### PR TITLE
Addition of parameter M200 - Set Filament Diameter

### PR DESCRIPTION
**Pull request by radek8**
Added the ability to turn on volumetric  extrusions and filament diameter settings

### CODE REVIEW

**Comment by digant73** [comment]
@radek too late unfortunately (as it happened also to me). The parameters should be placed (in all files) ordered by their gcode while instead M200 was put after M900. The same happened for M569 (it is after M913)

**Comment by radek8** [comment]
> @radek too late unfortunately (as it happened also to me). The parameters should be placed (in all files) ordered by their gcode while instead M200 was put after M900. The same happened for M569 (it is after M913)

I am sorry.
If you mean the sequence of commands in parseACK.c and interfaceCmd.c, I can fix it

**Comment by digant73** [comment]
everywhere, so also in machineParameter etc... Noh, no problem. Just a suggestion to follow for your next PR

**Comment by radek8** [comment]
In Parametersetting.c I have it arranged intentionally.
CURRENT_SETTING, BUMP_SENSITIVITY, HYBRID_THRESHOLD, STEALTH_CHOP
I wanted to leave the TMC driver items together.

I placed the fiber diameter setting behind the linear edvance, because these are the parameters that relate to the filament extrusion.

**Comment by digant73** [comment]
I know the logic you used. I made the same with offset (home, probe, MBL) and guruatwhal explained to me the logic he originally followed.

**Comment by radek8** [comment]
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1697

**Comment by radek8** [comment]
Guruatwhal is preparing for a bigger change, so let us be surprised. :-)

**Pull request merged**
