### PR TITLE
Clickable upper icons during print

### PR DESCRIPTION
**Pull request by kisslorand**
### Requirements

BTT or MKS TFT

### Description

Nothing fancy, just during print the upper icons are clickable now, except the layer icon. After the print is done, those icons are not clickable anymore.

### Benefits

During print users can jump directly to heat, fan and speed/flow menu directly from the printing menu. Print time icon click is not implemented yet, that will have another PR.

### Related Issues

No issues, it is a user experience improvement, it implements FR #1506 and FR #1544.

### Ready for merge?

Yes.

### CODE REVIEW

**Comment by bttguy** [comment]
Very welcomed and well done PR! Thank you!

**Comment by sarvenn** [comment]
Hell yeah! Nail it @kisslorand!
For me, it was one of the most wanted feature to see as implemented.

**Comment by Wombat37** [comment]
I can't access these keys during printing with RRF. Do you want more details?

**Comment by sarvenn** [comment]
@bigtreetech please give it a spin. I want to try it asap :)

well done @kisslorand !

**Comment by oldman4U** [comment]
Why not trying it before it is merged?

**Comment by sarvenn** [comment]
> Why not trying it before it is merged?

I have my own taboos :)

**Comment by oldman4U** [comment]
Some taboos are not very clever.

**Comment by oldman4U** [comment]
@kisslorand 

This does not work on my TFT35 E3 v3. Should I check another BTT TFT?

**Comment by sarvenn** [comment]
> Some taboos are not very clever.

Well said.

**Comment by radek8** [comment]
It works well on my TFT35 E3 V3. The nozzle and bed temperature button is merged into one? Isn't that a shame?

**Comment by kisslorand** [comment]
Yes. nozzle and bed temperature button trigger is merged into one. It is done so to maintain the 8 button/menu standard across the firmware.

**Comment by oldman4U** [comment]
Have you dine anything special besides using kisslorands PR?

**Comment by radek8** [comment]
What kind of action is it going to be?

**Comment by kisslorand** [comment]
You'll see. ;)

**Comment by oldman4U** [comment]
I love secrets😌

**Comment by oldman4U** [comment]
Found the problem - sitting right in front of the computer....

Works great, THANK YOU!

**Comment by radek8** [comment]
I'm afraid of what you're preparing. That you want to put back the percentage of progress? :)

**Comment by oldman4U** [comment]
This would be great. 🙊

**Comment by oldman4U** [comment]
It is funny for me that so far, no user has been asking for the ability to see the number of layer which is currently printing. Are you all calculating it or do you use slicers which show the hight of the print and not the number of the layer? And I believe this information is available in all kinds of gCode. Isn't it!?

**Comment by kisslorand** [comment]
> I'm afraid of what you're preparing. That you want to put back the percentage of progress? :)

Why would you be afraid of that?

**Comment by radek8** [comment]
That was fun.

**Comment by kisslorand** [comment]
Than wait for the 3rd PR I am preparing for the PrintScreen There will be flames!
Of course, only if any of these will be merged.

**Comment by oldman4U** [comment]
What makes you believe they could not be merged?

**Pull request merged**
