### PR TITLE
PR-#1-LCD Brightness auto dim on idle

### PR DESCRIPTION
**Pull request by GeminiServer**
The LCD screen will dim to idle brightness, if the display is not touched for the period of the lcd idle timer. All settings are accessible from feature settings menu.
The idle time settings are randomly predefined and one custom time is setable within the conf file. 
The input could be a num_pad ui input. I have got a working version here, but need code/class clean/adaptions, so may be in a next pull request.

Bugfix - Default brightness assignment,  some code style adaptions and build warnings.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Should this be enabled by default?

**Comment by GeminiServer** [comment]
> Should this be enabled by default?

Upps.. did i forget the off ;). Which indeed should be default.

**Comment by GeminiServer** [comment]
> > Should this be enabled by default?
> 
> Upps.. did i forget the off ;). Which indeed should be default.

Done! Thx for your feedback. 
Cheers.

**Comment by thisiskeithb** [comment]
Which IDE do you use? It doesn't seem to follow the [`.editorconfig`](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/master/.editorconfig) file.

**Comment by GeminiServer** [comment]
> Which IDE do you use? It doesn't seem to follow the [`.editorconfig`](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/master/.editorconfig) file.

Vs code under macOS

**Comment by thisiskeithb** [comment]
Do you have the [editorconfig](https://github.com/editorconfig/editorconfig-vscode) plugin installed? That'll help with code formatting (no whitespace at the end of lines, indent style, new line at the end of each file, etc).

**Comment by GeminiServer** [comment]
> Do you have the [editorconfig](https://github.com/editorconfig/editorconfig-vscode) plugin installed? That'll help with code formatting (no whitespace at the end of lines, indent style, new line at the end of each file, etc).

The plugin wasn't installed. Now it is.

**Comment by thisiskeithb** [comment]
@GeminiServer You may be able to track this down faster than I can since you contributed the code, but when in Marlin Mode & the screen times out, it doesn't wake when pressing the encoder (pressing the screen wakes it).

See https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/483 for the full report.

**Pull request merged**
