### PR TITLE
Bugfix for PR #1680

### PR DESCRIPTION
**Pull request by kisslorand**
### Description

PR #1680 introduced a bug where if printing from SD remotely (Octoprint. Pronterface, etc) the printing menu would not activate, instead the TFT would stay at the menu where it was at the time the print started. 
This PR activates the printing menu and makes it next in line after the MainScreen. That means that after the print is finished and the user presses "Back" it will bring him to the MainScreen.

### Benefits

Everyone.

### Related Issues

No issue reported as it was discovered early in time.

### CODE REVIEW

**Comment by DaStivi** [comment]
@kisslorand is there ah reason you reverted #1680 back? i've justed tested this, and now neither if serial_always_on is enabled or disabled, i can't get into marlin mode anymore now?!

**Comment by DaStivi** [comment]
sorry for might generate some confusement... @guruathwal do i see that correctly you also allready reverted the #1691 bugfix of bugfix1680?  I don't see through it anymore 🙈 sorry... but anyhow i'am on the latest build now, and marlin mode doesn't work anymore, no matter if serial_always_on is enabled or disabled...

**Comment by guruathwal** [comment]
@DaStivi this is not related to #1673

**Comment by DaStivi** [comment]
> @DaStivi this is not related to #1673.
> P.S. I tested the latest commit and Marlin mode is booting with LPC based mainboard with TFT set to marlin mode with and without serial_alway_on active.

yeah, i have gone back to your initial change to fix it... its still not working.. so i don't know what happend, i gonna reset.txt the tft now... maybe it was ah issue while i gona way back to the bug version to test the octoprint-print screen i did in 1673  just had the 1681 now in mind as this reverted it... but when i have got everything correct you again reverted 1681 so it should be fixed again right now in latest builds, isn't it?

**Comment by guruathwal** [comment]
you need to ignore this PR(#1680) and check PR #1686.

**Comment by DaStivi** [comment]
> > @DaStivi this is not related to #1673.
> > P.S. I tested the latest commit and Marlin mode is booting with LPC based mainboard with TFT set to marlin mode with and without serial_alway_on active.
> 
> yeah, i have gone back to your initial change to fix it... its still not working.. so i don't know what happend, i gonna reset.txt the tft now... maybe it was ah issue while i gona way back to the bug version to test the octoprint-print screen i did in 1673 just had the 1681 now in mind as this reverted it... but when i have got everything correct you again reverted 1681 so it should be fixed again right now in latest builds, isn't it?

ok, it was my fault, sorry for the double confustion... marlin mode didn't worked because i used an old config.ini file where the new #### Marlin Mode Type
# Select Marlin Mode type.
#   Options: [128x64 Full Graphic LCD: 0, 20x4 Character LCD: 1]
marlin_type:0

options was not init... @guruathwal might be a good idea btw. to change the default behavior to the 128x64 mode, even without having it in config.ini to prevent DAUs like me :)

**Pull request merged**
