### PR TITLE
cleanup & fix st7920 simulator (add klipper support)

### PR DESCRIPTION
**Pull request by Msq001**
### Description

* cleanup st7920, Fix occasional display offset bug
* st7920 simulator add support for klipper(Now the support is not perfect, because the compatibility problem, default code is used with Marlin, and if you want to use with kipper needs additional modification code).
  * if you use TFT24 V1.1, modify [stm32f10x hal](https://github.com/Msq001/BIGTREETECH-TouchScreenFirmware/blob/236c497d6050215b9674f6f78ffe0d581a834417/TFT/src/User/Hal/stm32f10x/spi_slave.c#L119)
  if you use TFT35 V3.0 etc.., modify [stm32f2xx hal](https://github.com/Msq001/BIGTREETECH-TouchScreenFirmware/blob/236c497d6050215b9674f6f78ffe0d581a834417/TFT/src/User/Hal/stm32f2xx/spi_slave.c#L118)
  from   `SPI_ReEnable(!!(GPIOB->IDR & (1<<13)));` to `SPI_ReEnable(0);`(because Marlin lpc176x st7920 spi is mode 0, but avr & stm32 is mode3, so marlin need to adapt by itself, but klipper is mode0, and the logic of SCK seems abnormal, so it cannot adapt, please set to mode 0 directly)
  * please modify [void ST7920_DrawGDRAM(uint8_t data)](https://github.com/Msq001/BIGTREETECH-TouchScreenFirmware/blob/236c497d6050215b9674f6f78ffe0d581a834417/TFT/src/User/API/UI/ST7920_Simulator.c#L347) function from 
```
void ST7920_DrawGDRAM(uint8_t data)
{
  if (st7920_reg.fs.g != 1) return; // Graphic display off
  for (uint8_t i = 0; i < 8; i++) {
    if (data & 0x80)
      ST7920_DrawPixel(st7920.x, st7920.y, true);
    else
      ST7920_DrawPixel(st7920.x, st7920.y, false);
    data <<= 1;
    st7920.x++;
  }
  if (st7920.x >= 128) {
    st7920.x = 0;
    st7920.y = (st7920.y + 32);
    if (st7920.y >= 64) st7920.y = (st7920.y + 1) & (64 - 1);
  }
}

```
  to 
```
void ST7920_DrawGDRAM(uint8_t data)
{
  if (st7920_reg.fs.g != 1) return; // Graphic display off
  for (uint8_t i = 0; i < 8; i++) {
    if (data & 0x80)
      ST7920_DrawPixel(st7920.x, st7920.y, true);
    data <<= 1;
    st7920.x++;
  }
  if (st7920.x >= 128) {
    st7920.x = 0;
    st7920.y = (st7920.y + 32);
    if (st7920.y >= 64) st7920.y = (st7920.y + 1) & (64 - 1);
  }
}
```
* There are still some unsolved bugs in the parts supporting klipper
  * The dynamic display of fan is abnormal in CGRAM when fan speed not 0
  * When the temperature changes in the status menu, the symbol of `°` will be covered by `space`
  * klipper st7920 fonts is stored in stm32 flash, this is temporary. next PR will move it to W25qxx, which is convenient for users to customize fonts
### Related Issues
#290

### CODE REVIEW

**Comment by vodic62** [comment]
Hi, thank you a lot for this commit. I already updated my TFT24 firmware, but my display is black most of the time. Only some times (once a day) it draws graphics on the display (works ok with Marlin). Same beahaviour I had with previous version o TFT24 firmware. Is my Klipper printer.cfg configuration of Bigtreetech SKR 1.3 board ok?

[board_pins]
aliases:
    # EXP1 header
    EXP1_1=P1.30, EXP1_3=P1.18, EXP1_5=P1.20, EXP1_7=P1.22, EXP1_9=<GND>,
    EXP1_2=P0.28, EXP1_4=P1.19, EXP1_6=P1.21, EXP1_8=P1.23, EXP1_10=<5V>,
    # EXP2 header
    EXP2_1=P0.17, EXP2_3=P3.26, EXP2_5=P3.25, EXP2_7=P1.31, EXP2_9=<GND>,
    EXP2_2=P0.15, EXP2_4=P0.16, EXP2_6=P0.18, EXP2_8=<RST>, EXP2_10=<NC>
    # Pins EXP2_1, EXP2_6, EXP2_2 are also MISO, MOSI, SCK of bus "ssp0"

[display]
lcd_type: st7920
cs_pin: EXP1_4
sclk_pin: EXP1_5
sid_pin: EXP1_3
encoder_pins: ^!EXP2_3, ^!EXP2_5
click_pin: ^EXP1_2
kill_pin: ^!EXP2_8

**Comment by dushyantahuja** [comment]
Same here - just uploaded the latest firmware to my TFT24 (compiled from the latest source) - and have the following in my config:
```
[board_pins]
aliases:
    # EXP1 header
    EXP1_1=P1.30, EXP1_3=P1.18, EXP1_5=P1.20, EXP1_7=P1.22, EXP1_9=<GND>,
    EXP1_2=P0.28, EXP1_4=P1.19, EXP1_6=P1.21, EXP1_8=P1.23, EXP1_10=<5V>,
    # EXP2 header
    EXP2_1=P0.17, EXP2_3=P3.26, EXP2_5=P3.25, EXP2_7=P1.31, EXP2_9=<GND>,
    EXP2_2=P0.15, EXP2_4=P0.16, EXP2_6=P0.18, EXP2_8=<RST>, EXP2_10=<NC>
    # Pins EXP2_1, EXP2_6, EXP2_2 are also MISO, MOSI, SCK of bus "ssp0"

[display]
lcd_type: st7920
cs_pin: EXP1_4
sclk_pin: EXP1_5
sid_pin: EXP1_3
encoder_pins: ^EXP2_3, ^EXP2_5
click_pin: ^!EXP1_2
#kill_pin: ^!EXP2_8
```
Still doesn't work - I just get a blank screen with "LCD12864 simulator" on top
Has anyone got it working - can you please advise if I've got the pins wrong, or maybe something else.

**Comment by Msq001** [comment]
Hello have modify here

>  * st7920 simulator add support for klipper(Now the support is not perfect, because the compatibility problem, default code is used with Marlin, and if you want to use with kipper needs additional modification code).
>   * if you use TFT24 V1.1, modify [stm32f10x hal](https://github.com/Msq001/BIGTREETECH-TouchScreenFirmware/blob/236c497d6050215b9674f6f78ffe0d581a834417/TFT/src/User/Hal/stm32f10x/spi_slave.c#L119)
>   if you use TFT35 V3.0 etc.., modify [stm32f2xx hal](https://github.com/Msq001/BIGTREETECH-TouchScreenFirmware/blob/236c497d6050215b9674f6f78ffe0d581a834417/TFT/src/User/Hal/stm32f2xx/spi_slave.c#L118)
>   from   `SPI_ReEnable(!!(GPIOB->IDR & (1<<13)));` to `SPI_ReEnable(0);`(because Marlin lpc176x st7920 spi is mode 0, but avr & stm32 is mode3, so marlin need to adapt by itself, but klipper is mode0, and the logic of SCK seems abnormal, so it cannot adapt, please set to mode 0 directly)

it's very important!

**Comment by vodic62** [comment]
I have followed your instructions and made modifications of spi_slave.c and ST7920_Simulator.c and compiled. Last week with old revision (without font support) I had black screen with occasional draw of graphics without fonts. With this latest revision with modifications from description I have black screen also, but I had no graphics redraw ever till now. Only some garbage on screen with some changes when rotating encoder happened yesterday.

**Comment by Msq001** [comment]
Hello, please try this .bin firmware.
[BIGTREE_TFT24_V1.1.26.1.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4677326/BIGTREE_TFT24_V1.1.26.1.zip)

if it's ok, please set `SPI_ReEnable(!!(GPIOB->IDR & (1<<13)));` to `SPI_ReEnable(1)` not `SPI_ReEnable(0)` for TFT24 V1.1

**Comment by dushyantahuja** [comment]
Great, thanks - this works great.

**Comment by vodic62** [comment]
I can confirm that when I made fresh git clone and made instructed modification my display started to work. Thank you.

**Comment by Tygrys-1** [comment]
Can this be related to #735 ?

**Comment by dushyantahuja** [comment]
hmmm - it's still not perfect - especially when you reset the printer using the reset button on the TFT. Refuses to show anything after that.

**Comment by DroneMang** [comment]
Does this update work now for klipper?  Do I just follow the instructions on the main page to update or are there specifics for the BIGTREE_TFT24?  Thanks!

**Comment by DroneMang** [comment]
The TFT24 display doesn't appear to work with Klipper.  I just tried this with the precompiled firmware from BTT and by compiling it, with the unified menu and standard, and nothing shows up other than LCD12864 simulator.  I have an SKR pro.

**Comment by rizwansarwar** [comment]
It does not still work properly. My screen sometimes shows up, sometimes it disappears completely and sometimes it shows total garbage on the screen. I think your fix does not totally fix the real issue.

**Comment by DroneMang** [comment]
I agree. I have to restart the firmware and klipper multiple times to get
something to show on the screen sometimes. Also the print progress was not
updating during a print. Hopefully this gets fixed! Thanks.

**Comment by Bl00d0und4** [comment]
Someone have a Wire Diagramm Form TFT24 v1.1?

**Pull request merged**
