### PR TITLE
updated Polish language file

### PR DESCRIPTION
**Pull request by NOVAXIM**
### Description

The translation is direct taken from the English version V3.0.27.x (20210903).
I tested the translation on the live screen. Nomenclature tailored to the specific content on the screen to make it logically consistent. Some texts have been shortened to fit on the screen.

### Benefits

I have translated many texts that have not yet been translated. This translation is done with great care for the logical meaning of the text with on-screen action.

### Related Issues

There should not be any problems.

### CODE REVIEW

**Comment by digant73** [comment]
You applied the changes to the wrong file.
The changes must be applied to TFT\src\User\API\Language\language_ph.h

**Comment by NOVAXIM** [comment]
> 
> 
> You applied the changes to the wrong file. The changes must be applied to TFT\src\User\API\Language\language_ph.h. The .ini file is autogenerated from the .h file

1. This file is for uploading to an SD card, not for compilation.
2. My country code is PL (ISO 3166 standard) so I don't understand why are you providing the language file for Philippines.
3. I didn't know that it is automatically generated. I will correct and upload again new 'language_pl.h' file in 'TFT/src/User/API/Language/'. Be patient.

**Comment by digant73** [comment]
I typed language_ph.h by mistake. I meant language_pl.h.

**Comment by NOVAXIM** [comment]
I closed this pull request and opened the new one correctly. Thank you for your help.

**Pull request closed without merging**
