### PR TITLE
Added a way to make a manual input to screen showing a value ( Temp, flow , speed etc...)

### LINKED ISSUE #1046: [FR] Manual way to enter temperature in touchscreen mode.
It would be practical to have a way to manually enter the temperature in touchscreen mode and not having to press multiple times the + button.

If you guys want I can implement it myself. I already forked the firmware and started working on it. As a matter of fact I already have it working on my screen.

### PR DESCRIPTION
**Pull request by Hyrules**
### Description

If you tap anywhere in the zone of the display showing a value a manual way to input shows up. This works with the Heat, Pid Tuning and Tune Extruder menu and mostly all the menus showing a value where the button 2 and 3 would be.
IMG_20200918_194919

### Benefits

Avoid the needs of pressing multiple times on the incremental or decremental button for many screens and input exact value.

### Related Issues

Resolves #1046

### CODE REVIEW

**Comment by traffic-light** [comment]
@Hyrules can you add resolves in front of the number of the function request in the pull request?

This will automatically close the ticket when it's merged.

**Comment by traffic-light** [comment]
Can you add this one to the extruder tuning I made a couple of weeks ago?
Otherwise I will do it in my next pull request;-)

**Comment by Hyrules** [comment]
No problem I will add this to the extruder tuning. I have edited the my pull request to add Resolves. You can pull if you want I will do another pull request today.

**Review by Hyrules — COMMENTED** [review]
Added TuneExtruder menu manual temp

**Comment by traffic-light** [comment]
Can you take a look at my code reviews?
It would be nice if the code is aligned correctly ;-)

**Comment by Hyrules** [comment]
Will check. I having some issues with VS code and the files. My setup is with tabs as the files are using spaces for indentations. Makes a mess in the files when I'm indenting.

**Comment by traffic-light** [comment]
You should deactivated the auto allignment.

  *   ctr + , (ctr+comma)
  *   press workspace tab
  *   search for "Clang_format_style"
  *   For both:
     *   Enter in the field deactivated (or anything else that doesn't exsist)

This way you adjust only for this workfolder a diffrent format style.
It will do nothing and come up with an error the first time.

Hope it will help you

Met vriendelijke groet;
Peter van Weeterloo
________________________________
Van: Hyrules <notifications@github.com>
Verzonden: dinsdag 22 september 2020 13:10
Aan: bigtreetech/BIGTREETECH-TouchScreenFirmware <BIGTREETECH-TouchScreenFirmware@noreply.github.com>
CC: Peter van Weeterloo <info@petrossystems.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [bigtreetech/BIGTREETECH-TouchScreenFirmware] Added manual temperature input to the temperature screen, pid tune screen and extruder tune screen (#1104)


Will check. I having some issues with VS code and the files. My setup is with tabs as the files are using spaces for indentations. Makes a mess in the files when I'm indenting.

**Comment by Hyrules** [comment]
I have fixed the indentation in my files. Hope this is ok.

**Comment by Hyrules** [comment]
The flash file is too big for the firmware has does one fix this ? I have updated my branch with the latest version or the firmware but it's failing because of the size of the firmware.

**Comment by traffic-light** [comment]
Yup. You've got to wait until BTT removes the choice of languages. They will make it that you can choose it when you build the firmware (it's pretty useless to have all the languages available when you just use one...)

**Comment by Hyrules** [comment]
Roger that. Will be waiting.

**Comment by oldman4U** [comment]
Hi.

This should be fixed with Gurmeets PR merged yesterday.

Could you please try it

Thank you

**Comment by oldman4U** [comment]
Hi. With the last few firmware versions it is possible to open the Echo/M117 window by pressing the Info window of the main Pre Print screen. This is a two button window also, so there must be a way now to get this without the gap. Gurmeet added this functionality app. a month ago.

**Comment by Hyrules** [comment]
I will check this tonight or tomorrow keep you posted. Meanwhile don't mind the checks I just merge my repo with the latest version of this repo.

**Comment by Hyrules** [comment]
I have found the way to do it. It's not simple at frist glance but it's doable. I will try to implement it. it will most likely take a day or two.

**Comment by Hyrules** [comment]
It's done. I have fixed the issue. There is no more dead zone between the buttons and I have modified the 3 menus Heat, Pid and Tune to support this. I had to create a new mapping for the zone in the menu file.

**Comment by oldman4U** [comment]
Purrrrrrfect!!!

But why have you listed it too temp. only. Whats about the fan control? I believe this would be very useful also to control the speed of the fan.

**Comment by Hyrules** [comment]
Yeah I coud add that as well.  My original modification was for temp as I rarely play with fan speed in the menu.

There is the fan speed menu and the extrude menu as well which could have manual inputs. I'll modify them to add manual input as well.

**Comment by oldman4U** [comment]
This would be great. I mean, you have been adding one of the most requested features, so it would be great if you could add this to the other screens which are working similar also.

Would it be helpful for you to get a list of screens which could benefit from adding your code? I could help you with that.

**Comment by Hyrules** [comment]
Indeed it would be useful to have all the screen. Right now I have those : 

Heat, Extrude, Speed, PidTune, Fan, TuneExtrude

**Comment by oldman4U** [comment]
So this would be very helpful for the following screens:

Pre-Print:
Temp, Bed, Fan, Speed, Flow (Menu-Heat/Fan is probably the same)
Menu-Movement-Bed Level-ABL/MBL/..
Menu-Movement-Bed Level-ABL/MBL/.. Z Offset
Menu-Extrude
Menu-Settings-Machine-Tuning-PID
Menu-Settings-Machine-Tuning-Tune steps

Print:
More-Heat
More-Fan
More-Extrude
More-Percent-Speed
More-Percent-Flow
More-Machine-Tuning-PID
More-Machine-Tuning-Tune steps

The last two are useless during print, so if this is some extra work just leave them as they are.

THANK YOU!!!

**Comment by Hyrules** [comment]
Current Status of what is completed : 

Pre-Print:
~Temp, Bed, Fan, Speed, Flow~ (Temp and bed are the same, fan is unique , Speed and flow are the same menu)
Menu-Movement-Bed Level-ABL/MBL/..
Menu-Movement-Bed Level-ABL/MBL/.. Z Offset
Menu-Extrude (WIP)
~Menu-Settings-Machine-Tuning-PID~
~Menu-Settings-Machine-Tuning-Tune steps~

I think that the menus below are the same as the pre-print version I will test to make sure.

Print:
More-Heat
More-Fan
More-Extrude
More-Percent-Speed
More-Percent-Flow
More-Machine-Tuning-PID
More-Machine-Tuning-Tune steps

**Comment by oldman4U** [comment]
Hyrules comes from Hero, right;-)

**Comment by oldman4U** [comment]
Please check #1214 which could also benefit!

👍🏻

**Comment by Hyrules** [comment]
This would need to be pulled into the main repo in order for me to be able to modify it. When it will be pulled I will sync me repo with the main and modifiy the screen to be able to make manual input.

**Comment by oldman4U** [comment]
😎

Hyrules <notifications@github.com> schrieb am Do. 29. Okt. 2020 um 13:05:

**Comment by Hyrules** [comment]
I have every screen working except the probe offset for whatever reason it crashes the screen when I try to redraw the menu after closing the numpad. I'm not sure what's the best way to debug this.

**Comment by oldman4U** [comment]
But it is solved?

**Comment by Hyrules** [comment]
Almost finished I just have to figure out how to get a label fro the z-offset and then I will be able to add it to the screen. There might still be a screen I have to modify ABL/MBL one i havn't seen yet.

**Comment by oldman4U** [comment]
What do you mean with label?

Hyrules <notifications@github.com> schrieb am Sa. 31. Okt. 2020 um 16:00:

**Comment by Hyrules** [comment]
when you open a numpad there is a label at the top normaly it's used to show the max and min but for the z-offset there is no max and min values for it so I want to display the text z-offset. This piece of text is somewhere in the language definition of the screen and I have to somehow load it and pass a pointer to the array to the numpadfloat method to display as a label / title. This is what i'm currently trying to do.

**Comment by Hyrules** [comment]
Ok just figured it out. Now my only lasting issue is the MLB (Mesh Bed Leveling) menu. I have to find a way to see the menu to test my modifications. I just have to figure out the autodetection that makes the printer see the bed leveling as Mesh Bed Leveling to implement that in my test app.

**Comment by oldman4U** [comment]
Hi.

DO you need any help. Maybe I have some time tomorrow.

Please let me know

**Comment by Hyrules** [comment]
Thanks i'm ok for the moment. I won't have time to work on this before the weekend though.

**Comment by oldman4U** [comment]
@radek8 

Could you pls tell us what is needed to get the MBL menu on screen, so Hyrules can add the great numpad to this menu also.

Thank you!

**Comment by GregSKR** [comment]
Nice work, thanks ! 👍 

BTW: Maybe I'm wrong, but looks like there is an extra comma at the end of line 119 that should not be there ?
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/468176ad38097fb9249744d37f009573e7e72a29/TFT/src/User/API/menu.c#L119

**Comment by oldman4U** [comment]
Welcome back, GregSKR. We missed you;-)

**Comment by traffic-light** [comment]
@bigtreetech i think it would be nice if this pr would be merged. :-)

**Comment by Hyrules** [comment]
Good idea. I will finish the other screens in another PR. So yes merging would be a good idea at the moment.

**Comment by ETE-Design** [comment]
@bigtreetech Could you pls. merge this, Phase 1.  seems to be ready :-)

**Comment by oldman4U** [comment]
Hi Hyrules.

I use this feature very often but would use it probably every time in case you could improve it even further by making the current value auto delete. Today you have to delete the current value before you can write a new one. Wouldn't it be great to delete the current value automatically by typing in the first number?

Just my 2 cents

Thank you

**Pull request merged**
