### PR TITLE
Update BIN files

### LINKED ISSUE #1175: BIGTREETECH TFT35 V2.0 BITMAPS MISSING ISSUE IN NON-UNIFIED UPDATE
AFTER FAILED UPDATES OF THE TFT35 V2 FIRMWARE I NOTICED THAT THE BMP FILES ITS ASKING FOR ARE MISSING FROM THE BMP FOLDER.. THE UNIFIED FIRMWARE HAS ALL OF THE BMPS BUT THE OTHER ONE, I GUESS ITS THE WORDED TYPE AND NOT PICTURE ICON UNIFIED BECAUSE IT WORKS.. SO THE ORIGINAL WORDED ICON BITMAP FOLDER HAS BITMAPS MISSING... @BIGTREETECH PLEASE FIX THE TFT35 MISSING NON-UNIFIED BITMAPS.. IF IM INCORRECT THEN PLEASE TELL ME WHAT THE ISSUE IS. I FOLLOWED ALL POSTED ADVICE ON HERE BUT NOTHING WORKS EXCEPT USING THE UNIFIED FOLDER BITMAPS..  I PREFER THE OTHER ONES, NOT THE UNIFIED PICTURE TYPES..  THANKS FOR ANY INSIGHT.

### LINKED ISSUE #1225: [BUG] Installing pre-configured firmware give errors/warnings
### Description

When I update my TFT35 display with the prepared firmware from the folder "Copy to SD Card root directory to update - Unified Menu Material theme" I get errors
* S_load.bmp and one other bitmap is missing.
* during "updating configuration" I get "Invalid keyword: mesh_max_color:2

Also strange: Is it normal that the GUI doesn't show bed and extruder temperature when heating up for a print job? My display stays as in the screenshot until the print starts, only then the current and expected temperatures are shown.

### Steps to reproduce

I downloaded the zip from github, copied
* TFT35 (folder)
* BIGTREE_TFT35_V3.0_E3.26.x.bin
* config.ini
on an SD card and inserted the card into the display to update.

### Hardware Variant

It's this display:
https://www.amazon.de/dp/B089SPPGKJ/?coliid=I3A06Y8U7J9O7E&colid=1Y5TQLAWV23RQ&psc=1&ref_=lv_ov_lig_dp_it

### TFT Firmware Version & Main Board Firmware details
* Marlin 2.0.7.2
* TFT_E3_V3.0.26.x Sept 12 2020

### Additional Information

IMG_20201030_235628
IMG_20201030_235658
IMG_20201030_235818
IMG_20201030_235855
IMG_20201030_235943

### PR DESCRIPTION
**Pull request by radek8**
Update BIN files

resolves #1225
resolves #1175

### CODE REVIEW

**Comment by oldman4U** [comment]
Have you used standard settings and compiled one firmware for each tft by changing the platformio.ini?

**Comment by radek8** [comment]
Yes default setting.
There is no need to change Platformio.ini.
You can manage FW for various TFTs with 2 clicks.

image

**Comment by traffic-light** [comment]
Isn't it better to remove them and place the important part, with additions, in the folder?

It's outdated really quick...

**Comment by oldman4U** [comment]
> Yes default setting.
> There is no need to change Platformio.ini.
> You can manage FW for various TFTs with 2 clicks.
> 
> image

OK, so you change the env in VSC - of course;-)

**Comment by oldman4U** [comment]
Can you please update your description to include 

resolves #1225

**Comment by Stellarspace** [comment]
I suggest getting rid of pre-compiled TFT firmware from the repository entirely in favor of automatic builds via [GitHub Actions](https://docs.platformio.org/en/latest/integration/ci/github-actions.html), but it probably won’t happen without continuously bugging @bigtreetech via email.

**Pull request closed without merging**
