### PR TITLE
add LCD2004 simulator

### PR DESCRIPTION
**Pull request by Subcircuit**
### Description
add LCD2004 simulator. Simulate the display effect of marlin lcd2004

### Related Issues
Bug not been found yet

### CODE REVIEW

**Comment by digant73** [comment]
Hi,

Nice work. I suppose it works only with BTT display and not also the MKS32 display, right?
I see that you defined a lot of pins and (as needed for Marlin mode) you updated the spi_slave.c to support the new mode. I'm trying to enable Marlin mode in the MKS TFT using the SPI3 but I have some problems with the PB3 pin assigned by default to Clock. The default pins for the SPI3 defined on the stm32f10x/spi.c are:

// SPI3 default pins config
#ifndef SPI3_SCK_PIN
  #define SPI3_SCK_PIN  PB3
#endif
#ifndef SPI3_MISO_PIN
  #define SPI3_MISO_PIN PB4
#endif
#ifndef SPI3_MOSI_PIN
  #define SPI3_MOSI_PIN PB5
#endif

I would like to change SPI3_SCK_PIN to PB1 (a free pin in the MKS TFT). However it seems that the change I made in SPI3_SCK_PIN has no effect. The spi_slave.c seems to always use PB3 instead of PB1 (or any other pin I set in spi.c).
Do you have any idea of this missing pin remap?
Attache the spi_slave.c I'm using. It is more or less same as the original spi_slave.c but SPI3 is used (ST7920_SPI is set to _SPI3) in pin_MKS_TFT28_v1_4.h
Thanks for any kind of support

[spi_slave_mks.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4973478/spi_slave_mks.zip)

**Comment by guruathwal** [comment]
Hi, this should be available as an option to choose between 2004 and 12864 in config.ini or configuration.h only, as the marlin firmware on any board will have only one of them.

**Comment by ETE-Design** [comment]
@digant73 If you sometimes for Marlin Mode Work on the MKS then pls. Make a PR. Would like to ha e that functions in my MKS also...

**Comment by guruathwal** [comment]
@digant73 the STM32 SPI only supports hardware pins in slave mode.

**Comment by digant73** [comment]
> @digant73 the STM32 SPI only supports hardware pins in slave mode.

Thanks. I just needed a confirmation.
I wired the PB3 pin from the chip to a free pin header in the board just to enable Marlin mode on my MKS TFT28.
I see the Marlin menu only powering the printer via USB (e.g. connected to PC) but when I switch on the printer from the main power the menu disappers and a black screen and/or wrong characters are displayed. I tried to set several delays on Marlin FW but I didn't solve the problem.
Futhermore, when the Marlin mode is correctly displayed (so via USB only), only the emulated rotary button works (pressing on top right corner). The emulated arrows to scroll on the menu doesn't work.
I made the FDD cable as short as possible. The continuity on each line of the FDD cable is OK (checked with a tester) and also the continuity from the pins in the chip to the pin headers in the board are OK

Do you have an idea on how to solve these two problems (black screen) and emulated rotary not fully working (with the exception of the select button)?

**Comment by digant73** [comment]
> @digant73 If you sometimes for Marlin Mode Work on the MKS then pls. Make a PR. Would like to ha e that functions in my MKS also...

That is my idea when I will solve the problems explained to guruatwhal. However you must have soldering skills to wire one pin from the chip to a free pin header in the board

**Comment by guruathwal** [comment]
@digant73  It is strange behaviour, but you may want to check the voltage when connected to USB and when connected to the board's power supply. 
also, did you connected the SPI pins to the pins used by SD card?

**Comment by digant73** [comment]
> @digant73 It is strange behaviour, but you may want to check the voltage when connected to USB and when connected to the board's power supply.
> also, did you connected the SPI pins to the pins used by SD card?

Not, yet. I will check the voltage on all the 6 pin used for marlin mode. 

Here, the connection schema used for Marlin mode:

MKS TFT FW pins      MKS TFT HW pins / board pins         MKS Gen L V1.0 HW pins   Marlin FW pins
// ---------------        -----------------------------                ----------------------           ---------------
// LCD_ENCA_PIN      PA13 / JTAG DIO                      =>   EXP2 D31                            BTN_EN1
// LCD_ENCB_PIN      PA14 / JTAG CLK                      =>   EXP2 D33                            BTN_EN2
// LCD_BTN_PIN        PB0  / PB0                                =>   EXP1 D35                             BTN_ENC
// SPISIM_CS_PIN      PB1  / PB1                                =>   EXP1 D16                             LCD_PINS_RS
// SPI3_SCK_PIN        PB3  / NC WiFi (wired to PB3)  =>   EXP1 D23                            LCD_PINS_D4
// SPI3_MOSI_PIN     PB5  / PB5                                 =>   EXP1 D17                            LCD_PINS_ENABLE

In the pin_MKS_TFT32_V1_4.h I set the following:

#define ST7920_SPI    _SPI3            // uncomment to enable Marlin mode

// Marlin mode + LCD Encoder support
#ifdef ST7920_SPI
  #define LCD_ENCA_PIN  PA13           // map ENCA pin to JTAG DIO pin
  #define LCD_ENCB_PIN  PA14           // map ENCB pin to JTAG CLK pin
  #define LCD_BTN_PIN   PB0            // map BTN pin to PB0 pin

  #define SPISIM_CS_PIN PB1            // CS pin used for SPI3 slave mode to 
  #define DISABLE_DEBUG                // free JTAG(PB3/PB4) for SPI3 and free SWDIO PA13 PA14 for encoder pins
#endif

As you see I disabled DEBUG mode in order to free PB3/PB4 for SPI3 (in spi.c default pins for SPI3 are PB3, PB4 and PB5) and PA13/PA14 for endoder pins.
Is it possible that disabling DEBUG mode is not enough to reuse those pins for SPI3 and lcd encoder?

**Comment by OrangePrilip** [comment]
so as not to create a new question. ask it here. is it possible to add a protocol to connect to smoothie? (skr 1.3 , tft3.5_v3.0)

**Comment by Subcircuit** [comment]
@guruathwal 
Thank you for mentioning this.  I will improve it.

**Comment by ETE-Design** [comment]
@digant73 Did you get the Marlin Mode working?

**Comment by digant73** [comment]
@ETE-Design yes, but soldering skills are required to wire the PB3 pin from the chip to a free pin header in the board

**Pull request merged**
