### PR TITLE
fix TFT70 display bugs

### PR DESCRIPTION
**Pull request by bigtreetech**
### Description
* back from "Click for summary " still have bugs,  will fix later

### Related Issues
#1659

### CODE REVIEW

**Comment by AntoszHUN** [comment]
All right! Thanks! I'm testing.

**Comment by AntoszHUN** [comment]
I did a few tests. At the end of printing, when printing is complete, the object cooling fan does not stop. The display shows 0%. The other photo shows it still going. Also, do not turn on the subject cooler while printing, even though it has shown 10%. It only turns on when I enter and set the menu.

DSC_0030
DSC_0031

Made By: AntoszHUN

**Comment by AntoszHUN** [comment]
I'm testing the fixes.

**Comment by bigtreetech** [comment]
> I'm testing the fixes.

Only the bug on the interface has been fixed now.  I haven't tested the fan part yet. but I'm still working on it

**Comment by bigtreetech** [comment]
> I did a few tests. At the end of printing, when printing is complete, the object cooling fan does not stop. The display shows 0%. The other photo shows it still going. Also, do not turn on the subject cooler while printing, even though it has shown 10%. It only turns on when I enter and set the menu.

Is the gcode file you printed from onborad SD or TFT SD?

**Comment by AntoszHUN** [comment]
> Is the gcode file you printed from onborad SD or TFT SD?

I printed from TFT SD.

**Comment by AntoszHUN** [comment]
There is another problem here. If I start printing by clicking on the file on the TFT SD card, it will heat up the devices by default. This is not how it works. It heats up the table (80°C) this is fine. Then it starts printing. The nozzle will not be heated.

**Comment by bigtreetech** [comment]
Can you share the gcode files you use? I can't reproduce this problem here

**Comment by AntoszHUN** [comment]
There is another bug here that I think can be problematic for the stable operation of the TFT70. The picture shows that no good MCU is associated with the TFT70 display. To the best of my knowledge, there is an STM32F407VGT6 in this display.

**Comment by AntoszHUN** [comment]
> 
> 
> Can you share the gcode files you use? I can't reproduce this problem here

Naturally. I used this.
[FLAGGG.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6081559/FLAGGG.zip)

**Comment by bigtreetech** [comment]
> There is another bug here that I think can be problematic for the stable operation of the TFT70. The picture shows that no good MCU is associated with the TFT70 display. To the best of my knowledge, there is an STM32F407VGT6 in this display.
> 

#1562 will solve the problem. It will be merged soon

**Comment by AntoszHUN** [comment]
> 
> 
> > There is another bug here that I think can be problematic for the stable operation of the TFT70. The picture shows that no good MCU is associated with the TFT70 display. To the best of my knowledge, there is an STM32F407VGT6 in this display.
> > 
> 
> #1562 will solve the problem. It will be merged soon

I understand. Super.

**Comment by bigtreetech** [comment]
> There is another problem here. If I start printing by clicking on the file on the TFT SD card, it will heat up the devices by default. This is not how it works. It heats up the table (80°C) this is fine. Then it starts printing. The nozzle will not be heated.

image

It's working as expected here. Can you repeat this problem? Can you reproduce this problem steadily? Or is it random?

**Comment by AntoszHUN** [comment]
> 
> 
> > There is another problem here. If I start printing by clicking on the file on the TFT SD card, it will heat up the devices by default. This is not how it works. It heats up the table (80°C) this is fine. Then it starts printing. The nozzle will not be heated.
> 
> image
> 
> It's working as expected here. Can you repeat this problem? Can you reproduce this problem steadily? Or is it random?

The problem keeps coming up. But I see you are not heated by the nozzle either. Did you start printing with cold nozzle? Because for me, yes.

**Pull request merged**
