### PR TITLE
Round icons for PR 2084

### PR DESCRIPTION
**Pull request by radek8**
Round icons for PR 2084
Addition of CZ translation

### CODE REVIEW

**Comment by digant73** [comment]
@radek "status_chamber.bmp" is wrongly named as "status_chander.bmp" on TFT24 and TFT28

**Comment by radek8** [comment]
> @radek "status_chamber.bmp" is wrongly named as "status_chander.bmp" on TFT24 and TFT28


Sorry, I'll fix it tonight.

**Comment by digant73** [comment]
no problem. I'm pushing a PR just now, so I will also rename those two bmp files

**Comment by radek8** [comment]
Thank you

**Pull request merged**
