### PR TITLE
Centering round icons

### PR DESCRIPTION
**Pull request by radek8**
Centering round icons

### CODE REVIEW

**Comment by kisslorand** [comment]
Thank you !!!

**Comment by radek8** [comment]
> Děkuji !!!

Can you test if it's okay?
Thank you.

**Comment by kisslorand** [comment]
I can test now for 3.5" and in 30 minutes the 2.8".

**Comment by kisslorand** [comment]
Later edit: I would put one pixel more higher the text area for the status screen icons on 320x240 TFTs. I compared 480x320 and 320x240. 
It would look even more vertically centered. Just test it and see.

**Comment by radek8** [comment]
I don't have TFT24 so I can't test.
So I move up another pixel.

**Comment by kisslorand** [comment]
Why 2 pixels?

**Comment by radek8** [comment]
Total 2
The first was one pixel and now the second pixel

**Comment by kisslorand** [comment]
Ah! Than it should be just perfect.
Thank you very much !!!

**Comment by radek8** [comment]
Perhaps

image

**Comment by kisslorand** [comment]
On my TFT28 with a total of 2 pixels up looks perfect.

**Comment by radek8** [comment]
> On my TFT28 with a total of 2 pixels up looks perfect.

OK

**Comment by kisslorand** [comment]
Anyone else around testing the other resolutions?

**Comment by radek8** [comment]
TFT70 would need to be tested.
The preheat icon may not be in the correct position

image

**Comment by xPew** [comment]
@kisslorand Can you check on my theme for this regards? (RRF dark) I tried to copy the layout of the original material UI, but who knows...
Also, there were recently some icon changes, I got pinged somewhere, but I couldn't find it anymore. Can somebody guide me on what bmp-s I need to change in my theme to fit for the latest changes? I would do it but I don't know what to do exactly as I still just learning github and contribution...

**Comment by kisslorand** [comment]
@xPew 
I can check it but only on two resolutions but I think @radek8 can do a better job on this. He can compare the icons on his computer and spot the eventual differences better than me on my TFT.

**Comment by radek8** [comment]
> @xPew I can check it but only on two resolutions but I think @radek8 can do a better job on this. He can compare the icons on his computer and spot the eventual differences better than me on my TFT.

The placement of the text boxes is OK. Icon names fixed by digant73

**Comment by xPew** [comment]
Thank you guys! :)

**Pull request merged**
