### PR TITLE
 Translation and Font for Russian

### PR DESCRIPTION
**Pull request by Acenotass**
Corrected the translation of the Russian language.
Edited "word_unicode.fon" - fixed English and Russian characters on the font Ubutu. (Additional letters of other European languages ​​did not correct, there are a lot of them)
It makes sense to refuse the file "byte_ascii.fon" because "word_unicode.fon" already contains all the English characters.

Sample

### CODE REVIEW

**Comment by guruathwal** [comment]
I do not know any thing about  Russian language but the Russian characters in the TFT35 are treated as 12x24 size characters.

**Comment by Acenotass** [comment]
Russian

Yes, they are located in a 12x24 table, and everything is perfectly displayed

IMG_20191227_175618_cr

**Comment by guruathwal** [comment]
Nice.. you should update the 8x16 version also

**Comment by Acenotass** [comment]
You can do it yourself using the font editor.
http://corosan.ru/sgfed/

**Comment by Rigid3D** [comment]
@Acenotass Would you please share the latest source of sgfed file that you are working on? I would like to correct the Turkish characters without loosing your work on Russian characters.

I think it would be a good idea to add sgfed file to this repository for further development of other language specific characters?

**Pull request merged**
