### PR TITLE
Added Mono Theme

### PR DESCRIPTION
**Pull request by bepstein111**
New Mono Hybrid Theme based on the Red Hybrid Theme

### Requirements

Same as any other theme. I tried to follow the directory structure exactly.

### Description

This is a new grayscale theme for the BTT TFT screens. It is based on the Hybrid Red Material theme, so I called it the Hybrid Mono Menu Material theme. If this gets accepted, I'm thinking about also doing a mono Unified Menu Material theme if there's interest.

### Benefits

This was requested by someone on the BTT facebook group in a thread somewhere. It adds an extra theme for those who don't want crazy colors on their printer screen, and if you don't want to use it, you don't have to. There's no downsides other than filesize.

### Related Issues

None that I am aware of.

### CODE REVIEW

**Comment by oldman4U** [comment]
Hi. I like monochrome themes, this is great!

Maybe you want to check the onboard and on TFT sd icons again. The difference is hard to see, even they will get a label on screen. And I did not check if you already have the two new icons which are needed with the next PR from Gurmeet, one is brightness and one is Marlin Mode. Please check

If you want, I would add your theme to the ReadMe. For this it would be great if you could provide a screen work, like it is available for the other themes and I would need your OK to add your user name bepstein111 next to it.

Thank you and please let me know

oldman

**Comment by bepstein111** [comment]
Glad to hear it! I'll give them a double check, I thought I fixed everything that didn't look great after doing the batch processing, but it's probable that I missed a few. And also will check about brightness and marlin mode. That's different than marlin.bmp, I presume?

Once I fix those things, I'll absolutely give you permission to the files and putting my username next to it. I'll see what I can throw together in terms of a "screenshot," not sure how the others were done, but I'll probably just make it in Photoshop if that's okay, as I'm unaware of any means of taking a legit screenshot from the TFT. 

Thanks!
bepstein111

**Comment by oldman4U** [comment]
Hi.

So you can remove bgcolor.bmp and font color.bmp and you have to add  brightness.bmp and marlin_mode.bmp and also the ReadMe.md.

Yes, Marlin is different.

Some TFTs support screenshot, so in case you can provide the above, I can make the screenshot.

**Comment by bepstein111** [comment]
Sounds good, will get to that either sometime today or tomorrow.

**Comment by oldman4U** [comment]
This is a friendly reminder...;-)

When I saw your theme I remembered that I tried to make the round miracle monochrome a year ago or so. The problem with the colourful themes is, that you can not use color to highlight important things. Which is not a problem in case you have a lot of space, but on such small screens you need every possible method to highlight important things.

**Comment by bepstein111** [comment]
Sorry, life happened! Working on it right now though

**Comment by oldman4U** [comment]
No stress!

**Comment by bepstein111** [comment]
I think that's it? Let me know if I need anything else! I don't think I can make a screenshot on my end unfortunately.

**Comment by oldman4U** [comment]
Hi, looks good.

The screenshot function only works with certain screens, like the TFT43. Attached a screenshot, will try to make it like the other screenshots and update the ReadMe.md asap.

Thank you


Ready_0

**Comment by bepstein111** [comment]
Great! Ahh, yes I only have the TFT35-E3. Looks great, thank you!

**Comment by bigtreetech** [comment]
Hello, Are all the icons ready? Can I merge it?

**Comment by oldman4U** [comment]
It is not my PR but for me it looks good. Will update the ReadMe in about 12h

**Comment by bepstein111** [comment]
> Hello, Are all the icons ready? Can I merge it?

Icons are good to go!

**Comment by oldman4U** [comment]
Monochrome TFT35

OK, what is the name of the theme?

Hybrid Mono Material Theme by bepstein111?

**Comment by bepstein111** [comment]
That works great.

**Comment by ETE-Design** [comment]
@bepstein111 would be great if you could take your time and do the same to the Unified Menu Material Theme :-D

**Comment by bepstein111** [comment]
> @bepstein111 would be great if you could take your time and do the same to the Unified Menu Material Theme :-D

That is absolutely the plan once I get some more free time on my hands!

**Comment by DaStivi** [comment]
there is ah really nice "black/dark" theme available on reddit for the TFT35!
https://www.reddit.com/r/BIGTREETECH/comments/lpfcw2/i_updated_the_dark_clean_theme_for_tft35_displays/

**Comment by bepstein111** [comment]
@DaStivi  that's correct. personally, that's the one I use on my screens. But since they don't feel like uploading it to the repository, and I don't want to steal their work and claim it as my own, I took one of the existing themes and turned it into something similar for people who don't know what a reddit is.

**Comment by AntoszHUN** [comment]
Hi! I spent days making the topic. But I didn't think anyone was going to spoil it.

Mady By: AntoszHUN

**Comment by oldman4U** [comment]
It is a replication of art.

😁

Zs.Antal ***@***.***> schrieb am Fr. 12. März 2021 um 05:52:

**Comment by AntoszHUN** [comment]
That's not mine anymore. It fell a little bad for me as a maker. :( That means I didn't do a good job. For those who don't want to see color icons, buy a 12864 LCD display.

**Comment by oldman4U** [comment]
You should be proud and I hope someone will make the same with the other
two themes.

Zs.Antal ***@***.***> schrieb am Fr. 12. März 2021 um 06:06:

**Comment by AntoszHUN** [comment]
Of course, I was stabbed when I touched on another topic. #1669

**Comment by bepstein111** [comment]
Sorry, entirely my fault, of course all credit for the original icons goes to AntoszHUN, all I did was spend some time in photoshop making sure they all looked decent in grayscale. Don't know where my mind was at.

**Pull request merged**
