### PR TITLE
Standard deviation - BLTouch repeatability test

### LINKED ISSUE #1102: [FR] (standard deviation on repeatability test )
**Is your feature request related to a problem? Please describe.**

it would be nice to also be able to enter the standard deviation along with the other data when the test repeatability is performed.

### PR DESCRIPTION
**Pull request by kisslorand**
### Requirements

BTT TFT ot MKS TFT

### Description

This PR adds the missing "Standard deviation" info on BLTouch repeatability test. It was done taking extra care not to increase RAM usage. Additional optimizations were made to reduce compiled size.

### Benefits

It enhances the informations displayed when a  BLTouch repeatability test is done.

### Related Issues

Fixes #1102

### RAM & Flash impact

**RAM** -> 0 bytes extra
**Flash** -> 368 bytes extra 

### Additional info

NO, the things introduced in this PR are NOT user selectable, there is NO adjustable thing in config.ini nor in parameters settings. There's NO additional popup. Nothing was removed, it's an extra.

### CODE REVIEW

**Comment by digant73** [comment]
Please revert abl, mbl, mesheditor, pid, probeoffset. They used the most correct and safe buffer copy

**Comment by kisslorand** [comment]
Please help me understand what's the problem as it is? (other that there are two typos I missed)

**Comment by kisslorand** [comment]
9e5e449 - (theoretically) faster string concatenation and format, reduced compiled size
2a62a8d - safer string concatenation and format as per @digant73's advice, compiled size bigger by 204 bytes.

In my tests I couldn't find any difference in functionality between the two commits mentioned.

**Comment by ETE-Design** [comment]
Is this also for the M48 repeatability test, and could you mabye add an button to run the process then?

**Comment by kisslorand** [comment]
There is a button for this. 
Menu -> Move -> Bed LEvel -> ABL -> BLTouch -> Repeat

**Comment by ETE-Design** [comment]
@kisslorand Ahh haven't seen that, cause don't use an BLTouch but an Inductive Sensor so dosen't make sense I have to look there  to do a M48 who work on all sensors... And the rest of the options inside BLTouch is just for BLTouch... Mabye that function should be moved to another place so people with other sensors know the M48 is possible...

**Comment by kisslorand** [comment]
Everyone can do it easily, just put M48 in your custom gCode list in Config.ini.

**Comment by kisslorand** [comment]
@bigtreetech 

This PR is ready to be merged, no bugs found nor reported, no conflicts with master branch.
You can choose the flavor you like from these two from here: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1484#issuecomment-755429269

**Pull request merged**
