### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by oldman4U**
Add information about config.ini and that it has to be updated together with the firmware and the TFT folder

### CODE REVIEW

**Comment by Acenotass** [comment]
@oldman4U 
It makes sense to specify that the config.ini file must contain UTF encoding.
Otherwise, the firmware freezes, I had it when they made menu items in Russian, but saved it in windows 1251 encoding.

**Comment by oldman4U** [comment]
Hi. 

UTF or should I mention a specific encoding (8/16/32)?

**Comment by Acenotass** [comment]
i think utf16, for chinese support, but for russian utf8 is enough

**Comment by oldman4U** [comment]
Thank you Acenotass!

Update is done.

**Comment by oldman4U** [comment]
Q: Can I add a Linked Issue to my own PR? Somehow this seems to be deactivated.

THX

**Comment by radek8** [comment]
Write in the description
Resolves #1095

**Comment by oldman4U** [comment]
Thank you radek8

**Comment by traffic-light** [comment]
@bigtreetech  when do you guys merge this? This it's pretty usefull because the readme is outdated

**Comment by oldman4U** [comment]
This is especially strange because they merged only one PR...

**Pull request merged**
