### PR TITLE
Add a preheat menu to the ABL menu - update

### PR DESCRIPTION
**Pull request by radek8**
Performing leveling without preheating is irrelevant.
That's why I'm adding the preheat menu to the ABL menu.
At the end of the ABL menu, preheating is switched off automatically.

IMG_20200925_211041_resized_20200925_091326178

### CODE REVIEW

**Comment by Guilouz** [comment]
@radek8 When I add your PR to master I have this error, without it's ok.

Capture d’écran 2020-09-26 à 02 15 20

**Comment by radek8** [comment]
Did you apply my PR to the last modification of PR1111 by diganta73?

**Comment by radek8** [comment]
[BIGTREE_TFT43_V3.0.26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5286378/BIGTREE_TFT43_V3.0.26.x.zip)

**Comment by Guilouz** [comment]
@radek8 Yes with latest PR #1111 , I just updated the french language file

**Comment by radek8** [comment]
All the checks have passed and I have compiled the TFT 43 display successfully
the problem will be you
I sent you a successful coplication

**Comment by Guilouz** [comment]
@radek8 just retry to download latest master : https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/archive/master.zip

Just made change in ABL.c file, without change anything else and same result : 

Capture d’écran 2020-09-26 à 12 22 45

**Comment by radek8** [comment]
what is written in the problems tab?

**Comment by radek8** [comment]
Delete the contents of the folder
BIGTREETECH-TouchScreenFirmware \ .pio \ build
Compile FW again

**Comment by radek8** [comment]
The problem is in your translation into French

image

**Comment by Guilouz** [comment]
Yes I know my repo is not updated but I have downloaded latest master localy on my desktop and try to compile with your changes and I have this error.

**Comment by radek8** [comment]
Do not zip to the desktop, use GitHub Desktop
https://desktop.github.com/
It's convenient, fast.
In a few seconds, you apply any branch for testing

**Comment by Guilouz** [comment]
With last PR compilation is now OK.

**Comment by radek8** [comment]
@bigtreetech, why don't you merge my PR?
Is there a problem?

**Comment by xhejtman** [comment]
> Performing leveling without preheating is irrelevant.
> That's why I'm adding the preheat menu to the ABL menu.
> At the end of the ABL menu, preheating is switched off automatically.
> 
> IMG_20200925_211041_resized_20200925_091326178

off topic question. Are those nice icons available somewhere? I guess they are not part of public BTT repo.

**Comment by radek8** [comment]
> > Performing leveling without preheating is irrelevant.
> > That's why I'm adding the preheat menu to the ABL menu.
> > At the end of the ABL menu, preheating is switched off automatically.
> 
> off topic question. Are those nice icons available somewhere? I guess they are not part of public BTT repo.

Yes they are available.
oldman4u has them ready to merge in PR #1251
"The Roud Miracle"

**Comment by Acenotass** [comment]
@radek8 
typo right on Freud's "he Roud Miracle" :)
#935

**Comment by oldman4U** [comment]
Bets accepted. Will it take another month for BTT to merge this PR or will they be able to do it in less than a month!?

**Pull request merged**
