### PR TITLE
New pull to replace the old smart filament sensor bug fix. 

### PR DESCRIPTION
**Pull request by looxonline**
### Description

This replaces the previous PR to fix the SFS. It was just easier for me to create a new PR off the current codebase. 

All of the @bigtreetech changes have been integrated but in addition the datatype bugs have also been fixed. There were two bugs:

1.) The filament position was being passed as a unit32 when it should have been a float. If a retraction occurs directly after a G92 E0 then the filament position can go negative and this resulted in the uint32 suddenly jumping to a massive number and then jumping back to a small number. This triggered the SFS algorithm twice which resulted in one of the triggers creating a false pause.

2.) The input to the FIL_SFS_SetAlive function was being declared as uint8 but passed as a bool. It is not passed and declared as the same datatype.

### Benefits

Tested and confirmed that there are no longer smart filament sensor false triggers.

### Related Issues

N/A

### CODE REVIEW

**Comment by oldman4U** [comment]
Hi.

I am not using a filament sensor, but thank you for your contribution.

The checks have failed because there is an unsupported update. Please change the 15 env. related entries from "platform      = ststm32" to "platform      = ststm32**@9.0.0**"

In case there are open tickets related to your fix, please add "resolves #ticketnumber" to the description of this PR.

Again thank you for your help and please check #1170 and #1218 in case you have some time to spare;-)

**Comment by digant73** [comment]
@looxonline In the past I got some wrong filament runout messages (so the print was paused and needed to be resumed). For me it seems that the problem was solved just increrasing the value for "fil_noise_threshold" to 200 (default value in config.ini was 100).
It seems you find and fixed a bug on filament runout feature that should allow me to reduce again "fil_noise_threshold" to 100. I will try to test it and verify if the wrong runout detection is finally fixed

**Comment by looxonline** [comment]
> Hi.
> 
> I am not using a filament sensor, but thank you for your contribution.
> 
> The checks have failed because there is an unsupported update. Please change the 15 env. related entries from "platform = ststm32" to "platform = ststm32@9.0.0"
> 
> In case there are open tickets related to your fix, please add "resolves #ticketnumber" to the description of this PR.
> 
> Again thank you for your help and please check #1170 and #1218 in case you have some time to spare;-)

All of the envs are using the correct platform but I only ever tried to build for the TFT35 V3 E3 which worked. I've now built for a bunch of other envs and it seems as if anything in the 1.X range fails at the linker stage. I'm not familiar with that HW series. Was there less flash available on those CPUs?

**Comment by oldman4U** [comment]
I do not know what exactly finally changed, but my PR also failed and changing the config.ini like described above solved the problem. @kisslorand knows more about it

**Comment by kisslorand** [comment]
FIL_SFS_SetAlive is not recognized in interfaceCmd.c

**Comment by oldman4U** [comment]
@AntoszHUN

Could you check if this solves your problem with the sensor.

**Comment by AntoszHUN** [comment]
> @AntoszHUN
> 
> Could you check if this solves your problem with the sensor.

I'll see you as soon as I have time.

**Comment by looxonline** [comment]
> FIL_SFS_SetAlive is not recognized in interfaceCmd.c

The thing is that it is actually recognized at a compiler level but it breaks at a linker level. Also, it only breaks at linker level for the V1.X hardware environments. All other environments build without any issue. This is why I think that there is some sort of an issue with NVMEM allocation with the earlier hardware revisions when trying to link this particular code. I noticed that the python build script is different for all of the V1 hardware versions which seems to indicate that they may have used an MCU with less flash although I have not read the script in detail in order to confirm this. Nevertheless, if this is the case then it could be possible that there is not enough flash to link the final binary on the V1 hardware and that is where the error is coming from.

**Pull request merged**
