### PR TITLE
automatic build test using GitHub actions

### PR DESCRIPTION
**Pull request by UnknownHero99**
auto build test using GitHub actions after each pull request to prevent compile errors

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Does this work better than [Travis](https://travis-ci.org/)?

**Comment by UnknownHero99** [comment]
to be honest, I have no idea :) but I did it with GitHub Actions because they are already integrated into GitHub and is very easy to use, they simply mark each pull request with red X if unable to compile or with green check mark if it compiles ok

**Comment by UnknownHero99** [comment]
slika

this is an example of pull request getting checked

**Comment by thisiskeithb** [comment]
I’ll have to check it out. I only have experience with Travis testing on GitHub because of [Marlin](https://github.com/MarlinFirmware/Marlin/pulls ) and was curious how well Actions worked.

**Comment by guruathwal** [comment]
This should save a lot of time.

**Pull request merged**
