### PR TITLE
update german translation and add missing icons

### PR DESCRIPTION
**Pull request by rebel1**
### Description

Update german translation and add missing icons for The Round Miracle Menu Material theme

### CODE REVIEW

**Comment by oldman4U** [comment]
@Acenotass Are there icons missing?

@AntoszHUN

Please check

**Comment by AntoszHUN** [comment]
> @Acenotass Are there icons missing?
> 
> @AntoszHUN
> 
> Please check

Thank you for reporting. In the evening I will make the necessary corrections between the icons.

AntoszHUN

**Comment by AntoszHUN** [comment]
> 
> 
> > @Acenotass Are there icons missing?
> > @AntoszHUN
> > Please check
> 
> Thank you for reporting. In the evening I will make the necessary corrections between the icons.
> 
> AntoszHUN

So then you have to do two icons.?

**Comment by kisslorand** [comment]
It would be nice to have an icon for the  "(Un)Load" menu too. A generic icon, something like the Unload or Load icon but without the direction.

**Comment by rebel1** [comment]
> > > @Acenotass Are there icons missing?
> > > @AntoszHUN
> > > Please check
> > 
> > 
> > Thank you for reporting. In the evening I will make the necessary corrections between the icons.
> > AntoszHUN
> 
> So then you have to do two icons.?

Yes, z_align.bmp and mesh_editor.bmp

**Comment by oldman4U** [comment]
@gurmeet

Who makes the icons for the unified menu?

René Bensch <notifications@github.com> schrieb am Sa. 16. Jän. 2021 um
17:47:

**Comment by AntoszHUN** [comment]
> 
> 
> > > > @Acenotass Are there icons missing?
> > > > @AntoszHUN
> > > > Please check
> > > 
> > > 
> > > Thank you for reporting. In the evening I will make the necessary corrections between the icons.
> > > AntoszHUN
> > 
> > 
> > So then you have to do two icons.?
> 
> Yes, z_align.bmp and mesh_editor.bmp

Okay. Thanks.

**Pull request closed without merging**
