### PR TITLE
Add BLTouch Reset option to menu

### LINKED ISSUE #902: [FR] reset BL-touch
At this moment, when I need to reset the BL-touch, I've got to go back to the marlin screen.

It would be great if this is possible in the new bl-touch menu under the bed levelling menu.

(It's a feature what you normally do not need a lot. But would be great if it's possible within the touchmode)

### PR DESCRIPTION
**Pull request by bryan065**
### Description

Add BLTouch reset function and resolves #902

### CODE REVIEW

**Comment by radek8** [comment]
write in the description
resolves #902
this will match the request with your PR :-)

**Comment by traffic-light** [comment]
This is really quick. Thanks a lot. I will try this out right now

**Comment by traffic-light** [comment]
Thank you. It works great.

I used this opportunity to relocate the icons like it is in Marlin:

Line 8 - 12
````
    {{ICON_BLTOUCH_RESET, LABEL_RESET},
        {ICON_BLTOUCH_TEST, LABEL_BLTOUCH_TEST},
        {ICON_BLTOUCH_DEPLOY, LABEL_BLTOUCH_DEPLOY},
        {ICON_BLTOUCH_STOW, LABEL_BLTOUCH_STOW},
        {ICON_BLTOUCH_REPEAT, LABEL_BLTOUCH_REPEAT},
````

Line 28 - 43
````
    case KEY_ICON_0:
      storeCmd("M280 P0 S160\n");
      break;
    case KEY_ICON_1:
      storeCmd("M280 P0 S120\n");
      break;
    case KEY_ICON_2:
      storeCmd("M280 P0 S10\n");
      break;
    case KEY_ICON_3:
      storeCmd("M280 P0 S90\n");
      break;
    case KEY_ICON_4:
      storeCmd("G28\n");
      storeCmd("M48\n");
      break;
````

**Comment by bryan065** [comment]
@radek8 ah, got it! thanks!

@traffic-light I'll update it to match the Marlin order.

**Comment by traffic-light** [comment]
@bigtreetech this update works good. Would be nice if it is possible to pull it

**Pull request merged**
