### PR TITLE
possible bugfix for filament sensor not working connected to TFT

### PR DESCRIPTION
**Pull request by digant73**
This PR is meant ONLY for testing puropose (it will be marked as draft) for all the users having
the filament sensor not properly working when connected to TFT.
I kindly ask all people affected by the problem with the sensor and SFL on TFT to test this PR and provide their results.

In order to use this PR the following setting MUST be enabled on Marlin (Configuration_adv.h):

M114_REALTIME

This PR could fix the following reported bugs:

#1617
#1612
#1611
#1538

**PR STATUS: NOT TO BE MERGED**

### CODE REVIEW

**Comment by oldman4U** [comment]
It has been working perfectly when printing from TFT storage for me. Do you
expect improvements there and also when printing from on board sd card?

Will test in about 12 hours.

Thank you

digant73 ***@***.***> schrieb am Sa. 20. März 2021 um 22:33:

**Comment by digant73** [comment]
@oldman4U 

I expect that from TFT it will continue to perfectly work for you and also for the users affected by the reported bugs.
Which are the problems from onboard?

**Comment by oldman4U** [comment]
👍🏻

Onboard I see it interrupting the print perfectly every time with the
correct Filament runout information on screen. The problem is that it
resumes print correctly sometimes but most of the time it shows Filament
runout again one or two times before print finally resumes correctly. I
have been testing this around 100x and could not find a pattern. Printing
from TFT storage I have been testing around 30x and it never failed and
always resumed the print correctly. Retract (and purge at Pause position)
has been working 100% independent of the storage I used.

Maybe I will upload some movies tomorrow.

Thank you

digant73 ***@***.***> schrieb am Sa. 20. März 2021 um 22:43:

**Comment by digant73** [comment]
could you provide the output from pronterface when you have the problems from onboard?
I will test it also from my side

**Comment by oldman4U** [comment]
ESP32 via WIFI should also do the job. Right!?

digant73 ***@***.***> schrieb am Sa. 20. März 2021 um 23:00:

**Comment by digant73** [comment]
Everything you can use to monitor the comunication with marlin is good

**Comment by oldman4U** [comment]
Ready for a test and Marlin is already updated with M114 RealTime enabled.

Anything I have to keep in mind regarding the TFT firmware besides activating Filament sensor?

**Comment by digant73** [comment]
@oldman4U nothing in particular. just verify if it works. From onboard it will be usefull to get the output to/from mainboard, so I could understand the cause for the multiple resume retries

**Comment by Chris1231** [comment]
I just loaded the last TFT firmware.
M114 REALTIME is enabled in Marlin. but unfortunately it still doesn't work. I still get the message no filament.

Sensor connected to TFT
Last Marlin version
Last TFT version

Is there anything else I have to consider?

otherwise I would first switch back to TFT firmware 25.3 :(

**Comment by digant73** [comment]
@Chris1231 stupid question, as "last TFT fw", do you mean this PR not the current BTT main branch, right?

**Comment by Chris1231** [comment]
my mistake,
the last current BTT main branch.

I'll try the PR right away.

**Comment by oldman4U** [comment]
OK, let's use this ticket for any further tests.

I will upload a movie in a few minutes which shows TFT35 E3 v3 with digant73's PR (even it does not matter because it works the same wit BTT FW) and a sensor connected to TFT printing from TFT. Just want to finish another test, which is not really related.

**Comment by oldman4U** [comment]
https://user-images.githubusercontent.com/54359396/111909060-0591d600-8a5c-11eb-86bd-8584a36891c4.mov


https://user-images.githubusercontent.com/54359396/111909083-1e01f080-8a5c-11eb-8bc3-22eb68f32ccb.mov


https://user-images.githubusercontent.com/54359396/111909094-2fe39380-8a5c-11eb-882b-45ecf6bab363.mov


https://user-images.githubusercontent.com/54359396/111909126-4558bd80-8a5c-11eb-8761-ecf9ecfa2941.mov

**Comment by Chris1231** [comment]
I have the PR firmware on the printer. Unfortunately without success.

i use the old z-endstop, could that be the problem?

**Comment by oldman4U** [comment]
What do you mean with old z endstop?

Have you seen the movies which I uploaded?


Chris1231 ***@***.***> schrieb am So. 21. März 2021 um 16:26:

**Comment by Chris1231** [comment]
@oldman4U yes have seen the movies, so I ask if the z-endstop from the ender 3 is no longer compatible with the tft firmware.

**Comment by oldman4U** [comment]
I do not understand what you mean. Sorry.

How is the endstop related to filament runout? My filament sensor works
technically like an endstop or vice versa.  Both define a status to be on
or off.

Chris1231 ***@***.***> schrieb am So. 21. März 2021 um 16:45:

**Comment by Chris1231** [comment]
that you don't understand me is more a result of my english.

but you have now clarified the question.
but why does it work for you, but not for me?

**Comment by GrahamJB** [comment]
Do you mean you are reusing the microswitch from a limit switch as the microswitch in a runout sensor?

**Comment by Chris1231** [comment]
@GrahamJB yes

**Comment by oldman4U** [comment]
In which order are the 3 wires connected to your TFT?

**Comment by Chris1231** [comment]
it's only 2, 3.5V and sig. when triggered, the 3.5v are switched to PA15.

**Comment by digant73** [comment]
@Chris1231 Did you configure filament runout sensor to SMART or only ON?

**Comment by Chris1231** [comment]
Only ON

**Comment by digant73** [comment]
Extruder position is used for SFS not for ON/OFF sensors.

The polling is made based on your current tool:

if tool 0 -> FIL_RUNOUT_PIN is used
if tool 1 -> FIL_RUNOUT_PIN_1 is used
....

If you have a BTT TFT35 V3, by default the following pins are used:

FIL_RUNOUT_PIN PA15

The following pins are by default disabled, so if use one of that you must uncomment the the proper line

// #define FIL_RUNOUT_PIN_1 PC12  //Extruder T1  Attention: Is the same pin as PS_ON.
// #define FIL_RUNOUT_PIN_2 PB10  //Extruder T2             Is the same pin as USART3 TX.
// #define FIL_RUNOUT_PIN_3 PB11  //Extruder T3             Is the same pin as USART3 RX.
// #define FIL_RUNOUT_PIN_4 PA0   //Extruder T4             Is the same pin as USART4 TX.
// #define FIL_RUNOUT_PIN_5 PA1   //Extruder T5             Is the same pin as USART4 RX.

Furthermore, "runout_noise_ms" and "fil_runout_inverting" are used.

Try setting "runout_noise_ms" to 1000 (1 second).
Try setting "fil_runout_inverting" to true/false

If you connected the sensor to the correct pin, it must work

**Comment by Chris1231** [comment]
short question, if I measure to GND with the PA15 multimeter, 3.5V are present, could that be the problem for me?

**Comment by Chris1231** [comment]
i think i have the solution to my problem.

I changed the wiring.
instead of switching 3.3V to PA15,
I switch PA15 to GND.

after a short test, it seems to work

**Comment by digant73** [comment]
@Chris1231 you should obtain a working runout changing the value for "fil_runout_inverting"

**Comment by Chris1231** [comment]
@digant73 I had already tried that before, without success.

**Comment by digant73** [comment]
@Chris1231 Ok. A usefull info for other similar problem as your

**Comment by oldman4U** [comment]
Using only two wires you have to use gnd and signal but i am wondering how this makes a difference in firmware!?

But it works now with the "latest" firmware!?

**Comment by Chris1231** [comment]
i am using the PR from digant73 and it works now.

**Comment by oldman4U** [comment]
So it will also work with the current master firmware.

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please close your ticket not this PR😆

**Comment by digant73** [comment]
@Chris1231 please, in you bug report put and update on you first post (where you initially described your problem) and explain where the problem was and how you fixed it. It will help other users having the same problem to quickly solve the problem without openung a new bug report. Thanks

**Comment by Chris1231** [comment]
thanks for your help, i closed my ticket and updated the first post.

**Comment by oldman4U** [comment]
Should we expand the verified bugs and add known issues to it and mention la and that it does not work with smart filament sensor?

**Comment by digant73** [comment]
I would say yes

**Comment by oldman4U** [comment]
👍🏻

**Comment by digant73** [comment]
closing the PR due to no other users having any problem with SFS not working when connected to TFT

**Pull request closed without merging**
