### PR TITLE
Add comments for filament sensor connected to the mainboard.

### PR DESCRIPTION
**Pull request by Ari-SSO**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

Add description to avoid configurations problems when someone has a filament runout sensor connected to the main board instead of the TFT board.

### Benefits

Help people to configures the filament sensor correctly.

### Related Issues

#2004

### CODE REVIEW

**Comment by digant73** [comment]
@Ari-SSO you applied the comments on top of an old build. You should apply the changes on top of the current BTT main branch

**Comment by radek8** [comment]
image

**Comment by Ari-SSO** [comment]
Just that I had asked before ... Well, I already added it to the master. Hopefully it's okay.

**Comment by oldman4U** [comment]
A few weeks ago I had a PR with probably 20 updates before I deleted it and made it new. And it was just the updated readme...🤪

**Pull request closed without merging**
