### PR TITLE
Update extruder tuning & Add jerk to parameter settings.

### LINKED ISSUE #1034: Firmware Funktion einfügen möglich?
Funktion Jerks einfügen ist das möglich?
Wie, Wo ist nötig.

### PR DESCRIPTION
**Pull request by traffic-light**
# Update extruder tuning

## _Changed_ 
The icons in the extruder tuning menu (and tuning menu) are now more appropriate to what they do.

I also changed the name of the extrude_100 to tune_extruder.
 _(I didn't change the icon itself. Only renamed it. See my idea: )_

## _New icon/ new design of current icon (tune_extruder.bmp)_
My idea is to change the current icon to something like this:
tune_extruder

But, as you can see, it's just a horrible version to indicate my idea for the new icon.
Can someone make a correctly and nicer icon with, maybe,  a better look/ style.
If you want, you can adjust my pull request OR create you're own PR
Thanks in advance. 
(@guruathwal , not long ago you did change the icons for the LCD. Could you take a look at this, if you want)

**TO BE CLEAR:** I'm **not** asking for a NEW icon. It's  a **replacement**! Just a icon that describes it better that it's for tuning the extruder!

####  So, in short  ####
Change this one:extrude_100
```
 C                |
 H                |         I
 A                |        N
 N                |        T
 G                |        O
 E            .  \ /
```

Into this one: tune_extruder

But with better graphics and for every TFT size ;-)

# Add jerk to parameters settings

## _What's changed_ 
I've added the jerk settings to the parameter settings
(also some aligning in the code for a better readability)

maybe I'll add the other settings in M205 in another menu in a new PR. But for now this is good enough.

This resolves #1034 

## _Further thoughts_ 
Maybe it's  a good idea to filter menu's in the parameters settings.
When not using the linear advanced? Don't show it. When not using Jerk? Don't show it

There are a lot of options not everyone is using. For example: I don't have a second nozzle. But it's still in that menu.
(I know. This is be a little harder because the way it's implemented right now. But maybe for in the future.)

# Corrected misspelled word
According to ticket #1042 I updated configuration.h

# TO DO 

Things I can't do:

- [x] Change the current extrude_100 (Wich I renamed) icon, see [update extruder tuning](#update-extruder-tuning), for tune_extruder.bmp (will be done by guruathwal)

### CODE REVIEW

**Review by traffic-light — COMMENTED** [review]
Remove extrude_100

**Comment by traffic-light** [comment]
Whoops. This can be seen as unneeded :-p

**Comment by traffic-light** [comment]
Please read **TO DO**  in the main-text ;-)

**Comment by traffic-light** [comment]
Is there someone who can create the new icon for me?
See the maintext for more information.

Maybe create a new pull with your new icons ;-)

**Comment by NicoletoAerials** [comment]
The flash space for storing icons is almost full at 94% therefore it is not advisable to include new icons unless strictly necessary. See #1013

**Comment by traffic-light** [comment]
> The flash space for storing icons is almost full at 94% therefore it is not advisable to include new icons unless strictly necessary. See #1013

It's not a new icon ;-)
Maybe you should read my maintext

**Comment by traffic-light** [comment]
(@guruathwal , not long ago you did changed the icons for the LCD. Could you take a look my suggestion, if you want)

**Comment by guruathwal** [comment]
@traffic-light I will update the icon along with some other icons.

**Comment by traffic-light** [comment]
@guruathwal thank you! You're the best ;-)

Then I'll remove it from the to do list ;-)
(I think that you already knew it but I renamed the icon to a more logical name ;-) )

@bigtreetech : this pr is ready for merge!

**Pull request merged**
