### PR TITLE
cleanup & remove duplicate code, reduce global variables & reduce code size.

### PR DESCRIPTION
**Pull request by guruathwal**
- Move const values out of functions to reduce program size
- Cleanup & remove duplicate codes
- Reduce global variables.
- Replace UNIFIED_MENU option with STATUS_SCREEN option.
- Remove obsolete/ unused code.
- Fix const declarations.

### CODE REVIEW

**Comment by digant73** [comment]
I see you made some variables global instead of local but const initializers are always maintained on psp. It seams to me not an optimization. Am I wrong?
I know anyone has a preferred programming style, but compressing the code removing blank lines goes not in the direction of the recent style guide. E.g. All the new lines I normally put in my code are to clearly separate varaible definition, initialization, external function invocation, gcode functions invocations, GUI function invocations etc... Unless of wrong indentation, tabs etc... if you could avoid to change the syntax followed by the author is preferrable, at least for the code written by me. Not an offense of course, your contribution is always welcome, but consider that, for me at least, is quite boring that someone changes someting that is properly wriitten and (personally) more readable. As you see I normally limit my changes, on code not written by me, to wrong indentaion and presence of tabs avoiding to drastically adapt the code to my style guide.
Also I didn't yet understand what is the style guide you use. E.g. for "switch" statement. sometimes the "case" statement is at same indentation of {, sometimes it is indented (as I suppose it should be) and it makes to me more hard to integrate something in your code trying to respect the style followed in the code.

**Comment by oldman4U** [comment]
Maybe it would be best to have a kind of guideline fro this repository. @traffic-light already started with it and I would recommend and ask guruathwal to make such a document, because he is the one who contributed most of the code.

@guruathwal I know you are very busy at the moment, but would you please be so kind and define such a document? This could be very useful and maybe would also help to reduce the amount of issues in the future.

Thank you

**Comment by traffic-light** [comment]
@oldman4U yes. I started on it.

For everyone (@digant73 @guruathwal ) who's having ideas:
Feel free to comment on my issue https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1253

**Comment by guruathwal** [comment]
@digant73  If you declared a const inside of a function, every time that function is called, it would allocate a new place in RAM for that const and eat up CPU cycles during the process. This defeats the point of a const. 
Code optimization itself means changing code to reducing RAM and memory usage.
It is good to add blank lines to distinguish between code but not when it results in blank line after every line of code. Instead it will be better to change line spacing in editor itself.

@oldman4U I have started as per your suggestion. Should be completed in about 2 - 3 days.

**Comment by digant73** [comment]
@guruathwal 
Well, in the best case, the compiler normally optimize the "const" avoiding to allocate memory and accessing directly the const data from the psp area. In that scenario, for both global and local variables, no memory allocation shold be performed but moving a const from local to global simply changes the visibility scope (it is increased when not necessary).
In the worst case, the compiler will also allocate memory for both global and local variables (psp is still there for both) but the global will permantly remain while the local will be released (it's on the stack) when exiting from the function. In this scenario, I see an increase of mem usage by the presence of global variable and (as for the first scenario) a change on the visibility scope.

For the code, I already explained my style. I don't put any random empty line here and there. For that aspect, anyone has his idea  and I normally don't change it on my review.

In the Mesh Editor menu, you moved some data structues on the .h file. I normally always avoid to provide structures in the .h when not necessary as in that case (all of that structures does not need to be normally tuned by user). The info that can be tuned were reported in the Configuration.h file.

**Comment by traffic-light** [comment]
> @digant73 If you declared a const inside of a function, every time that function is called, it would allocate a new place in RAM for that const and eat up CPU cycles during the process. This defeats the point of a const.
> Code optimization itself means changing code to reducing RAM and memory usage.
> It is good to add blank lines to distinguish between code but not when it results in blank line after every line of code. Instead it will be better to change line spacing in editor itself.
> 
> @oldman4U I have started as per your suggestion. Should be completed in about 2 - 3 days.

So, you're making a style guide too?

**Comment by guruathwal** [comment]
@traffic-light  I am writing coding standard which would cover all aspects of this repository.

**Pull request merged**
