### PR TITLE
Feature Request - UBL

### PR DESCRIPTION
**Pull request by ETE-Design**

### CODE REVIEW

**Comment by guruathwal** [comment]
@ETE-Design This PR has some files changes and commits that look very similar to PR #329 by @darkspr1te like adding support for MKS displays.
can you check and confirm to avoid confusion as it might end up with too many duplicate files and merge issues.

**Comment by darkspr1te** [comment]
The works by @delwinbest is similar to my PR #329 as they are collaborated patches/works , as mine is not building(remotely only, local build works fine) , I dont think this feature is related to UBL but to adding of a new variant,

**Comment by guruathwal** [comment]
@darkspr1te  I tried to compile you PR on my PC but it failed for TFT35 V3

**Comment by ETE-Design** [comment]
@delwinbest Have just tryed your firmware on an MKS TFT28, work great, exept offset / babystep in the level menu seems not to work... Should be enough to do this in Marlin 2.0 right:
#define BABYSTEPPING
#define BABYSTEP_ZPROBE_OFFSET
//#define MIN_SOFTWARE_ENDSTOP_Z

**Comment by Scope666** [comment]
Can't use anything newer than 2.0.3 Stable ... Bugfix and 2.0.4 are broken:

https://github.com/MarlinFirmware/Marlin/issues/16889

**Pull request closed without merging**
