### PR TITLE
Add parsing of fan speed, Improve popup dialog window, Add large fonts, Improve Numpad UI & other bug fixes

### LINKED ISSUE #267: F0 shows 0 on Unified 3.0.25 TFT35 even it is set to other values via GCODE
My TFT35 shows F0 as 0 on Info-Screen when I print via USB, even the Filament Cooling Fan is running. Other Values, like Hotbed and Hotend temperature are displayed correctly.

Printer: Creality Ender 3 Pro with SKR Mini E3 1.2

### LINKED ISSUE #659: [BUG] Layer and Fan stats not updating
I have an issue with my BTT TFT35 v1.2. During printing the purple layer stats and blue fan stats aren’t updating during print.

Is this a known issue?

### LINKED ISSUE #674: [BUG] Fan controls are not working
Fan control menu (Menu - Heat/Fan - Fan) is useless - none of the buttons there (apart from "Back" button) do anything. Moreover, current fan speed is not updated when fan is controlled by gcode commands - it's always 0.

### LINKED ISSUE #692: [BUG] In certain case the file name from the printer's SD card is shown as ???
### Description

File named M8x195.gcode is read as ??? on the file listing in touch mode, when the SD card is in the printer slot.

In the Marlin mode the file name is displayed ok.
If the file is placed on the TFT card, the name is displayed ok.
Selecting the "???" file to print starts printing the file, showing the real file name in the upper line of the display.

### Steps to reproduce

1. Name the file on SD card M8x195.gcode
2. Put the SD card in the printer slot
3. Go to touch mode, select print, from printer SD - you should see ??? in the file list

**Expected behavior**

Proper file name should be displayed.

**Actual behavior**

??? is displayed

### Hardware Variant

TFT35 E3 v3.0

### TFT Firmware Version & Main Board Firmware details

Marlin 2.0.5.3
TFT 26.1.1, non-modified version

### Additional Information
The file was created in Windows, it has mixed case letters in the name and 6 characters. I suppose that any file name with that properties may have the same problem.

### LINKED ISSUE #761: Why are the steps on the screen and not the distance?
Why are the steps on the screen and not the distance? Explain clearly. Why isn't the fan showing?
WP_20200526_11_04_11_Pro

### PR DESCRIPTION
**Pull request by guruathwal**
- ~Integrate preheat menu with heat menu.~
- Improve Live icons.
- Improve Numpad UI.
- Use Numpad to set temperature instead of increase decrease button. (Click on heat status icons to edit temperatures.)
- Fix 'T0' temperature updating to the current tool/nozzle.
- Fix bugs in baby-stepping and probe offset menu.
- Improve popup dialog window (display window according to message type).
- Fix unnecessary item re-draw in the feature settings menu.
- Add printf/sprintf library from https://github.com/mpaland/printf
- Add parsing of fan speed. (#674, #659, #267). Requires updating Marlin firmware to newer than May 26, 2020 (https://github.com/MarlinFirmware/Marlin/pull/18013)
- Add parameter save & reset option in parameter settings.
- Change some global variables to local variables to reduced global RAM usage.
- Fix Typos and other cleanups.
- Fix onboard SD filename displayed as `????` (#692)
- Add firmware retract, recover and linear advance settings in the parameter settings menu.
- Fix axis position display with smoothieware (#761)
- Add Large ASCII fonts for displaying values
- Add small icons for small buttons.
- Separate core functions from menu functions.
- ignore line number from gcode received from OctoPrint.
- Fix Global info display

Resolves #674, resolves #659, resolves #267, resolves #761, resolves #692

### CODE REVIEW

**Comment by radek8** [comment]
cannot be compiled
image

**Comment by radek8** [comment]
Menu parametersetting it does not work correctly

**Comment by guruathwal** [comment]
@radek8  can you provide more details about your issue?

**Comment by radek8** [comment]
1. It is not possible to click on individual items in the Parameter menu
2. the M117 popup window cannot be confirmed.


[M117.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4707237/M117.zip)
[Parameter.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4707238/Parameter.zip)

**Comment by radek8** [comment]
3. In the "heat" menu, the "Both" option cannot be selected for the upper left icon
IMG_20200531_100955

**Comment by radek8** [comment]
4. The printer does not print, it only reads the percentages quickly.

[Print.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4707542/Print.zip)

**Comment by radek8** [comment]
Wouldn't the new Preheat icon be better the other way around?


image

**Comment by guruathwal** [comment]
@radek8  the parameter and m117 issues are fixed now.

> 1. In the "heat" menu, the "Both" option cannot be selected for the upper left icon

That icon is for selecting the current heater i.e. toggle between [BED, T0, T1, T2, ...] for the stop button and for applying preheat temperatures. preheat is applied to the current Nozzle number and bed displayed on the screen. Earlier that icon was placed in the bottom-left corner, now it is in the top-left icon.

**Comment by radek8** [comment]
@guruathwal 
Switching between  [BED, T0, T1, T2, ...] - OK  I didn't realize that.

Menu Parameter fixed. Thank you.

The problem with the M117 persists

An error occurs during compilation :

TFT\src\User\Menu\Popup.c: In function 'popupReminder':
TFT\src\User\Menu\Popup.c:108:21: warning: comparison of distinct pointer types lacks a cast
   if (infoMenu.menu != menuDialog)
                     ^~
TFT\src\User\Menu\Popup.c: In function 'showDialog':
TFT\src\User\Menu\Popup.c:137:21: warning: comparison of distinct pointer types lacks a cast
   if (infoMenu.menu != menuDialog)

**Comment by guruathwal** [comment]
Oops my bad. now check...

**Comment by radek8** [comment]
Great. Fixed issue with M117.

I also found a problem with the terminal window.
You cannot turn off the display of the ACK in the terminal window.

**Comment by radek8** [comment]
Another problem with the popup window.
After editing the printer parameters in the Parameter menu, there is a query to save to eeprom. Cannot be confirmed

**Comment by radek8** [comment]
The BabyStep menu is excellent. :-)
I'm just missing the save button that someone removed in the past.

**Comment by radek8** [comment]
Thank you. Parametersetting works as it should

**Comment by radek8** [comment]
There is still a problem in the Parametersetting menu.
I have 2 extruders.
If I change the value of E2 (current or step / mm), the value of E and E2 will be overwritten.
After reloading the values, E is changed. E2 is unchanged

**Comment by radek8** [comment]
There is an error in line 6 in file Parametersetting.c

image

**Comment by Uz45** [comment]
MKS TFT32 V4.0 - MKS_32_V1_4 variant 

The screen freezes after booting the main screen if baudrate is not correctly specified in config.ini. The screen bootin normally if the baudrate value is correct. But it freezes when you enter the Heat menu. The rendering menu is normal but does not respond to clicks.

**Comment by radek8** [comment]
@guruathwal is still a problem with the popup window after auto-leveling (ABL icon).
Unable to confirm, reset required.

**Comment by radek8** [comment]
The second problem is auto-leveling.
The save to eeprom query does not pop up after leveling is completed, but after pressing the back button. However, if I press the back button before the leveling is completed, there is nothing to save or the damaged data will be saved.

**Comment by bigtreetech** [comment]
Hello, I don't think it's appropriate to delete the "+“, "- "button in the "Heat Menu", because it's inconvenient to manually input the "fine-tuning" temperature every time during the printing process, so I think the best way is to keep "+" ”-“ in the "Heat Menu" and add the input(numpad)  function.

and putting "Heat Menu" and "Preheat Menu" together can also confuse the user, so I suggest that there should still be two menus. It's a good idea to display the temperature on the preheat icon, so that all the "preheat button" can share a same icon.

I still prefer the previous dialog box. I think adding font&background color changes to different scenes on the basis of the  previous dialog box can achieve the same effect, and it is more beautiful.

About the interface display effect, these need to be discussed. Because there are a thousand Hamlets in a thousand people's eyes.

Anyway, Thank you again for your hard work to this project !

**Comment by guruathwal** [comment]
> Hello, I don't think it's appropriate to delete the "+“, "- "button in the "Heat Menu", because it's inconvenient to manually input the "fine-tuning" temperature every time during the printing process, so I think the best way is to keep "+" ”-“ in the "Heat Menu" and add the input(numpad) function. 
>
> and putting "Heat Menu" and "Preheat Menu" together can also confuse the user, so I suggest that there should still be two menus. It's a good idea to display the temperature on the preheat icon, so that all the "preheat button" can share a same icon.

I added the Numpad to changing temperature for users with devices without a rotary encoder. It is really a headache when trying to set temperature different from preheats with +- and just 3 variables[1, 5, 10].  This is also the case for the Move menu when trying to move an axis to a location like 137.50.

Changing temperature while printing can be solved by changing the layout of the menu while printing or by adding a 3 / 4 button menu layout. this can also be useful for other features also like baby-stepping or changing speed/flow rate while printing.

> 
> I still prefer the previous dialog box. I think adding font&background color changes to different scenes on the basis of the previous dialog box can achieve the same effect, and it is more beautiful.
> 
>About the interface display effect, these need to be discussed. Because there are a thousand Hamlets in a thousand people's eyes.

I found some areas on the display were drawn multiple times in the message box. I tried to make the layout simple and more informative following the current design trend. It will always be your decision to include it, I can only provide the option. I am always open to discussions.

**Comment by radek8** [comment]
@guruathwal
if I insert an onboard SD card in a format that is not supported,
a popup window will appear, but cannot be confirmed.

error

**Comment by Tygrys-1** [comment]
I agree with all changes but not heat menu integration. I think it requires some discussion before. Current heat menu system is clear, and there is a place to add more materials, like eg. TPU.
Live icons are fine up to 3 choices, with more they are annoying.

**Comment by rightawy** [comment]
I really like the new Message box. The previous one looked ugly.
The new heat menu is also good, This is what touch screens are for👍. At least I can set a temperature different from the preheat options without having to solve the formula and playing the plus-minus game. [ 237 = 10 * 23 + 5 * 1 + 1 * 2], Although improvements can be made like changing the 8 icon layout which was earlier used for every occasion (list view is a real lifesaver). 
Preheat as a separate menu is overkill. It should be kept as an option in heat menu. It lets you confirm what temperature has been set on the same menu and see which hotend the preheat is being applied to. The same goes for the baby-stepping menu and the probe offset menu. They both can be integrated like the speed and flow percentage menu.
I agree 3 preheats are enough but still, 4 preheats are easier to use. Try changing font and background colour in screen settings or screen brightness level in feature settings, turning off the knob LED, or even accidentally touching the language button. You have to literally count the clicks to get back to English, and that is also difficult with a new language being added in every release.
Almost 25% of the firmware is filled with the languages only. a total of 15 till now, of which the users use only one unless they want to learn new languages😉. Marlin firmware does a better job by compiling with only the language selected.

**Comment by guruathwal** [comment]
@digant73 Thank you for checking 👍. 
I avoid committing whitespace-only changes in the code as they make it harder to track changes when trying to debug the code. I will add those changes after this PR is finalised.

**Comment by radek8** [comment]
@guruathwal
There is still a problem with the pop-up - Error that cannot be confirmed

**Comment by radek8** [comment]
Another error. 
After 3 clicks on the PREHEAT icon, fragments will appear on the screen

IMG_20200606_224402

**Comment by radek8** [comment]
@guruathwal
Another error. Strange behavior when changing the print speed.
100% + 5% = 999% Back button -> 10%
10% + Normal button = 100% Back button -> 10%
see video
[speed.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4741017/speed.zip)

**Comment by guruathwal** [comment]
> Another error.
> After 3 clicks on the PREHEAT icon, fragments will appear on the screen
> 
> IMG_20200606_224402

@radek8 Re-flash the config.ini from this PR.

**Comment by radek8** [comment]
The speed menu still does not work even after a fix

**Comment by radek8** [comment]
> > Another error.
> > After 3 clicks on the PREHEAT icon, fragments will appear on the screen

> 
> @radek8 Re-flash the config.ini from this PR.

Thank you. solved by the config.ini file

**Comment by GregSKR** [comment]
I love the new menus, thanks!
Some bugs I can see:
**Temp menu** display problem with the numpad
IMG_20200608_201833

**Speed menu**
- the '+' button gives an error
IMG_20200608_201944
- when entering speed menu, switching to flow and going back, if you enter once again the speed menu it displays 'Speed' but show the flow value (and you really change the flow value). You have to click on 'Speed' to switch from 'false speed' to real 'speed'
- changing the flow value ok the first time but after going back en entering once again the menu you can't change it anymore

**Comment by digant73** [comment]
In the Fan menu if you set a value and then press on the stop button it seems the gcode is not executed althought the value in the menu is correctly reset

In the Extrude menu I will swap icon 5 and 6 so the menu is similar to other were units are before the speed button

**Comment by GregSKR** [comment]
Thanks for the bugfixes!

Looks like it's all fine, except for the third bug I listed ("when entering speed menu...).

I made a temporary fix in Speed.c, by changing line 71

from
```
percentageItems.items[KEY_ICON_5] = itemPercentUnit[item_percent_unit_i];
```

to
```
percentageItems.items[KEY_ICON_4] = itemPercentage[item_percentage_i];
percentageItems.items[KEY_ICON_5] = itemPercentUnit[item_percent_unit_i];
percentageItems.title.index = itemPercentageTitle[item_percentage_i];
menuDrawTitle(textSelect(percentageItems.title.index));
```


and it look OK, but you will certainely have a better solution...

**Comment by radek8** [comment]
Hi #guruathwal
You marked PR as a draft
Can you please move all bugs to a separate PR so they can merge before you complete this project?
Thank you

**Comment by Tygrys-1** [comment]
Just a thought:
I think of adding a decimal point and a + and - buttons for the numeric keypad, there is a place for them. The DP might be handy in ie.  move menu, and +/- might do their usual work of increasing-decreasing value to set.

**Comment by digant73** [comment]
*) MainPage.c: In the ClassicMenu function you forgot to restore the icon LABEL_PREHEAT. You are still using LABEL_HEAT
*) language_gr.c: one item has a different position compared to all the other language files

**Comment by digant73** [comment]
Just a small improvement. When selecting a file to be printed it should be better a dialog box asking to proceed printing the selected file is shown. Just to avoid to start printing a wrong selected file

**Comment by Tygrys-1** [comment]
> 
> 
> Just a small improvement. When selecting a file to be printed it should be better that a dialog box asking to proceed printing the selected file is shown. Just to avoid to start printing a wrong selected file

I'm thinking of some kind of preview screen, with the file name, size, preview picture if available, and perhaps some information from the file like filament used or estimated print time. Slicers usually provide such info in comments and for popular ones this can be parsed and displayed.

**Comment by digant73** [comment]
> > Just a small improvement. When selecting a file to be printed it should be better that a dialog box asking to proceed printing the selected file is shown. Just to avoid to start printing a wrong selected file
> 
> I'm thinking of some kind of preview screen, with the file name, size, preview picture if available, and perhaps some information from the file like filament used or estimated print time. Slicers usually provide such info in comments and for popular ones this can be parsed and displayed.

that should be good but more difficult to implement.
The most frequent requests that I see about improvements in the current firmware are:
1) M600 support (a lot of people ask for this). I saw that a PR to support M601 was just integrated in the official BTT release but I didn't understand if any support to M601 is provided in that fw. Why a PR for M601 instead of M600?
2) changing Zoffset from Probe menu should allow to move also the nozzle. I see there is already a PR for that since many time. Probably it should be enough to integrate it in the new Probe menu that Guruathwal already made
3) Printing confirmation. That is the most easy feature to provide

**Comment by guruathwal** [comment]
@digant73 
> 2. In the speed menu only the icon 5 and 6 are swapped compared to all the other menus with the same icons.  It should be better the are aligned to all the other menus (so first the % icon and then the speed icon)

In all menus inc/dec steps are on the left [Icon 5] and speed/reset/stop is on the right [Icon 6].

**Comment by GregSKR** [comment]
@guruathwal : thanks for your work. 👍 
Just a small problem in preheat menu:
-enter preheat menu
-switch from 'Both' to 'Bed'
-go back
-enter again preheat menu... 'Both' is showned but it should be 'Bed' like previously. If you run a preheat at this stage, only bed will preheat, not both... so the 'switch' button needs to be updated when entering preheat menu 😉

**Comment by digant73** [comment]
@guruathwal 
1) sorry my mistake. it was the extruder menu not the speed menu. Now I see you swapped the two icons in the extruder menu
2) I confirm the problem reported by GregSKR in the preheat menu
3) in laguage_cn.c remove two spaces to align the string value
4) I see you integrated the Configuration.h providing support for M601 (it was provided in another PR) but I don't see any handling on the rest of the project. I had a look to the current main BTT release and there I see that in interfaceCmd.c there is M601 handling. That file is also far different than your. I don't know if you usually integrate the main BTT code in your PR so it is already aligned with it

**Comment by guruathwal** [comment]
@digant73 thanks for the update.
>I see you integrated the Configuration.h providing support for M601 (it was provided in another PR) but I don't see any handling on the rest of the project. I had a look to the current main BTT release and there I see that in interfaceCmd.c there is M601 handling. That file is also far different than your. I don't know if you usually integrate the main BTT code in your PR so it is already aligned with it

M601 is compatible only with Prusa Firmware. I think I missed it during merging commits from upstream branch. I will add it. 
The original interfaceCmd.c had 2 set of exactly same code lines for gcodes received from a device like wifi module and gcode sent from TFT itself, due to this it was difficult to implement new gcode. one line needs to add twice. I tried to remove these duplicate lines.

**Comment by digant73** [comment]
> @digant73 thanks for the update.
> 
> > I see you integrated the Configuration.h providing support for M601 (it was provided in another PR) but I don't see any handling on the rest of the project. I had a look to the current main BTT release and there I see that in interfaceCmd.c there is M601 handling. That file is also far different than your. I don't know if you usually integrate the main BTT code in your PR so it is already aligned with it
> 
> M601 is compatible only with Prusa Firmware. I think I missed it during merging commits from upstream branch. I will add it.
> The original interfaceCmd.c had 2 set of exactly same code lines for gcodes received from a device like wifi module and gcode sent from TFT itself, due to this it was difficult to implement new gcode. one line needs to add twice. I tried to remove these duplicate lines.

yes I saw the original interfaceCmd.c has that duplication and you simplified that and probably missed the addition of M601 from the main branch.
But do you think M600 handling could be provided in the future? I don't know how it must be handled but it seems to me similar to pausing a print

**Comment by GregSKR** [comment]
@digant73 wrote
> 1. pressing on preheat icon the system stucks

Yes, had an error in Predheat.c when building the firmware, line 91
Juste change it from
`preheatItems.items[key_num] = itemToolPreheat[nowHeater];`
to
`preheatItems.items[KEY_ICON_5] = itemToolPreheat[nowHeater];`
and you're ok...

**Comment by GregSKR** [comment]
Just saw a few things...

- Bad copy/paste in \User\API\interfaceCmd.c line 672:

`if(cmd_seen('E')) setParameter(P_CURRENT,E2_STEPPER,cmd_value());`
`setDualStepperStatus(Z_STEPPER,true);`
should be "E" and not "Z" stepper!
`setDualStepperStatus(E_STEPPER,true);`

- Some double ";;" in \User\API\parseACK.c

lines 326-328:
`if(ack_seen("X")) setDualStepperStatus(X_STEPPER, true);;`
`if(ack_seen("Y")) setDualStepperStatus(Y_STEPPER, true);;`
`if(ack_seen("Z")) setDualStepperStatus(Z_STEPPER, true);;`

line 335:
`setDualStepperStatus(E_STEPPER, true);;`

**Comment by GregSKR** [comment]
Thanks for the fix.

Some suggestions about the logic used in Fanc.c that will increase 1 by 1 but decrease 2 by 2:

- This formula will decrease 1 by 1:

```
if (fanSpeed[curIndex] > 0)
{
  if (infoSettings.fan_percentage ==  1)
  {
   if (fanGetSpeedPercent(curIndex)%20 != 0)
   {
    fanSetSpeedPercent(curIndex, (fanGetSpeedPercent(curIndex)));  //rounding current speed % reduces speed % by 1.
   }
   else
   {
    fanSetSpeedPercent(curIndex, (fanGetSpeedPercent(curIndex) - 1));  //except for multiples of 20 that needs subtracting 1.
   }
  }
  else
  {
   fanSpeed[curIndex]--;
  }
}
```

- and about the logic of conversion here:

```
void fanSetSpeedPercent(u8 i, int16_t percent)
{
  percent = limitValue(0, percent, 100);
  fanSpeed[i] = (percent * infoSettings.fan_max[i]) / 100;
}

u8 fanGetSpeedPercent(u8 i)
{
  return ((fanSpeed[i]*100)/255);
}
```
Shouldn't **fanSetSpeedPercent()** be **fanSpeed[i] = (percent * 255) / 100;** to match le fanGetSpeedPercent formula?

**Comment by GregSKR** [comment]
btw, happy to see the "fan half speed" icon back. It will look nicer with the picture "shadowed" like the others:
Sans titre-1
BMP : [fan_half_speed.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4817764/fan_half_speed.zip)

**Comment by digant73** [comment]
The persistent temp display drops last bed temp digits.

for example, with nozzle temp set to 100 and bed temp set to 100 you will only see this in the upper right corner of the display:

100/100 100/10

Below a picture showing the problem:

IMG_20200626_113221

**Comment by Hukuma1** [comment]
@digant Is it possible to have the icon right next to the number? Right now bed icon is a lot farther left in latest change.

**Comment by rightawy** [comment]
@bigtreetech  please merge this PR

**Comment by digant73** [comment]
> @digant Is it possible to have the icon right next to the number? Right now bed icon is a lot farther left in latest change.

if you refer to my last picture, it is correct. The logic used is to have icons in the same position while values centered to "/" char fixed position (avoiding values are shifted on the left or right during update)

**Comment by Hukuma1** [comment]
> > @digant Is it possible to have the icon right next to the number? Right now bed icon is a lot farther left in latest change.
> 
> if you refer to my last picture, it is correct. The logic used is to have icons in the same position while values centered to "/" char fixed position (avoiding values are shifted on the left or right during update)

Something like this:
example

The extra spacing removed if not all numbers being used. Otherwise for people like me who only print PLA and bed constantly only stays at 60 temperature max, there is going to be a big gap and look misaligned.

That's why I asked if you could possibly improve the logic to move the icons accordingly to spacing depending on if number will be 00/000 or 000/000 or 00/00.

**Comment by digant73** [comment]
> > > @digant Is it possible to have the icon right next to the number? Right now bed icon is a lot farther left in latest change.
> > 
> > 
> > if you refer to my last picture, it is correct. The logic used is to have icons in the same position while values centered to "/" char fixed position (avoiding values are shifted on the left or right during update)
> 
> Something like this:
> example
> 
> instead of:
> example2
> 
> The extra spacing removed if not all numbers being used. Otherwise for people like me who only print PLA and bed constantly only stays at 60 temperature max, there is going to be a big gap and look misaligned.
> 
> That's why I asked if you could possibly improve the logic to move the icons accordingly to spacing depending on if number will be 00/000 or 000/000 or 00/00.

Yes, I understand what you would like, but it is better that icons and values have fixed positions. However, you can easily change the logic as you want. It's a personal preference.

**Comment by digant73** [comment]
@guruathwal

There seems to be some problem with printing long filenames. When I tried to print AG_v2_bracelet_4_hole_3D_PRINTED-3DN_Standard-30_speed-1_retract.gcode it froze and I couldn't select OK/Cancel. It worked after I renamed it to TPU-bracelet.gcode

**Comment by Hukuma1** [comment]
> > > > @digant Is it possible to have the icon right next to the number? Right now bed icon is a lot farther left in latest change.
> > > 
> > > 
> > > if you refer to my last picture, it is correct. The logic used is to have icons in the same position while values centered to "/" char fixed position (avoiding values are shifted on the left or right during update)
> > 
> > 
> > Something like this:
> > example
> > instead of:
> > example2
> > The extra spacing removed if not all numbers being used. Otherwise for people like me who only print PLA and bed constantly only stays at 60 temperature max, there is going to be a big gap and look misaligned.
> > That's why I asked if you could possibly improve the logic to move the icons accordingly to spacing depending on if number will be 00/000 or 000/000 or 00/00.
> 
> Yes, I understand what you would like, but it is better that icons and values have fixed positions. However, you can easily change the logic as you want. It's a personal preference.

Cool. When you say I can easily change it, you mean it's in options setting? Or I must code it? Because if it's the latter, please make it the former. ;)

**Comment by digant73** [comment]
> > > > > @digant Is it possible to have the icon right next to the number? Right now bed icon is a lot farther left in latest change.
> > > > 
> > > > 
> > > > if you refer to my last picture, it is correct. The logic used is to have icons in the same position while values centered to "/" char fixed position (avoiding values are shifted on the left or right during update)
> > > 
> > > 
> > > Something like this:
> > > example
> > > instead of:
> > > example2
> > > The extra spacing removed if not all numbers being used. Otherwise for people like me who only print PLA and bed constantly only stays at 60 temperature max, there is going to be a big gap and look misaligned.
> > > That's why I asked if you could possibly improve the logic to move the icons accordingly to spacing depending on if number will be 00/000 or 000/000 or 00/00.
> > 
> > 
> > Yes, I understand what you would like, but it is better that icons and values have fixed positions. However, you can easily change the logic as you want. It's a personal preference.
> 
> Cool. When you say I can easily change it, you mean it's in options setting? Or I must code it? Because if it's the latter, please make it the former. ;)

it was the latter. But you can try the latest update provided by guruathwal if it is ok for you

**Comment by MrTimPovey** [comment]
Is it possible to expand the status line to include a second nozzle temp?

**Pull request merged**
