### PR TITLE
Fixed random pause/hesitation when printing

### LINKED ISSUE #2761: [Q] Random pauses or hesitation when printing.
While printing once or twice a print, sometimes more, the machine will stop right in the middle of printing for a second, maybe even two. No errors or anything, it leaves an ugly blob, and it just continues on. It does not happen the same place on the file or on the machine. If I had to say anything, it might happen more often during circle moves, or curves. This does not happen while using the same screens for my CNC machines.

I have 6 printers  and 2 CNC's running TFT35 V3 E3 screens. I have noticed this issue for probably as long as I have used the screens, more than two years I would guess. Some screens are brand new and some are very old. I update marlin and the TFT several times a year. Some of my gcode is old and ran perfectly fine on older 1286 screens, and some of my files are new.

So I think this is either some sort of configuration issue, slicer setting, or a screen firmware bug. Any ideas?

Config, 
[config.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/11165582/config.zip)

### PR DESCRIPTION
**Pull request by digant73**
**BUGFIXES:**
- Fixed #2761: Based on deep analysis and testing shared by @rondlh on #2761
- Improved partial message retrieval handling: `Serial_Get` finction in `SerialConnection` API improved to prevent the possibility to read multiple times the same partial message on next function invokation

fixes #2761 

**PR STATE:** Ready for merge

### CODE REVIEW

**Comment by rondlh** [comment]
How to get this PR merged asap?

**Comment by digant73** [comment]
It seems to be ok. Other features like advanced ok or any other improvement can be provided in a separate PR.

**Comment by rondlh** [comment]
> It seems to be enough to solve the issue (just keeping in this PR the minimal code).`Serial_Get` (reader) and `USART_IRQHandler` (writer) are totally decoupled now. #2761 is open since April. Other features like advanced ok or any other improvement can be provided in a separate PR.

@digant73 Are you responding to me? If so then you seem to have misunderstood my question...

**Comment by rondlh** [comment]
> I have also to work and travel during the day. If you are afraid about the possible issue due to no use of `volatile` for wIndex I just made an edit in my last comment in #2761. It will be added.

I mean this... many PRs have NOT been merged for a long time, perhaps BTT is not paying much attention, so the question is how do we get your recent work merged asap? I'm not worried about the volatile variable, it has been off during all of my testing.

**Comment by digant73** [comment]
> > I have also to work and travel during the day. If you are afraid about the possible issue due to no use of `volatile` for wIndex I just made an edit in my last comment in #2761. It will be added.
> 
> I mean this... many PRs have NOT been merged for a long time, perhaps BTT is not paying much attention, so the question is how do we get your recent work merged asap? I'm not worried about the volatile variable, it has been off during all of my testing.

I can only suppose that some PRs are not merged for reasons that the author perfectly know. After that said, as far as I see BTT is OoO since more than 10 days. I already asked BTT to consider to merge many PRs if it can help.

**Comment by V1EngineeringInc** [comment]
Niiiice!!

**Comment by rondlh** [comment]
Merged 🥇  Great job, thanks for your support!

**Pull request merged**
