### PR TITLE
New HW_Init, ModeSwitching and Touch_Endoder API

### PR DESCRIPTION
**Pull request by digant73**
**IMPROVEMENTS:**
* Created new API HW_Init, ModeSwitching and Touch_Encoder: the hw functions (generic hw and specific for Marlin and Touch mode) were moved on HW_Init API. The SW encoder functions were moved on Touch_Encoder API. The mode switching functions were moved to ModeSwitching API
* extend.c/h renamed to SmartFeatures,c/h: the smart home features was moved from menu.c to SmartFeatures.c
* PowerFailed.c/h menu renamed to PrintRestore.c/h: power failed functions were moved to the new API PowerFailed (this API is used also by other menus and API (e.g. Printing)
* Changed land code for dutch language file: The proper land code is NL instead of DU
* Minor optimizations
* Some cleanup

**PR STATE:** ready to merge

### CODE REVIEW

**Comment by Help3D-Padova** [comment]
@digant73 with the MKSTFT28 the changemode is not working after this update. Have you tried on that hardware ? 

I uploaded the compiled files here in the branch but same issue.

#   Options: [Marlin Mode: 0, Touch Mode: 1, Blocked Marlin Mode: 2, Blocked Touch Mode: 3]
default_mode:1

Tried also to force "Marlin mode" but still touch on booting.

Any hints ?

**Comment by digant73** [comment]
try to compile the code instead of using the compiled version. It perfectly works with both the Marlin support (HW changes) and only Touch support (the standard version on BTT main branch)

**Comment by digant73** [comment]
screenshot feature is not supported on MKS TFT. I will see if it can be provided even for MKS

**Comment by Help3D-Padova** [comment]
@digant73 not a big problem ! Is anyone sharing a screen of ALL FW pages at the last revision ?

**Pull request merged**
