### PR TITLE
Home, sweet home

### LINKED ISSUE #1137: [FR] Add ability to get to home screen with 1 click from any screen please
Can you please add ability to get to home screen with a single click from any screen. It is really boring to click multiple time 'Back' button

### PR DESCRIPTION
**Pull request by kisslorand**
### Requirements

BTT or MKS TFT

### Description

Long press "Back" button brings you to the home screen. It takes 1/3 of the long press time needed for the Marlin/Touch mode change. 
Holding Back button will not trigger the Marlin/Touch mode change menu.
This function works only in menus where there are icons, not applicable for menus like Notification, Terminal, File selection, Parameter setting, etc. 

### Benefits

Everyone.

### Related Issues

Fixes #1137

### Additional info

This PR doesn't bring any new popups, there are no user selectable/adjustable parameters. It doesn't remove anything else than the ability to enter into the Marlin/Touch mode selection menu by holding the Back button.
This feature can be enabled or disabled in `Configuration.h` by `#define SMART_HOME`.

Extra RAM usage: 4-8 bytes (depending on board)
Extra flash usage: ~~288-708~~ 264-684 bytes (depending on board)

Original idea by @traffic-light: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1137#issuecomment-700086095

### CODE REVIEW

**Comment by oldman4U** [comment]
Have you checked if this conflicts with the screenshot feature introduced by BTT app 10 days ago?

**Comment by oldman4U** [comment]
Great I could help.

**Comment by kisslorand** [comment]
This PR is fully functional, it is kept as Draft to see if anyone complains about the change of Back button long press from "Marlin/touch mode" or "Screenshot feature" to "Back to home feature".

**Comment by kisslorand** [comment]
In the printing menu, after the print the "Main" becomes obsolete, since long press "Back" will bring you to the Main menu.
It can be replaced with anything else.
Any suggestions?

**Comment by digant73** [comment]
@kisslorand That should be ok as it is. The smart home feature is an extra feature to speed up the moving on main menu. Also beeing handled in the main loop, I would make it configurable in Configuration.h. So anyone can choose to enable/disable it according to his personal preference

**Comment by kisslorand** [comment]
@digant73 
Done. Thanks for the advices.

Now remains the question, the "smart home" option should be enabled or disabled by default? Many users just download the prebuilt bin file.
Well, I left it enabled and keep this as a draft to see further if anyone complains.

**Comment by kisslorand** [comment]
@bigtreetech 
Give this PR a spin, it's ready to be merged.

**Comment by sarvenn** [comment]
Today I updated my fw to latest release. I've noticed that this feature doesn't work on smaller back buttons such as in the feature menu (list view I suppose). Just wanted to stop by and let you know @kisslorand .

**Comment by kisslorand** [comment]
> This function works only in menus where there are icons, not applicable for menus like Notification, Terminal, File selection, Parameter setting, etc.

It's written in the presentation of this PR.

**Pull request merged**
