### PR TITLE
Enable RRF Macros menu support

### PR DESCRIPTION
**Pull request by pfn**
### Requirements

* Add menu to display macros from RRF
* Execute macros
* Config file setting to show or hide menu
 
### Description

Enables a Macros menu when `rrf_macros_on: 1` is set in config.ini

Can browse and execute macros in the top-level. This support was rebased onto master from https://github.com/Thro42/BTT-SOVOL-TouchScreenFirmware-Duet. However it is more robust than the original version.

Limitations:
* macros cannot be interactive, no prompts or confirmations
* the TFT will block until the macro completes running (intentional)

### Benefits

This is a feature enhancement to allow users on BTT TFT on RepRapFirmware to execute macros stored on the printer.

### Related Issues

#1400 this improves RRF support.

### CODE REVIEW

**Comment by digant73** [comment]
Please in MainPge.c convert 

 if (infoSettings.rrf_macros_enable) {
    mainPageItems.items[5].label.index = LABEL_MACROS;
  }

to

 if (infoSettings.rrf_macros_enable)
 {
    mainPageItems.items[5].label.index = LABEL_MACROS;
  }

Always use two spaces for indent. In Macros.c there are some parts with 4 spaces.
Always set the editor to convert tabs to spaces and to remove trailing spaces

**Comment by pfn** [comment]
cc @Thro42 so that you're aware that your changes have been rebased onto master

**Comment by Guilouz** [comment]
Missing string #define STRING_MACROS "Macros" in other language files

**Comment by digant73** [comment]
@Guilouz already fixed and merged by PR #1716

**Comment by Guilouz** [comment]
> @Guilouz already fixed and merged by PR #1716

yes I saw that afterwards

**Pull request merged**
