### PR TITLE
Add support for Home Offset

### PR DESCRIPTION
**Pull request by amp-man**
### Description

This implements `M206` - Home Offset for X,Y,Z axes in the parameters, as well as functions for getting and setting (at the moment) only the z offset.

Previously, "Save" in the babystepping menu would only try to store the babystepping values with `M851` - XYZ Probe Offset. Now, according to the reported settings by marlin, if z probe is not enabled, the offset gets stored with `M206` - Set Home Offsets.
So, if you do manual bed leveling and/or have no z probe installed, you can save your babysteps.

### Benefits

Adds support for Home Offset in Parameters and also allows to store Babysteps to EEPROM when no Z Probe is installed.

### CODE REVIEW

**Review by digant73 — CHANGES_REQUESTED** [review]
Please in your PR restore the current probeOffsetControl.c. I see you changed only a variable name.
In my current PR I also provided other optimization, so they will conflict with your PR in this moment

**Comment by amp-man** [comment]
> Please in your PR restore the current probeOffsetControl.c. I see you changed only a variable name.
> In my current PR I also provided other optimization, so they will conflict with your PR in this moment

Hi, sure, I changed it back. Would you be open for a change to z_probe_offset_value after your pr is merged? I think it would reduce ambiguity, especially when there would be probe z offset and home z offset now.

**Comment by digant73** [comment]
> > Please in your PR restore the current probeOffsetControl.c. I see you changed only a variable name.
> > In my current PR I also provided other optimization, so they will conflict with your PR in this moment
> 
> Hi, sure, I changed it back. Would you be open for a change to z_probe_offset_value after your pr is merged? I think it would reduce ambiguity, especially when there would be probe z offset and home z offset now.

I already changed the name in the past due it was too long (and "probe" was redundant and not important). Also others variable names (in other API) have the same naming convention now. However there is no ambiuguity at all. You also defined "home_offset_z_value" in your code as "static" so the scope is local to your source code. Honestly I would call it simply "z_offset" as I did. For sure, I would invert offset_z to z_offset in your variable name.
Please also have a look to my babystep.c. I also changed something in my PR (in the same way as in probeOffset.c). It should be better your changes are also compliant to my changes.

**Comment by amp-man** [comment]
@digant73 Thanks for explaining. I agree. How would I go about aligning my pr with yours? PR to your fork?

**Comment by digant73** [comment]
I think my PR will be merged before yours. After that I will review your PR with some changes

**Review by digant73 — CHANGES_REQUESTED** [review]
Hi
Attached the reviewed code compliant to my just merged babystep.c.
Please, check it works with your homeOffsetControl.c.
Also have a look to the changes I applied to probeOffsetControl.c. Eventually apply the same logic in your homeOffsetControl.c so both will be aligned for future changes/improvements


[Babystep.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5457458/Babystep.zip)

**Comment by bigtreetech** [comment]
@digant73 Hello, It seems that "offset" value does not change with babystep after #1111. It is only used as display in this menu?

**Comment by digant73** [comment]
@bigtreetech do you mean with the integration of this PR z offset is not updated properly? or do you mean that on my PR the z offset value is not displayed properly or do you mean that changing babystep (so also z offset) the z offset is not set even saving to eeprom? It should work in both cases (as it was in the past). However I will have a look this evening. The Z value is now queried with the same API used also in the Move menu

**Comment by bigtreetech** [comment]
@digant73  I mean that `offsetSetValue(z_offset)` is useless now, Because of the `z_offset` is only updated by the actual value fed back from Marlin In Babystep menu, So it's unnecessary to set  `z_offset` again by `offsetSetValue(z_offset)` .
It just shows that `z_offset` and not actively modified, but gives this work to Marlin's `BABYSTEP_ZPROBE_OFFSET`. Now the logic is clearer than before
But in this PR, Babystep will never change the value of home offset, because there is no function of `BABYSTEP_HOME_OFFSET` in Marlin

**Comment by digant73** [comment]
@bigtreetech yes you are right. In this case it's no more needed to save z offset. If BABYSTEP_ZPROBE_OFFSET is disabled in Marlin, z offset will not be changed so a change in babystep menu will not change z offset (it will respect the Marlin setting). In that case the z offset menu has to be used to change z offset. If home offset is also never changed changing babystep (because BABYSTEP_HOME_OFFET does not exists), the fuction "offsetSetValue()" can be removed. In this case this PR is not so much usefull. I mean a "home offset" menu should be provided

**Comment by oldman4U** [comment]
Hallo @amp-man. (Man beachte die deutsche Ansprache;-))

Now that your PR has been merged I would like to ask you, if you would be available for additional contributions. If so, it would be great if you could check #1170 and #1218 and let me know.

Danke

**Comment by amp-man** [comment]
Hallo zurück, @oldman4U :)

I am interested in contributing, but do not know when I'll have time available atm. (university started again).
If I start working on a feature, I'll let you know :)

**Comment by oldman4U** [comment]
👍🏻

Thank you und alles Gute für das Studium. Erstes Semester?

ampman <notifications@github.com> schrieb am Do. 5. Nov. 2020 um 14:16:

**Comment by amp-man** [comment]
Thanks for merging digant73's suggestions, @bigtreetech (I assume @Msq001 is you). I tried a rebase after #1188 was merged, but was not happy with the results. As far as I understand, you are talking about the fact that Marlin provides a dedicated G-Code for changing z probe babystep values, but if you don’t have a z probe, then you do not really save babystep values with a dedicated G-Code, so you could just change the home offset in the machine parameter menu. Is that right?

**Comment by amp-man** [comment]
> 👍🏻 Thank you und alles Gute für das Studium. Erstes Semester? ampman <notifications@github.com> schrieb am Do. 5. Nov. 2020 um 14:16:
> […](#)

Nein, schon etwas weiter :)

**Comment by oldman4U** [comment]
Bist im München, right. If so, kennst du einen Ösi namens Simon?

ampman <notifications@github.com> schrieb am Do. 5. Nov. 2020 um 14:18:

**Comment by amp-man** [comment]
> Bist im München, right. If so, kennst du einen Ösi namens Simon? ampman <notifications@github.com> schrieb am Do. 5. Nov. 2020 um 14:18:
> […](#)

Sagt mir jetzt gerade nichts, aber kann gut sein dass man sich mal über den Weg gelaufen ist.

**Comment by oldman4U** [comment]
Wäre ein großer Zufall gewesen. Will dich jetzt nicht mehr aufhalten.

Happy printing

ampman <notifications@github.com> schrieb am Do. 5. Nov. 2020 um 14:34:

**Comment by amp-man** [comment]
> Wäre ein großer Zufall gewesen. Will dich jetzt nicht mehr aufhalten. Happy printing ampman <notifications@github.com> schrieb am Do. 5. Nov. 2020 um 14:34:
> […](#)

No worries, @oldman4U. Same!

**Pull request merged**
