### PR TITLE
BIQU Bootscreen => BigTreeTech Bootscreen

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Replace the BIQU bootscreen with BigTreeTech's logo/Bauhaus typeface to match existing branding. I also fixed the "Marlin's Mode" typo and renamed "12864 Mode" to "Marlin Mode" in `Configuration.h` for consistency.

### Benefits

The logo was created after initial interest by users in the main [BigTreeTech Facebook group](https://www.facebook.com/groups/505736576548648/) and working with Biqu Hope. An [informal poll was taken](https://www.facebook.com/groups/505736576548648/permalink/801528553636114/) and final approval received from from Biqu Hope.

Comparison:

Screen Shot 2019-11-06 at 11 32 05 PM

### CODE REVIEW

**Comment by Sthopeless** [comment]
I've been using it on all my TFT's since you posted on Facebook, does look a lot better :p 
Thank you!

**Comment by thisiskeithb** [comment]
Thanks for the kind words, @Sthopeless!

I was bored and created another one for my Enders:

image

I'm hoping to work on another graphic/icon "pack" this weekend specifically for the Crealtiy series that'll include it as well as color variants. We'll see 😜

**Comment by Sthopeless** [comment]
Looking forward to it then ;) 
Do you think it is possible to have a few 'packs' already preloaded on the TFT and choose which one we are using on the fly!? 
In the long run I think it would be easier then having to 'reflash' them

**Comment by thisiskeithb** [comment]
> Do you think it is possible to have a few 'packs' already preloaded on the TFT and choose which one we are using on the fly!?

Anything is possible with enough time 😉

You should put in a [Feature Request](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/new).

**Comment by Tim-The-Woodsman** [comment]
To be honest it confused me to see my BigTreeTech screen and board to boot up with a BIQU logo. Thanks!

**Comment by thisiskeithb** [comment]
> To be honest it confused me to see my BigTreeTech screen and board to boot up with a BIQU logo. Thanks!

Best I can tell is that BigTreeTech is a division of Biqu.

**Comment by Tim-The-Woodsman** [comment]
I figured so, yes. At least after talking to a supporter from biqu today which referred me to a colleague with a bigtreetech address. BTT logo is a beauty though :-)

I'll merge your changes into mine, really like it.

**Comment by thisiskeithb** [comment]
BTT has been really welcoming of updates, so I'm sure these will get merged soon 🙂

**Pull request merged**
