### PR TITLE
improve the config color option, set hex color value(RGB888 format) directly

### PR DESCRIPTION
**Pull request by Msq001**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description
improve the config color option, set hex color value(RGB888 format) directly

### Benefits
#699 
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/526#issuecomment-610201284

### CODE REVIEW

**Comment by Msq001** [comment]
@Acenotass hello, I have noticed your suggestion here https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/526#issuecomment-610201284. This PR has realized this function. You can test it

**Comment by Acenotass** [comment]
@Msq001 thank you so much, I'll check it out!

**Comment by mjfox33** [comment]
I have tested this with the following two lines in the config file. It did not show an error message but failed to set them to these colors and defaulted to white for the fg and bg. Also, why are you converting the rbg888 to rgb565 when loading the config file (config.c)? I was hoping to allow for 24bit color in marlin mode.

# Or set the color(RGB888 format) hex value directly(start with “0x”).
# Such as: 0xFF0000 : Red, 0x00FF00 : Green, 0x0000FF : Blue
marlin_bg_color:0x002b36
marlin_fn_color:0x839496

**Comment by bigtreetech** [comment]
@mjfox33 can you test the last precompiled firmware,  I just tested your color settings and it works fine.

converting RGB888 to RGB 565 is because that the TFT LCD is only 16bit color depth. ^_^

**Pull request merged**
