### PR TITLE
Layer update during printing

### PR DESCRIPTION
**Pull request by kisslorand**
### Requirements
BTT TFT or MKS TFT

### Description

Layer update during printing was broken due to PR #1272 
### Benefits

Layer display during printing fixed. It shows the actual layer height, it updates during printing. 
### Related Issues
Fixes this issue: #1314

### CODE REVIEW

**Comment by oldman4U** [comment]
Hi.

Why would you change the event to MKS_32_V1_4?

**Comment by oldman4U** [comment]
And I believe you have a typo, you write "Targetl" but I believe it should be "Target" and suddenly the compiling which failed before also works.

**Comment by kisslorand** [comment]
> Hi.
> 
> Why would you change the event to MKS_32_V1_4?

I keep forgetting to set it back to original before making a commit. MKS_32_V1_4 is what I use for my builds.

> And I believe you have a typo, you write "Targetl" but I believe it should be "Target" and suddenly the compiling which failed before also works.

Yup, there was a typo

New commit is on the way, hope it fixes layer update during print issues for BOARD_SD, TFT_USB and TFT_SD gcode file source.

**Comment by oldman4U** [comment]
👍🏻

kisslorand <notifications@github.com> schrieb am Di. 1. Dez. 2020 um 14:36:

**Comment by mehmetsutas** [comment]
👍🏻

I was just making the same change and saw this. :)

**Comment by kisslorand** [comment]
Does it work with these changes with SD onboard? I can test it only with SD and USB connected to the TFT.

**Review by mehmetsutas — CHANGES_REQUESTED** [review]
Maybe on line 278 we should put the coordinatequery call in ternary if also. If it is not printing from BOARD_SD, we do not need to call coordinatequery frequently.

**Comment by kisslorand** [comment]
Why do you need it when printing from BOARD_SD?

**Comment by mehmetsutas** [comment]
@kisslorand that was exactly what I would do.

**Comment by oldman4U** [comment]
How can I test the code with all PRs failing to check successfully?

**Comment by kisslorand** [comment]
I guess you can check the [changes made](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1319/files) and do that to your files locally than build it. How did you do it before?

**Comment by mehmetsutas** [comment]
I am not able to check it right now. But all changes are reasonable. If it can compile, it should work.

**Comment by oldman4U** [comment]
> I guess you can check the [changes made](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1319/files) and do that to your files locally than build it. How did you do it before?

This works with just a few changes. I use GitHub Desktop to merge PRs to my local repository.

**Comment by oldman4U** [comment]
off topic

@mehmetsutas Have you got a mail from me yesterday?

**Pull request merged**
