### PR TITLE
Another update language_de.h

### PR DESCRIPTION
**Pull request by NetSecond**
Translated new line 358 into german language.

### CODE REVIEW

**Comment by gitmacer** [comment]
@NetSecond Line 36 also needs a translation. If you also translate that no additional PR is needed.

**Comment by gitmacer** [comment]
Attention @NetSecond! LCD_IDLE_TIME means inactive duration until idle mode. I would translate it as "LCD-Timeout" similar to the one Android/Samsung uses (Bildschirm-Timeout).

Also instead of "LCD Helligkeit im Standby" I would translate it as "LCD-Timeout-Helligkeit", "Standby-Helligkeit" or maybe "Reduzierte Helligkeit" to reduce the needed space.

"Blockiere Touch im Idle" using "Standby" earlier and then switching to idle isn't ideal also "Idle" isn't listed in the german dictionary.
I would suggest to use "Kein Touch im Standby".

Other opinions are welcome.

**Comment by NetSecond** [comment]
@gitmacer
Thanks for your informations.

Idle is not a german word but the most people know what Idle is.
Idle is normaly not understood as timeout in germany, here it is translated as "Leerlauf", it meens doing nothing until next task.
I think in english it is translated as "neutral" ?!?!

In case of github errors I have deleted my fork/repository and now I can´t edit the file anymore ....
(I don´t know, what I´ve done wrong, I am new to github ....)

So I tried to change the file as follow:

```
    #define STRING_LCD_BRIGHTNESS         "LCD-Helligkeit"
    #define STRING_LCD_IDLE_BRIGHTNESS    "LCD-Timeout-Helligkeit"
    #define STRING_LCD_IDLE_TIME          "LCD-Timeout"
    #define STRING_BLOCK_TOUCH_ON_IDLE    "Kein Touch im Standby"
```

Sorry and regards,
NetSecond

**Comment by gitmacer** [comment]
> @NetSecond 
> In case of github errors I have deleted my fork/repository and now I can´t edit the file anymore ....

That wasn't a great idea. I don't know if you can easily revert that. I think you need to redo the changes and create a new PR because of that.

Clicking "merge" on the "wrong" PR would have done the job just fine as mentioned there.

> (I don´t know, what I´ve done wrong, I am new to github ....)
I noticed. Everyone started at some point and did mistakes on the way. ^^

**Comment by oldman4U** [comment]
"Touch" isn't german either.

**Comment by gitmacer** [comment]
@oldman4U It is. And it's actually the only "allowed"/used word in
combination with screens etc.
Valid translations for "the touchscreen" are "der Touchscreen" (by far the
most used one), "der Touchbildschirm" and "das Touchdisplay".
Even "Touchpen" and "Touchpad" are german words.
As you can see the word "Touch" is even used in the less common synonyms If
you would use any more "german" word for 1 of these things you would get
weird looks. I can tell you as a German that Touch and Standby are used
(only IT/electric topics) and found in the german dictionary.
Also here is a link to the german dictionary just in case. :)
https://www.duden.de/suchen/dudenonline/Touch

Am Mi., 11. Aug. 2021 um 19:52 Uhr schrieb oldman4U <
***@***.***>:

**Comment by oldman4U** [comment]
Bin jetzt kein Sprachwissenschaftler, aber Touch und ähnliche Anglizismen sind Fremd- oder Lehnwörter und müssten bei einer Übersetzung inbegriffen werden.

Berührung sagt in so einem Fall niemand, weshalb (und nicht nur in diesem Fall) die ganze Übersetzung ziemlich überflüssig ist.

;-)

My2cents

**Comment by gitmacer** [comment]
> Und der Dudenlink bezieht sich dann ja auch auf eine völlig andere Bedeutung dieses Wortes. 

Kinda true. I see now that the 2. meaning of the standalone word isn't currently listed in the one by the private publisher Duden.
But it is listed in the one by the German government.
https://www.dwds.de/wb/Touch#d-1-2

**Comment by gitmacer** [comment]
> Bin jetzt kein Sprachwissenschaftler, aber Touch und ähnliche Anglizismen sind Fremd- oder Lehnwörter und müssten bei einer Übersetzung inbegriffen werden.

Ich weiß nicht ob das stimmt allerdings glaube ich dem Wörterbuch der Regierung welche es genau so und mit Beispielen gelistet hat.

> Berührung sagt in so einem Fall niemand, weshalb (und nicht nur in diesem Fall) die ganze Übersetzung ziemlich überflüssig ist.
> 
> ;-)
> 
> My2cents 

I don't get your point. Do you suggest to stuck with the English term even though it includes definitely not German words?

To me it sounds more like you try to find reasons why my translation is wrong than suggesting/finding a better one.

**Comment by oldman4U** [comment]
There is nothing wrong with your translation. Just thought that touch is worth to be mentioned as well.

**Pull request merged**
