### PR TITLE
Use official docs how to override default LD script // Resolve #126

### LINKED ISSUE #126: TFT35 V2 latest version not updating
when trying to update to the latest version it just stucks on updating screen at 100%, prebuilt version works just fine, so possibility that problem is on my side

### PR DESCRIPTION
**Pull request by ivankravets**
Docs: http://docs.platformio.org/en/latest/projectconf/section_env_build.html#build-flags

### CODE REVIEW

**Comment by ivankravets** [comment]
You can also remove LD related python extra scripts from https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/master/buildroot/scripts

**Comment by reloxx13** [comment]
@bigtreetech

**Comment by thisiskeithb** [comment]
I applied the patch, but more changes are needed before it'll build with this commit:

```prolog
> Executing task: platformio run <

Processing BIGTREE_TFT35_V3_0 (platform: ststm32; framework: stm32cube; board: STM32F103VC)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
ValueError: too many values to unpack:
  File "/Users/keith/.platformio/penv/lib/python2.7/site-packages/platformio/builder/main.py", line 149:
    env.SConscript(item, exports="env")
  File "/Users/keith/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py", line 541:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/Users/keith/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py", line 250:
    exec _file_ in call_stack[-1].globals
  File "/Volumes/github/BIGTREETECH-TouchScreenFirmware/buildroot/scripts/custom_filename.py", line 5:
    flags = {k: v for (k, v) in build_flags.get("CPPDEFINES")}
  File "/Volumes/github/BIGTREETECH-TouchScreenFirmware/buildroot/scripts/custom_filename.py", line 5:
    flags = {k: v for (k, v) in build_flags.get("CPPDEFINES")}
=========================================================================================================== [FAILED] Took 0.61 seconds ===========================================================================================================

Environment         Status    Duration
------------------  --------  ------------
BIGTREE_TFT35_V1_0  IGNORED
BIGTREE_TFT35_V1_1  IGNORED
BIGTREE_TFT35_V1_2  IGNORED
BIGTREE_TFT35_V2_0  IGNORED
BIGTREE_TFT35_V3_0  FAILED    00:00:00.614
BIGTREE_TFT28_V1_0  IGNORED
BIGTREE_TFT24_V1_1  IGNORED
===================================================================================================== 1 failed, 0 succeeded in 00:00:00.614 =====================================================================================================
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

**Comment by ivankravets** [comment]
@thisiskeithb I've just updated PR. Please re-test.

**Comment by ivankravets** [comment]
@thisiskeithb could test 2 firmwares inside?

[BIGTREE_TFT35_V3.0.24.2.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/3826221/BIGTREE_TFT35_V3.0.24.2.zip)

**Comment by thisiskeithb** [comment]
> @thisiskeithb could test 2 firmwares inside?

Same issue I'm seeing over here when self-compiling: `BIGTREE_TFT35_V3.0.24.2_piocore_403.bin` works, while `BIGTREE_TFT35_V3.0.24.2_piocore_410.bin` does not.

**Comment by ivankravets** [comment]
@thisiskeithb please remove your fork and re-test this https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/136

Thanks!

**Pull request closed without merging**
