### PR TITLE
Improved Terminal menu based on TFT size and resolution

### LINKED ISSUE #1181: [FR] In Terminal, move the letter F from the ABC page to 123 page
**Is your feature request related to a problem? Please describe.**
I've recently refitted my 3DTouch a couple of times and each time needed to type the command G1 F60 Z0. But 'F' is on the alphabetic screen so requires 3 screen taps instead of 1.

**Describe the solution you'd like**
Move the ABC to bottom right and move the SPACE down to where ABC was. Move Z to where SPACE was. Move E to where Z was. Add F where E was.

Also rearrange ABC screen similarly and duplicate E, S & T so they are available of both screens since these are common letters in text.

`
1 2 3 M G DEL`
`
4   5   6   X   Y   Z`
`
 7   8   9   E   F  SPC`
 `
.   0   -   S   T  ABC`

 `
A   B   C   D   E  DEL`
`
 H   I   J   K   L   N`
`
 O   P   Q   R   S  SPC`
`
 T   U   V   W   Y 123`
 

**Describe alternatives you've considered**
Keep switching back and forth between screens

**Additional context**
There is space for the additional F key on the numeric screen and it is commonly used in GCode commands

### PR DESCRIPTION
**Pull request by digant73**
Based on the idea of StarNamer on his PR #1191, just to speed up the merge on BTT main repo due to my last changes already applied on Terminal menu.
I don't have any TFT sample from BTT to test the layout on all the TFT variants, so I ask you to test in your TFT and eventually provide your feedback. I simple verified that the 3 layouts are correctly displayed in my TFT and the terminal correctly works.
Thanks to StarNamer!

**IMPROVEMENTS:**

* **Improved Terminal menu:**
 1) three different layouts based on TFT size and resolution:
  * TFT width < 480 pixels: a 6\*6 layout is used (4\*6 keyboard)
  * TFT width < 800 pixels: a 6\*7 layout is used (4\*7 keyboard)
  * TFT width >= 800 pixels: a 8\*10 layout is used (6\*10 keyboard)
 2) just some refinements on the GUI (big fonts also for the control bar in the terminal page, some shadows on the control bars...)
 3) three keyboard color layouts selectable on Configuration.h:
  * standard 1 and 2: standard configurable (in config.ini) font, background, and line colors are used (e.g. white, black and gray)
  * alternative: black, white and blue colors are used
 4) standard configurable (in config.ini) Marlin font and background colors used on the terminal menu
 5) QWERTY keyboard layout selectable on Configuration.h for the 7" TFT
* resolves #1181

* **Improved Babystep menu:**
 1) with the support to both Probe/Home offset, the Babystep menu is now also able to display with a different color (the configurable color "reminder_color" in config,ini) the Z offset values not automatically changed applying babystep changes (e.g. if no BABYSTEP_ZPROBE_OFFSET is set in Marlin FW). This means that, in order to apply (set) and make permanent (on EEPROM) the displayed Z offset value, the user MUST click in the save button and accept to save to EEPROM. Otherwise, that value will be lost exiting from the menu or resetting the printer

**CLEANUP:**
* removed directory TFT/scr/User/Language Packs because no more needed
* changed comments in config.ini to reflect the correct maximum lenght of "start", stop" and "cancel" gcodes. It was wrongly reported 50 instead of 75
* MeshEditor.c: some cleanup

**PR STATE:**
* **FINAL:** Ready to be merged with BTT main branch:

Terminal color layout:

IMG_20201105_212520

Standard 1 keyboard color layout:

IMG_20201106_202059

Standard 2 keyboard color layout:

IMG_20201108_131051

Alternative keyboard color layout:

IMG_20201106_202433

The pictures below are only to show the layout that will be displayed on a 7" TFT. Clearly on a real 7" TFT the layout and the size of the key will differ:

IMG_20201105_212448

QWERTY keyboard layout for a 7" TFT:

IMG_20201108_130728

### CODE REVIEW

**Comment by oldman4U** [comment]
Cool.

Like I said, a TFT28 is available and maybe DHL will deliver a TFT24 tomorrow. But for the test, the 28 will be good enough. You have a TFT35, right, or should I test it also?

**Comment by Hukuma1** [comment]
Looks great! 

Any chance of inverting the color scheme for the main terminal screen? The white background could be black, text can be white. Or have a second version that would fit with the darker Material Design theme of BTT TFT. This white one could be great for the Classic theme.

**Comment by digant73** [comment]
@Hukuma1 
I used the same colors of the old Terminal. The white and black colors are the configurable font_color and bk_color but inverted (bk used for the foreground and font used for background). I will swap the color and see how it appears

**Comment by oldman4U** [comment]
Look, a new member of my family arrived today.
[Uploading 242835.pdf…]()

Which firmware PR should I test now?

**Comment by digant73** [comment]
@oldman4U 
Nice. Of course with that TFTs you MUST test this PR. It is the final version. Two keyboard color layouts configurable in Configuration.h. By default, the standard layout is available

**Comment by oldman4U** [comment]
So I will do. But tomorrow.

My first impression was - unusable tiny - but I must say even the 6
elements horizontally are usable 95%+.

digant73 <notifications@github.com> schrieb am Fr. 6. Nov. 2020 um 22:40:

**Comment by StarNamer** [comment]
@digant73 I'm pleased you were able to merge my early work. It looks great. I've been using my 7x4 for a few weeks on my TFT35 with no trouble, and my quick hack simulating your 7x4+abc/del/space/back  seems to be completely OK this week (despite my color errors) so would expect yours to be fine.

We had a major new system go live at work this week, so as expected, I didn't get a chance to do any more  code fixing, just running a few prints, but I'm glad you found time to implement it. I, too, would like to see if there's anyone using a TFT70 who can test that layout and see if it's OK; since it has space for 10 keys across, I did wonder about putting 1 to 9 and 0 on one row then arranging the letters in a QWERTY layout, but for most users, alphabetic is probably better.

There was one issue I noticed. While running a print from Octoprint which was displaying ETA and ETL messages every 10 seconds, I switched the TFT to terminal mode and clicked Send (no command) which switched it to monitoring the output (this is a useful, if possibly unintended, feature). I then left it for some time receiving output, and when I looked, the page count had gone negative. I reproduced this with a constructed GCode script for a very small model which output every command with M117 before executing it. I haven't looked if this is a simple issue and, of course, it may just be my variant. I hope to find time to download your updated version soon and try that.

Once again, good job. I'm impressed.

20201108_005955 (2) (1118 x 768)

**Comment by digant73** [comment]
@StarNamer 
Thanks for the feedback. The problem with the negative page numbers should be solved now.
Also the QWERTY layout is now available for the 7" TFT.

**Comment by oldman4U** [comment]
Aha. Wanted to send a before - after, but it is already outdated firmware;-)

IMG_7419
IMG_7420

Great work!

**Pull request merged**
