### PR TITLE
 separate y-axis invert for manual leveling menu

### PR DESCRIPTION
**Pull request by Msq001**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description
* Delete useless judgments in `reDrawProgress` for clean
* Separate y-axis invert for manual leveling menu
* clean up `infoPrinting` struct

### CODE REVIEW

**Comment by digant73** [comment]
@bigtreetech please in setPrintAbort() in Printing.h add the following comment above infoHostprinting = false:

void setPrintAbort(void)
{
  // always reset the flag reporting the host is printing (even if the TFT didn't intercept it yet)
  // due to no further notifications will be sent by the host to notify it is no more printing
  infoHost.printing = false;

  // if printing from onboard SD or remote host
  if (infoPrinting.printing && infoFile.source >= BOARD_SD)

**Comment by oldman4U** [comment]
Hi.

Unfortunately this does not fix the problem.

With Y and LY set to 0 the 5 point levelling is OK, but the Y axis is inverted while Move. So I  set Y1 and LY0, because the is OK. Unfortunately this inverted the axis for both, so the Move was OK, but for the 5 point levelling the y axis was inverted. So this means the Y value not only affects the Move but also the 5 point levelling. Good that we have the ability to change this also (even I believe changing the Y should not change the levelling also), so I defined Y1 (to get the correct Move menu) and LY1 (to invert the wrong invert of LY by defining Y1). Unfortunately this does not change anything, so it seems that LY is ignored as soon an Y is set to 1. So now I have 4 options and not a single one gives me the correct result.

Y0 and LY0: Move wrong, 5 point OK
Y1 and LY0: Move OK, 5 point wrong
Y0 and LY1: Move wrong, 5 point OK
Y1 and LY1: Move OK, 5 point wrong

From here we have 2 options:
1: LY ignores whatever is defined as Y.
2: LY allows to invert what ever the result of Y is, does not matter if it is 1 or 0.

**Comment by bigtreetech** [comment]
> Hi.
> 
> Unfortunately this does not fix the problem.
> 
> With Y and LY set to 0 the 5 point levelling is OK, but the Y axis is inverted while Move. So I set Y1 and LY0, because the is OK. Unfortunately this inverted the axis for both, so the Move was OK, but for the 5 point levelling the y axis was inverted. So this means the Y value not only affects the Move but also the 5 point levelling. Good that we have the ability to change this also (even I believe changing the Y should not change the levelling also), so I defined Y1 (to get the correct Move menu) and LY1 (to invert the wrong invert of LY by defining Y1). Unfortunately this does not change anything, so it seems that LY is ignored as soon an Y is set to 1. So now I have 4 options and not a single one gives me the correct result.
> 
> Y0 and LY0: Move wrong, 5 point OK
> Y1 and LY0: Move OK, 5 point wrong
> Y0 and LY1: Move wrong, 5 point OK
> Y1 and LY1: Move OK, 5 point wrong
> 
> From here we have 2 options:
> 1: LY ignores whatever is defined as Y.
> 2: LY allows to invert what ever the result of Y is, does not matter if it is 1 or 0.

Hello, do you have the newest .bin file compiled by the new source code ? After updating the new .bin, the following settings can make your printer move as expected
`invert_axis:X0 Y1 Z0 LY0`

**Comment by oldman4U** [comment]
I used your branch. Precompiled fw and config.ini with LY in it.

**Comment by oldman4U** [comment]
Ok. Will test again using Master and let you know asap.

**Comment by bigtreetech** [comment]
> Ok. Will test again using Master and let you know asap.

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/master/Copy%20to%20SD%20Card%20root%20directory%20to%20update
This should work well.

**Comment by oldman4U** [comment]
YES!!!!!

Now it works GREAT. Y affects ONLY Move and LY affects ONLY 5 point levelling.

THANK YOU

**Pull request merged**
