### PR TITLE
Flow,speed,fan - reworked

### PR DESCRIPTION
**Pull request by kisslorand**
### Requirements

BTT TFT or MKS TFT

### Description

This is a major rework of the  Speed, Flow and Fan adjustment. It uses a different approach of stacking consecutive speed, flow and fan related commands. It is making sure the desired value is sent to Marlin, feedback is used. No more fiddling and guesswork.

### Benefits

Users can now adjust  the FeedRate, FlowRate, FanSpeed during print without hiccups, the adjustment is straight forward. the desired and actual values are displayed so no guessing what's going on, just as in the heating menus (actualValue/desiredValue). User can abuse the adjustment buttons, desired value will refresh instantly. Rapid firing those buttons will not clog the print queue, only the relevant values are sent.

### Related Issues

#1139 #1409

### Remarks

The unit of the adjusted values are displayed above the "actualValue/desiredValue" because of design constrains. It's the best I could come up with.

### CODE REVIEW

**Comment by digant73** [comment]
I would use the prefix "target" and "current" for the variables and funtions names instead of "set" or "cur"

**Comment by kisslorand** [comment]
Good advice. I started with "desired" and "current" than changed my mind because of length considerations.

**Comment by oldman4U** [comment]
@kisslorand I have no idea what you have done, but it works GREAT!!!

Tested printing from on board and TFT based storage and the values are taken over reliable, does not matter how fast I click or when I use the keypad.

The only problem I have seen on MY machine is, when I increase the Flow value over 800%, something which is completely useless but hey, it is possible to change it;-) So changing above 800% makes my motor grind and higher values stop the motor. Likely other motors or TMC settings will make this problem occur earlier or later, so I am fine with it. This is a HUGE step forward, THANK YOU!

Once released, I will make some additional tests with the print finished function (Marlin update is still pending...)

@bigtreetech Please merge this great fix asap.

**Comment by kisslorand** [comment]
Thanks for the feedback. 
The "problem" you mentioned is rather a misuse of a feature. There is "SPEED_MAX 999" defined in the TFT's firmware. The flow rate is not an absolute value, it is a factor. If let's say extrusion speed is at 1mm/s than a FlowRate of 800% would make it 8mm/s which is still reasonable. However if you are already at 10mm/s than it would be absurd to have 80mm/s extrusion speed.
If needed, "SPEED_MAX 999" can be reduced to a reasonable value like "SPEED_MAX 200" but max speeds should have been defined according to the machine's spec already in Marlin. It's Marlin's job to supervise max speeds. 
The TFT FW is not machine specific, each machine should have it's Marlin configured properly to its components capability and limits.

**Comment by oldman4U** [comment]
I can not see this is real problem and agree 100% what you say.

Really cool;-)!!!

**Pull request merged**
