### PR TITLE
improved Terminal menu

### PR DESCRIPTION
**Pull request by digant73**
**IMPROVEMENTS:**

* Improved Terminal menu:
 1) Changed layout providing a control bar. Configurable colors are used such as:
  * infoSettings.font_color: used for keyboard
  * infoSettings.bg_color: used for keyboard
  * infoSettings.marlin_mode_font_color: used on terminal window
  * infoSettings.marlin_mode_bg_color: used on terminal window
 2) page and total page count provided in the terminal window

**PR STATE:**
* **FINAL:** Ready to be merged with BTT main branch:

IMG_20201102_220422_1
IMG_20201102_220442_1
IMG_20201102_220505_1

### CODE REVIEW

**Comment by oldman4U** [comment]
Wouldn"t it be good to release it together with #1191?

**Comment by digant73** [comment]
@oldman4U no problem. If the owner of that PR agrees, I can merge his changes in my PR.

**Comment by StarNamer** [comment]
@digant73 Your changes look like what I was think of moving on to if you hadn't already done it and hopefully will be a significant improvement. Moving the non-printing buttons to their own group makes the layout much cleaner.

My changes were basically to include a variation of the number of columns (in ui_draw.h) to better make use of the space on the TFT35 while not making the key areas too small on the TFT24/28. For ease of editing, I moved the array definitions from SendGCode.h to SendGCode.c and, for ease of future layout changes, eventually decided to simply replicate the entire arrays for each variant rather than try to dynamically construct them by macros or multiple tests. I'm sure you'd be able to adopt them easily.

It looks like you've also picked up changes for scrolling  the output similar to [PR 1171](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1171) which I'm looking forward to using.

By the way, I'm still puzzled by the inclusion of ">" on the 123 page since I haven't identified a use for it. What am I missing?

Looks like a great job and I hope to download your changes and take a look later in week.

**Comment by StarNamer** [comment]
Decided I couldn't wait to look at your code. I see, you've moved the arrays/enums into SendGCode.c, the same as I did.

If the TFT24/28 can handle the extra row you've added, then it should work for both the TFT24/28 and the TFT35.

If it can't, you could do something like:
`"1", "2", "3", "4", "M", "G",
`
`"5", "6", "7", "8", "X", "Y",
`
`"9", "0", ".", "-", "E", "F",
`
`"ABC", "Space", "Del", "Back"
`
With something similar on the ABC page.

If 5 rows are OK on the TFT35, then additional keys could be added...
`"1", "2", "3", "M", "G", "S", "T",
`
`"4", "5", "6", "X", "Y", "Z", "E",
`
`"7", "8", "9", "I", "J", "P", "R",
`
`".", "0", "-", "/", "~", "!", "#",
`
`"ABC", "Space", "Del", "Back"
`

I'll try to find time to try out a few ideas in the next few days, based on your code.

**Comment by StarNamer** [comment]
First attempt. Need a few tweaks, but it's 1am!

**Comment by oldman4U** [comment]
It is 3am here reading your posts. I am excited 😆

**Comment by digant73** [comment]
@StarNamer My PR is on top of the merged #1171. Simply provide me your layouts here and I will merge them on my PR

**Comment by rightawy** [comment]
What happened to the concern for people with handicapped and large fingers? https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/967#issuecomment-673647055

**Comment by oldman4U** [comment]
@rightawy 

As far as I understand, StarNamer provides the interface depending on the size of the screen, so it should work like before for the smaller screens. Bigger screens can hold more elements (even the resolution is sometimes lower compared to the TFT35), so it makes sense to allow more elements for those screens (or have bigger buttons).

In general I hope that people like me having big hands do not expect the same functionality independent of the size of the screen. This would be like buying a small car but expecting the comfort of a big car. Somehow this does not match.

My 2 cents like always;-)

**Comment by bigtreetech** [comment]
@StarNamer Hello,  Now I merge this PR, you can make new resolution adaptation changes in #1191, and I will merge #1191 after your optimization

**Pull request merged**
