### PR TITLE
Czech translations for new messages

### PR DESCRIPTION
**Pull request by 3darena**
### Description

1) Added translations for latest or new messages
2) Added INVERT_ZAXIS for printers with bed moving UP/DOWN

### Benefits

Printers with bed moving up/down now have corresponding icons. Icon with arrow down for movemen down and same change for movement up.

### CODE REVIEW

**Comment by guruathwal** [comment]
@3darena 
For Syncing the fork from the Upstream Branch try this:

open Git Bash in root folder of the fork on your computer.
run following commands
1. `git checkout master`
2. `git fetch upstream`
3. `git reset --hard upstream/master`
4. `git push --force`

**This way the PR for Sync will not get pushed to Upstream again.
Earlier I did same as you which resulted in too much difference in commits.**

**Comment by 3darena** [comment]
> @3darena
> For Syncing the fork from the Upstream Branch try this:
> 
> open Git Bash in root folder of the fork on your computer.
> run following commands
> 
> 1. `git checkout master`
> 2. `git fetch upstream`
> 3. `git reset --hard upstream/master`
> 4. `git push --force`
> 
> **This way the PR for Sync will not get pushed to Upstream again. Earlier I did same as you which resulted in too much difference in commits.**

**Comment by 3darena** [comment]
@guruathwal 
I am not so much familiar with git :-/ I have pushed two independent changes, this probabbly made an issue to your tree?

When I am trying your commands, I ending with this message:
```
git fetch upstream
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.
```

**Comment by guruathwal** [comment]
@3darena you need to clone your fork through [GitDesktop](https://desktop.github.com/)

**Comment by 3darena** [comment]
@guruathwal I am Linux user, so this software is not for me :-/

**Comment by guruathwal** [comment]
> @guruathwal I am Linux user, so this software is not for me :-/

@3darena you can try this: https://github.com/shiftkey/desktop

**Pull request merged**
