### PR TITLE
Add Disable Steppers option to menu

### PR DESCRIPTION
**Pull request by Guilouz**
Add option to disable steppers motors from menu.

IMG_1592

### CODE REVIEW

**Comment by bryan065** [comment]
I believe Digant already added XY axis motor off button in #899. Mind if I update your icon to match that? It'll show XYZ off

**Comment by Guilouz** [comment]
> I believe Digant already added XY axis motor off button in #899. Mind if I update your icon to match that? It'll show XYZ off

Yes no problem ! But why only possibility to disable XY and not Z ?

**Comment by Subia75** [comment]
a question ,
i'm inexperienced in programming and i'm learning but i ask for help.
I tried to download 2 days ago and recompiled the firmware to the latest updates but I don't find the option to disable steppers motors, and also the icon in the BMP folder.
something wrong or there is a procedure to be done.
thank you

**Comment by bryan065** [comment]
Whoops, I was too slow for this. I'll update the icon in another PR

**Pull request merged**
