### PR TITLE
Clean up and remove duplicate codes

### PR DESCRIPTION
**Pull request by guruathwal**
- Rename **bed_en** to **heated_bed**, rename **chamber_en** to **heated_chamber**.
- Remove duplicate code & unused icons.
- Prevent error messages from closing in smart notifications to allow user interaction.
- Restore main menu icon layout

### CODE REVIEW

**Comment by guruathwal** [comment]
@digant73  Hi, the best way to do that is to detect the expected printer response and display it and ignore the extra responses at the time of processing them in **parseACK.c**. Blocking new messages will also block many other messages which may trigger while the earlier message is open.
Also, the EEPROM buttons are already available in parameter settings & custom menu, This need to be sorted out as well because we have very limited program memory and flash storage.

**Comment by digant73** [comment]
@guruathwal yes, I know neither the first nor the last message approach is the best solution. At the end, based on all the tests I performed, for the notification I preferred to display the first message (it provided the most important info). Maybe a configurable (at compilation time) parameter in configuration.h to choose the first or last message approch could be the best solution. Anyone will use the his preferred approch.
For the EEPROM I preferred to put that in the menu because is more intuitive, self explaining and easy to use. The restore and reset function on parameter menu could be misinterpreted as applied only to parameters and not to all system. I never used the custom menu.

**Comment by Msq001** [comment]
@digant73 
Hello, Can you confirm that your freeze problem can be solved in here https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/950 ?

**Comment by guruathwal** [comment]
the freeze on preheat menu must be due to #899 . as new settings variables were added but the  **PARA_SIGN** in flashStore.c was not changed. reflashing the config.ini should resolve the freeze.

**Comment by guruathwal** [comment]
#921  is a similar issue with custom gcodes showing in marlin mode

**Comment by digant73** [comment]
@Msq001 it seems it solved the problem. Just another feedback I received from some people. They said that there were (before your fix) freezes in the statusScreen menu when text displayed on the status bar needed scrolling. Could it be an issue to investigate?

@guruathwal I always install from scratch, so probably the problem was somewhere else. However, with the last main branch I'm not having any freeze

**Pull request merged**
