### PR TITLE
add config enable/disable external multi-serial

### PR DESCRIPTION
**Pull request by Msq001**
### Description
* Multi-Serials connected to ESP3D, OctoPrint, Other TFT, etc... Disable the serial port when it is not in use and floating, Avoid the serial port to receive the wrong data because of electromagnetic interference that cause communication interrupted and printing frozen

### CODE REVIEW

**Comment by kisslorand** [comment]
How do you enable only SerialPort3 (without SerialPort2)?
How do you enable only SerialPort4 (without SerialPort2)?
How do you enable only SerialPort3 & SerialPort4 (without SerialPort2)?
How do you enable all serial ports?

**Comment by Msq001** [comment]
> How do you enable only SerialPort3 (without SerialPort2)?

multi_serial = 2

> How do you enable only SerialPort4 (without SerialPort2)?

multi_serial = 4

> How do you enable only SerialPort3 & SerialPort4 (without SerialPort2)?

multi_serial  = 6

> How do you enable all serial ports?

multi_serial = 7


```
### Enable Multi-Serials
# Multi-Serials connected to ESP3D, OctoPrint, Other TFT, etc...
# Disable the serial port when it is not in use and floating
# Avoid the serial port to receive the wrong data because of electromagnetic interference
#   Options: [0: Disable all multi-serials,
#             1: Enable SERIAL_PORT_2,
#             2: Enable SERIAL_PORT_3, 3 = 1 + 2: Both enable SERIAL_PORT_2 and SERIAL_PORT_3,
#             4: Enable SERIAL_PORT_4, 5 = 1 + 4: Both enable SERIAL_PORT_2 and SERIAL_PORT_4,
#             etc...]

```

1 = Enable SERIAL_PORT_2 alone
2 = Enable SERIAL_PORT_3 alone
4 = Enable SERIAL_PORT_4 alone

3 = 1 + 2 = Enable SERIAL_PORT_2 + SERIAL_PORT_3 
5 = 1 + 4 = Enable SERIAL_PORT_2 + SERIAL_PORT_4 
6 = 2 + 4 = Enable SERIAL_PORT_3 + SERIAL_PORT_4 
7 = 1 + 2 + 4 = Enable SERIAL_PORT_2 + SERIAL_PORT_3 + SERIAL_PORT_4

**Comment by kisslorand** [comment]
That's great, it wasn't obvious for me. Now it's really personalisable for individual requirements.

**Comment by oldman4U** [comment]
How does a user know which serial port he has to activate for a certain connection on his particular TFT? Today some users have a problem to define the same baud rate in Marlin and TFT....

**Comment by guruathwal** [comment]
@oldman4U by looking at the back of the TFT.

**Comment by radek8** [comment]
> 
> ```
> ### Enable Multi-Serials
> # Multi-Serials connected to ESP3D, OctoPrint, Other TFT, etc...
> # Disable the serial port when it is not in use and floating
> # Avoid the serial port to receive the wrong data because of electromagnetic interference
> #   Options: [0: Disable all multi-serials,
> #             1: Enable SERIAL_PORT_2,
> #             2: Enable SERIAL_PORT_3, 3 = 1 + 2: Both enable SERIAL_PORT_2 and SERIAL_PORT_3,
> #             4: Enable SERIAL_PORT_4, 5 = 1 + 4: Both enable SERIAL_PORT_2 and SERIAL_PORT_4,
> #             etc...]
> ```
> 
> 1 = Enable SERIAL_PORT_2 alone
> 2 = Enable SERIAL_PORT_3 alone
> 4 = Enable SERIAL_PORT_4 alone
> 
> 3 = 1 + 2 = Enable SERIAL_PORT_2 + SERIAL_PORT_3
> 5 = 1 + 4 = Enable SERIAL_PORT_2 + SERIAL_PORT_4
> 6 = 2 + 4 = Enable SERIAL_PORT_3 + SERIAL_PORT_4
> 7 = 1 + 2 + 4 = Enable SERIAL_PORT_2 + SERIAL_PORT_3 + SERIAL_PORT_4

I also didn't immediately understand the logic from the comments in the config.ini file. Now it's clear.
So can you add a complete list of options with a description to config .ini, as you answered kisslorand?
Thank you

**Comment by Msq001** [comment]
@radek8 Hello, Please review https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1941/commits/27e97b363a8f463a8be84cc84787570a36a8cf24

**Comment by Msq001** [comment]
> How does a user know which serial port he has to activate for a certain connection on his particular TFT? Today some users have a problem to define the same baud rate in Marlin and TFT....

Maybe we need to make a document for this? The silk screen printing of some ports is blocked by the seat, and the sequence SERIAL_PROT_2, SERIAL_PROT_3, SERIAL_PROT_4 in the software is different from USART1, USART2, USART3 in MCU hardware. If there is a document, it is the best.

**Pull request merged**
