### PR TITLE
New icons for BLTouch and RGB controls in alternative icon theme

### PR DESCRIPTION
**Pull request by guruathwal**
Added new icons for BLTouch, RGB controls iand some other new options which needs icons in alternative theme

### CODE REVIEW

**Comment by arminth** [comment]
No fonts to be replaced on TFT24?

**Comment by guruathwal** [comment]
> No fonts to be replaced on TFT24?
I own a TFT35 v2 only. are your fonts not displaying correctly? Can you post photo of the screen?

**Comment by guruathwal** [comment]
> Loved your new font that was present in your pre-built binary @guruathwal . Unfortunately it wouldn't show when I build my own with your code. Are you reverting back to this 'Chinese' font?

Just Pushed the fixed font. Please check it out and share the opinion.

**Comment by thisiskeithb** [comment]
> Just Pushed the fixed font. Please check it out and share the opinion.

How'd you manage to fix this font and do you have a .sgfnt / source file for Ubuntu? 🙂I couldn't figure out how to use the SG Bitmap Font Editor to create fix the old ones.

**Comment by hapklaar** [comment]
> Just Pushed the fixed font. Please check it out and share the opinion.

Looks good!

**Comment by guruathwal** [comment]
> Just Pushed the fixed font. Please check it out and share the opinion.
> 
> How'd you manage to fix this font and do you have a .sgfnt / source file for Ubuntu? 🙂I couldn't figure out how to use the SG Bitmap Font Editor to fix the old ones.

I used font samples from this repository :
[https://github.com/Acenotass/BIGTREETECH-TFT35-V1.2/tree/master/firmware/Copy%20to%20SD%20Card%20root%20directory%20to%20update/TFT35/font](url)

The character position was shifted backwards by 31 in recent changes  and total character count is 95 according to my findings.
The Russian characters are removed from the new .fon file, because of which the Russian and Armenian languages are still having same problem even after using the original working file. 

**To make your fonts work again you need to do the following steps in SG Font Editor:**

**For TFT35:**
1. Go to : File > Doc Properties and set Symbol width to 12, Symbol height to 24, symbol count to 95.
2. Go to: File > Import and  import the original 'byte-ascii.fon' which is working with setting as show in screenshot below, 
font import setting
3. Open a new Sg Font Editor and import the font file which you want to use with Import setting same as above but set the character count to 256.
4. Now you need to copy and replace the characters one by one from the new font file to original font file. (CTRL + Left click to select a character)
5. After copying every character one by one, in the go to : File > Export and export with setting in screenshot below and set the file name to 'byte_ascii.fon':
export setting
6. Copy the file to font folder and update the font in TFT35.

**For TFT24 / TFT28**
Please note that I do not have a TFT24 with me so I cannot test it by myself. buy you can post the photo to help.
The character placement in font file for TFT24 / TFT28 are different from font file for TFT35 
1. Set the Doc Properties as below:
font size setting tft24_28
2. Go to: File > Import and  import the original 'byte.fon' which is working with settings as show in screenshot below:
tft24 import
3. Open a new Sg Font Editor and import the font file which you want to use with Import setting same as above but set the character count to 256.
4. Now you need to copy and replace the characters one by one from the new font file to original font file. (CTRL + Left click to select a character)
5. After copying every character one by one, in the go to : File > Export and export with setting in screenshot below and set the file name to 'byte_ascii.fon':
tft24 export
6. Copy the file to font folder and update the font in TFT24 / TFT28.


If you can not find any file which is working on TFT24 / TFT25 then you can try placing the characters similar to characters in file for TFT35.

Please post a reply if it works or not.

**Comment by thisiskeithb** [comment]
> Please post a reply if it works or not.

I'm working on some other firmware updates right now, but I'll report back. Thank you for including screenshots!

It'd be nice to change the default (Times) font with Ubuntu for all TFTs in the default theme, so I planned to put in a PR to get those updated once I could figure out how to edit the originals for TFT24 & TFT28.

> The Russian characters are removed from the new .fon file, because of which the Russian and Armenian languages are still having same problem even after using the original working file.

See https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/107. @bigtreetech How do you plan to handle Russian & Armenian languages?

**Pull request merged**
