### PR TITLE
Add Point 5 in Leveling (Center)

### PR DESCRIPTION
**Pull request by Guilouz**
Just add a fifth point (center) for manual leveling.

### CODE REVIEW

**Comment by Guilouz** [comment]
@digant73 I'm not sure about the syntax

**Comment by digant73** [comment]
> @digant73 I'm not sure about the syntax

What's your doubt?

**Comment by Guilouz** [comment]
> > @digant73 I'm not sure about the syntax
> 
> What's your doubt?

If my code is correct like that :

{infoSettings.machine_size_min[X_AXIS] + infoSettings.level_edge, infoSettings.machine_size_min[Y_AXIS] + infoSettings.level_edge},
    {infoSettings.machine_size_max[X_AXIS] - infoSettings.level_edge, infoSettings.machine_size_min[X_AXIS] + infoSettings.level_edge},
    {infoSettings.machine_size_max[X_AXIS] - infoSettings.level_edge, infoSettings.machine_size_max[Y_AXIS] - infoSettings.level_edge},
    {infoSettings.machine_size_min[X_AXIS] + infoSettings.level_edge, infoSettings.machine_size_max[Y_AXIS] - infoSettings.level_edge},
    {(infoSettings.machine_size_min[X_AXIS] + infoSettings.machine_size_max[X_AXIS]) / 2, (infoSettings.machine_size_min[Y_AXIS] + infoSettings.machine_size_max[Y_AXIS]) / 2},

**Comment by digant73** [comment]
> > > @digant73 I'm not sure about the syntax
> > 
> > 
> > What's your doubt?
> 
> If my code is correct like that :
> 
> {infoSettings.machine_size_min[X_AXIS] + infoSettings.level_edge, infoSettings.machine_size_min[Y_AXIS] + infoSettings.level_edge},
> {infoSettings.machine_size_max[X_AXIS] - infoSettings.level_edge, infoSettings.machine_size_min[X_AXIS] + infoSettings.level_edge},
> {infoSettings.machine_size_max[X_AXIS] - infoSettings.level_edge, infoSettings.machine_size_max[Y_AXIS] - infoSettings.level_edge},
> {infoSettings.machine_size_min[X_AXIS] + infoSettings.level_edge, infoSettings.machine_size_max[Y_AXIS] - infoSettings.level_edge},
> {(infoSettings.machine_size_min[X_AXIS] + infoSettings.machine_size_max[X_AXIS]) / 2, (infoSettings.machine_size_min[Y_AXIS] + infoSettings.machine_size_max[Y_AXIS]) / 2},

Ok, so you applied my suggestion at the end. You stated that you had some doubts on my suggestion so I asked you to explain your doubts

**Comment by Guilouz** [comment]
> > > > @digant73 I'm not sure about the syntax
> > > 
> > > 
> > > What's your doubt?
> > 
> > 
> > If my code is correct like that :
> > {infoSettings.machine_size_min[X_AXIS] + infoSettings.level_edge, infoSettings.machine_size_min[Y_AXIS] + infoSettings.level_edge},
> > {infoSettings.machine_size_max[X_AXIS] - infoSettings.level_edge, infoSettings.machine_size_min[X_AXIS] + infoSettings.level_edge},
> > {infoSettings.machine_size_max[X_AXIS] - infoSettings.level_edge, infoSettings.machine_size_max[Y_AXIS] - infoSettings.level_edge},
> > {infoSettings.machine_size_min[X_AXIS] + infoSettings.level_edge, infoSettings.machine_size_max[Y_AXIS] - infoSettings.level_edge},
> > {(infoSettings.machine_size_min[X_AXIS] + infoSettings.machine_size_max[X_AXIS]) / 2, (infoSettings.machine_size_min[Y_AXIS] + infoSettings.machine_size_max[Y_AXIS]) / 2},
> 
> Ok, so you applied my suggestion at the end. You stated that you had some doubts on my suggestion so I asked you to explain your doubts

No, not on your suggestion, a doubt on my syntax to integrate your suggestion.

**Comment by radek8** [comment]
there is a mistake, but it has been there before

{infoSettings.machine_size_max[X_AXIS] - infoSettings.level_edge, infoSettings.machine_size_min[X_AXIS] + infoSettings.level_edge},

right is

{infoSettings.machine_size_max[X_AXIS] - infoSettings.level_edge, infoSettings.machine_size_min[Y_AXIS] + infoSettings.level_edge},

**Comment by Guilouz** [comment]
> there is a mistake, but it has been there before
> 
> {infoSettings.machine_size_max[X_AXIS] - infoSettings.level_edge, infoSettings.machine_size_min[X_AXIS] + infoSettings.level_edge},
> 
> right is
> 
> {infoSettings.machine_size_max[X_AXIS] - infoSettings.level_edge, infoSettings.machine_size_min[Y_AXIS] + infoSettings.level_edge},

Which lines ?

**Comment by radek8** [comment]
image

**Pull request merged**
