### PR TITLE
Fix to display M117 messages in info area

### LINKED ISSUE #494: [Q] Can M117 commands issued from Octoprint make it to the status screen in touchmode?
I am using the TFT 2.4 on an SKR pro 1.1 connected to Octoprint on a RPI.
Any messages issued by M117 (e.g. percentage of print, layer number or anything else to be displayed via M117) are not making it to the the status screen in touchmode. XYZ coordinates, temperatures and fan percentages during printing on the other hand are displayed correctly.

What am I doing wrong!? Display is hooked up via TFT connector, EXP1 and EXP2.
Serial Port is configured to 6
Serial Port 2 is configured to 1

### LINKED ISSUE #1050: [Q] How to display M117 messages in touch mode info area on TFT35 E3 V3.0?
**Your question or details you need. Please describe.**
When in Marlin (12864 simulator) mode, M117 messages regarding progress etc are displayed on the last line of the screen. How do I get these to display on the Info Area when in touch mode. With the current firmware, the text "Ender-3 Ready" is always displayed.

**specify the device variant related to your question.**
TFT35 E3 V3.0.

**Additional context**
So far, I've only tested this while printing GCode sent via USB from OctoPrint, either as a print job or as terminal commands. The test displays in Marlin mode, but not in touch mode.
.

### PR DESCRIPTION
**Pull request by Guilouz**
Fix to display M117 messages send by Octoprint plugin like DisplayLayerProgress in info area.

resolves #494
resolves #1050

### CODE REVIEW

**Comment by oldman4U** [comment]
Hi Guilouz.

Could you please add

resolves #494 
resolves #1050

to your PR. This will close those two tickets related to your fix.

Thank you

**Comment by arminth** [comment]
I have tried the PR and it works!
Two things there:
It is mandatory to enable

#define HOST_ACTION_COMMANDS
#if ENABLED(HOST_ACTION_COMMANDS)
  #define HOST_PROMPT_SUPPORT
  #define HOST_START_MENU_ITEM  // Add a menu item that tells the host to start
#endif

in configuration_adv.h in Marlin!

I also found that the notifications received via M117 are not collected in the notification-window (if you tap on the notification, a list of all notifications pops up, which you can then clear. This list is empty even tough several M117 messages have been issued (and received).

Cheers
Armin

**Comment by Guilouz** [comment]
> I have tried the PR and it works!
> Two things there:
> It is mandatory to enable
> 
> #define HOST_ACTION_COMMANDS
> #if ENABLED(HOST_ACTION_COMMANDS)
> #define HOST_PROMPT_SUPPORT
> #define HOST_START_MENU_ITEM // Add a menu item that tells the host to start
> #endif
> 
> in configuration_adv.h in Marlin!
> 
> I also found that the notifications received via M117 are not collected in the notification-window (if you tap on the notification, a list of all notifications pops up, which you can then clear. This list is empty even tough several M117 messages have been issued (and received).
> 
> Cheers
> Armin

Yes it's normal, M117 messages are just info and not notifications.

**Comment by arminth** [comment]
OK. Didn't know that as until today, they never made it to my display! 😂

**Comment by Guilouz** [comment]
@bigtreetech You can merge it please.

**Comment by oldman4U** [comment]
Hello Guilouz 

Sorry to bother you but I wanted to know if you would be available for additional contributions now that the PR has been merged. Unfortunately I can not code but together with @Guilouz traffic-light and some other users we try to give this project a bit more structure. To be able to do so, we have to know the resources we have - so I wanted to ask.

Merci

**Comment by blueeagle69** [comment]
> **#define HOST_START_MENU_ITEM**

You don't need this.

**Comment by arminth** [comment]
And why was it not working without that?

**Comment by blueeagle69** [comment]
Haven't got a clue. I dont use that setting and M117 messages display on my tft.

**Pull request merged**
