### PR TITLE
Maker select v2

### PR DESCRIPTION
**Pull request by Wallaal06**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### CODE REVIEW

**Comment by traffic-light** [comment]
Woooow dude! You know you're changing the uniform material theme for tft35?

Are you sure?

@bigtreetech, this shouldn't be right. This will replace the unified theme

**Comment by traffic-light** [comment]
Oh. And you added you're personal config.

I don't know what you're trying to do here 🤔

**Comment by Wallaal06** [comment]
Sorry.  I just downloaded github desktop yesterday so I can keep my
firmware updated easier.  Im still trying to learn how it all works. I must
have done something that tried to put files on the the actual firmware.  Im
sorry about that.

**Comment by traffic-light** [comment]
Ah okay. No problem.
I was already thinking there was something like that..

Good luck with figuring out GitHub desktop :-)

**Comment by Wallaal06** [comment]
Thanks

**Comment by traffic-light** [comment]
@Wallaal06 Please remove this pull request with closing it ;-)

**Pull request closed without merging**
