### PR TITLE
MarlinBft - custom short (8+3) firmware name and bin output support

### PR DESCRIPTION
**Pull request by GeminiServer**
### Description

Since marlin supports the binary file transfer protocol. You can serial upload the TFT firmware to the tft sd card. Unfortuatly MarlinBft does not support long file names. 
We have no boot loader code of the BTT TFT firmware to adapt, change or expand the long firmware name to 8+3 one. 

Therefore, this work arround will do the trick. It's a bit dirty but it works:
1. Uploading the 8+3 file to the TFT SD-Card using Marlin Bft  (i.e.: B35V30.new)
2. Restart/reset the TFT - which will detect the 8+3 firmware name (B35V30.new) and renames it to the right long one. 
3. After a second reboot, the bootloader will detect the update long name firmware and it will be installed as known. 

@bigtreetech: If you also release the bootloader source code we can made the changes.  Or you adapt 8+3 firmware name requirements in to the bootloader code and release it ;)

A sample plugin which uses the Marlin Bft:
https://github.com/CharlesWillis3/OctoPrint-MarlinBft

### CODE REVIEW

**Comment by traffic-light** [comment]
But the images would be a problem I think (also the speed for the images ;-))

**Comment by GeminiServer** [comment]
@traffic-light - Jepp. Not for bitmaps. 😎
This is just for the Firmware. I think that the icons / bitmap files are not often updated. For partially bitmap updates could be useable but the filename could be a Problem.

**Comment by traffic-light** [comment]
@GeminiServer That's true.
And it's not that hard to place a sd card in the screen.

With this update it's possible to upload new firmware over the internet :stuck_out_tongue: 
(I hope that the speeds are improved. Otherwise it would take long to upload to sd-card (at least, that's what I think)

But that doesn;t take away: Good job!

**Comment by oldman4U** [comment]
Hello @GeminiServer.

Sorry to bother you but I wanted to know if you would be available for additional contributions now that the PR has been merged. Unfortunately I can not code but together with traffic-light and some other users we try to give this project a bit more structure. To be able to do so, we have to know the resources we have - so I wanted to ask.

Danke

**Comment by GeminiServer** [comment]
> Hello @GeminiServer.
> 
> Sorry to bother you but I wanted to know if you would be available for additional contributions now that the PR has been merged. Unfortunately I can not code but together with traffic-light and some other users we try to give this project a bit more structure. To be able to do so, we have to know the resources we have - so I wanted to ask.
> 
> Danke
@oldman4U - Sure, I would happy to provide support further. Keep in mind that all this is done by spare time ;)

**Comment by oldman4U** [comment]
This is great, thank you!

You are located in Germany, right? I am in Austria. So we probably have a very similar work - life balance situation, with way to little time for our hobbies;-)

It is my feeling that you like more to do new things and less bug fixing, right?

If you have time - there is one "issue" where it is not sure if it is a missing feature or (more likely for me) a bug. Please check #1135 where printing from onboard SD card delivers all the data like temp and elapsed time to the TouchScreen mode, but not the layer information.

Please let me know in case you have time to check this and also please let me know in case there is anything I can help you with.

Thank you

**Comment by oldman4U** [comment]
Hi.

Happy new year.

Just in case you are available for a new contribution - the issue I mentioned above is solved.

Thank you

**Pull request merged**
