### PR TITLE
This PR is fixing the bugs introduced by merging PR #1487

### PR DESCRIPTION
**Pull request by kisslorand**
### Requirements

MKS or BTT TFT

### Description

This is a bugfix for the bugs introduced by PR #1487.
The fixed bugs are:

- filament length not calculated when printing from remote host and from onboard SD
NoLength

- in some cases, prinintg from remote host and onboard SD, the file name is missing from the print summary
NoName

- other languages than English are not taken into account properly after print finished
PrintFinishLanguage

- in some cases, printing from remote host from onboard SD, after print finished cannot exit from the menu, screen freezes

https://user-images.githubusercontent.com/50251547/104843268-62dd9f80-58d2-11eb-8b01-749f4a45a2fb.mp4

- PR #1487 wrongly assumed that "File opened:" is received from Marlin only if printing from remote host and onboard SD, hence even if TFT initiated the print from onboard SD, TFT was informed that it's a remote that started the print (`infoFile.source == BOARD_SD_REMOTE`). This PR makes the TFT aware again if print was started from remote host or not.
- if the user embedded some filament data into the gCode and didn't wanted to have the filament length, its was still initiated and calculated (only if printed from TFT and onboard SD because of some before mentioned bug)
- duplicate code removed

### Benefits

Everyone

### Additional info

This PR does not include any extra popup, there's not user configurable parameter added.
Extra RAM usage: 0 (zero)
Extra flash usage: ~72 bytes

### CODE REVIEW

**Comment by kisslorand** [comment]
@AntoszHUN 
Please check the little change I made in the Hungarian language file. Thank you in advance.

**Comment by AntoszHUN** [comment]
> @AntoszHUN
> Please check the little change I made in the Hungarian language file. My intention was to make the file opening confirmation popup look better in case of very long filenames.
> Thank you in advance.

You shouldn't always vary with it. Then there would be no problem. Why wasn't it as good as it was? Now what should I look at?

**Comment by AntoszHUN** [comment]
I watched. Will be good. I'll test it and see if it gets into the master.

**Comment by kisslorand** [comment]
Thank you.

**Comment by kisslorand** [comment]
@bigtreetech 
Please consider merging this so other PRs will have a base without the bugs this PR fixes.

**Pull request merged**
