### PR TITLE
Add message for no SD card/USB disk detected.

### PR DESCRIPTION
**Pull request by guruathwal**
- Add a pop-up message for no SD card/USB disk detected to differentiate between detection errors and read errors.
- Replace `U_DISK` with `USB_DISK` and `U_DISK_SUPPORT` with `USB_FLASH_DRIVE_SUPPORT`.

### CODE REVIEW

**Comment by radek8** [comment]
@guruathwal 
You have added 2 lines to most translations, but only one in some (CZ, BR, AM, CA CN).
missing there:
STRING_USB_DISK_NOT_DETECTED

**Comment by guruathwal** [comment]
@radek8  thanks. fixed.

**Comment by radek8** [comment]
Behind the expression
STRING_USB_DISK_NOT_DETECTED
fill in the text alignment space in all translations.

**Comment by guruathwal** [comment]
already done.

**Pull request merged**
