### PR TITLE
Added Event LED + Portrait Mode for all TFT variants

### LINKED ISSUE #634: The TFT display does not support the progress LED.
Is it possible that the Printer Event LEDs feature will be included in the TFT display firmware at some point? Marlin knows. It also works nicely in Marlin Mode. But not in touch screen mode anymore. Do you know anything about this?

Hello! AntoszHUN

### LINKED ISSUE #1072: [FR] Smart RGB encoder control
It would be very useful to be able to have the encoder LED change colour based on the current printer state, like in marlin when using the touchscreen.

Example:
Idle: Off
Heater: from blue to red
Print: white
Completion: green
Idle: Off

### LINKED ISSUE #1178: [BUG] usb printing not able to control Neopixel PRINTER_EVENT_LEDS on tft35 v3 and poss other screens with usb drive ports
Once we get neopixels actally working (by changing from the default pin P1_24 to another pin on the skr 1.4 turbo) and rewiring things etc I now find that there is no way to use PRINTER_EVENT_LEDS !!! when printing direct from a removable usb drive. It seems that the only way to use them is by printing from the sd slot or by command line with direct connection.

printing from usb drive just ignores M190 Sxx.x that turns the neopixel string on & starts the neopixels changing from blue to violet and M109 Sxxx.x that changes from violet to red when heating the extruders, and when the print starts turns them white. I know Marlin 2x does not support the end of print green colour neopixels as it uses sdPrint.complete to trigger it but a little gcode tweak can fix that.
this is not a marlin problem, this is a Touchscreen tft35 v3 (and possibily other screens) problem as it works on other devices by other makers according to the bug reports on the Marlin git.

Printing from the sd slot on the tft35 v3 works fine and seems to send the M109 & M190 commands correctly

### LINKED ISSUE #1620: NEOPIXEL Sequential display for temperature change not working when print from SD card
**TOUCH SCREEN MODE**
When printing from SD card neopixel sequential display not working.
Cycle through colors at startup also not working.
Manual switch on neopixel IS working

MARLIN MODE it's working

Touch screen mode printing with octoprint it is working

CONFIG:
#define NEOPIXEL_LED
#if ENABLED(NEOPIXEL_LED)
  #define NEOPIXEL_TYPE   NEO_GRB   // NEO_GRBW // NEO_GRBW / NEO_GRB - four/three channel driver type (defined in Adafruit_NeoPixel.h)
  #define NEOPIXEL_PIN        PC7                      // LED driving pin
  //#define NEOPIXEL2_TYPE NEOPIXEL_TYPE
  //#define NEOPIXEL2_PIN     5
  #define NEOPIXEL_PIXELS     8                        // Number of LEDs in the strip, larger of 2 strips if 2 neopixel strips are used
  #define NEOPIXEL_IS_SEQUENTIAL                // Sequential display for temperature change - LED by LED. Disable to change all LEDs at once.
  #define NEOPIXEL_BRIGHTNESS 100              // Initial brightness (0-255)
  #define NEOPIXEL_STARTUP_TEST                 // Cycle through colors at startup

  // Use a single Neopixel LED for static (background) lighting
  //#define NEOPIXEL_BKGD_LED_INDEX  0               // Index of the LED to use
  //#define NEOPIXEL_BKGD_COLOR { 255, 255, 255, 0 } // R, G, B, W
#

used:
marlin 2.0.5.3
TFT35 /  3.0.26.x febr 4 2021
SKR mini v1.2

### LINKED ISSUE #1786: marlin neopixel Color cycle.
I connected neopixels to SKR 1.4 board, but in TFT mode the set color cycle that marlin performs during heating doesn't happen. it would be cool to have that. 

thank you

### LINKED ISSUE #2288: [BUG] Using the e-step tuning with an IDEX setup will always use Extruder 1 (T0) and not Extruder 2 (T1)
### Description

I have an Ender 3 Pro with the Ender IDEX motherboard, dual extruders etc. I also have the TFT35 E3. I've installed the 3.27.0 firmware and have updated the e-stop on extruder 1 (T0) with the (very nice) e-step "wizard". But when I select extruder 2 (T1) and press the "Extrude 100mm", it says active extruder T0 and not T1. So there seems to be a bug there?
### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**

**Actual behavior**

### TFT Firmware Version & Main Board Firmware details
TFT35 E3 V3 -  BIGTREE_TFT35_V3.0_E3.27.x

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.
[config.ini.CUR.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/7722358/config.ini.CUR.zip)

### PR DESCRIPTION
**Pull request by digant73**
**IMPROVEMENTS:**
* Added Event LED feature: A reworked/reviewed version of PR #1209 made by **traffic-light** (thanks for your work). A new param "**event_led**" was added in "config.ini" (and also available on Feature menu) to enable Event LED feature. If enabled and when printing from TFT SD / TFT U Disk, during heating the TFT periodically sets the printer's (neopixel) LED color and TFT's knob LED color, if any, according to the current nozzle and bed temperatures.
* Cleanup on last merged PR providing Portrait Mode firmware variant: No need to create a new target on "platformio.ini" for a Portrait Mode variant. Flag "**PORTRAIT_MODE**" can be enabled in "build_flags" to enable the generation of a Portrait Mode variant. Firmware releases for Portrait Mode will have suffix "**_portrait.bin**" (e.g. BIGTREE_TFT24_V1.1.27.x_portrait.bin).
* Added Portrait Mode support for all the TFT variants/resolutions: Resolutions 480X272 and 800X480 cannot be tested by myself (I don't have any TFT variant based on those resolutions (e.g. TFT43, TFT70 V3)). Feedbacks from users will be monitored/collected after the merge of this PR and changes/improvements will be applied on next PRs. See **TESTING FOR 272X480 AND 480X800 PORTRAIT MODE** section for the testing required

**BUGFIXES:**
* Reviewed layout for Mesh editor menu in order to work on Portrait Mode
* Fixed Numpad menu not open clicking on Infobox area on Portrait Mode
* Fixed #2288
* Minor bugfixes

**How Event LED feature works during a print (applied according to param "**event_led**" in config.ini):**
1) when starting a print from TFT SD / TFT U Disk, if param "**emulated_m109_m190**" in config.ini is set to:
   *) "**disabled**":
      1) heating is controlled by printer. The TFT cannot control the printer's (neopixel) LED during heating. It will control only the TFT's knob LED, if any
      2) if Event LED feature is enabled in Marlin fw, printer's (neopixel) LED color is controlled by the printer during heating
      3) TFT's knob LED color, if any, set to BLUE (if bed heated first) or PURPLE (if hotend heated first)
      4) TFT's knob LED color progressively set to RED when target temperatures are being reached

   *) "**enabled**":
      1) printer's (neopixel) LED color and TFT's knob LED color, if any, set to BLUE (if bed heated first) or PURPLE (if hotend heated first)
      2) printer's (neopixel) LED color and TFT's knob LED color progressively set to RED when target temperatures are being reached
      3) printer's (neopixel) LED color set to WHITE (to illuminate the print surface) when target temperatures are reached
2) TFT's knob LED color set to it's default color (param "**knob_led_color**" in config.ini) when target temperatures are reached
3) printer's (neopixel) LED color and TFT's knob LED color set to GREEN when print terminates
4) printer's (neopixel) LED color switched off when exiting from Printing menu
5) TFT's knob LED color set to it's default color (param "**knob_led_color**" in config.ini) when exiting from Printing menu

**How Event LED feature works during a PID (always applied (independent from param "**event_led**" in config.ini)):**
1) printer's (neopixel) LED color and TFT's knob LED color, if any, set to RED when starting a PID process from PID menu
2) if Event LED feature is enabled in Marlin fw:
   1) printer's (neopixel) LED color set to BLUE (if bed heated first) or PURPLE (if hotend heated first) when starting a PID process
   2) printer's (neopixel) LED color progressively set to RED when target temperatures are being reached
3) printer's (neopixel) LED color and TFT's knob LED color set to GREEN when PID process terminates or aborts
4) printer's (neopixel) LED color switched off when exiting from PID menu
5) TFT's knob LED color set to it's default color (param "**knob_led_color**" in config.ini) when exiting from PID menu

**TESTING FOR 272X480 AND 480X800 PORTRAIT MODE:**
In order to support portrait mode for the remaining resolutions 272X480 and 480X800, some info/feedbacks from users having TFT variants based on those resolutions (e.g. TFT43, TFT70 V3) are needed even after this PR is merged.
In particular it is needed to:
* Set display rotation values for 90° and 270° (e.g. set proper value in line "#define SSD1963_90_DEGREE_REG_VALUE  0x00  // TO VALIDATE") for LCD_Driver:
  * RM68042.h (used by TFT35 V1 and V1.1)
  * SSD1963.h (used by TFT43 V3, TFT50 V3 and TFT70 V3)
  * ST7789.h (used by TFT28 V3)
* Validate/test and/or change values for TFT resolution:
  * TFT_272X480.h
  * TFT_480X800.h

resolves #634
resolves #1072
resolves #1178
resolves #1620
resolves #1786
fixes #2288

**PR STATE:** Ready for merge

**Mesh Editor's layout in Portrait Mode**

other_5

### CODE REVIEW

**Comment by radry** [comment]
Did you check on actual hardware if portrait mode still works with these changes?

**Comment by digant73** [comment]
> Did you check on actual hardware if portrait mode still works with these changes?

yes. Part of this PR is to add support to portrait mode also for other resolutions/TFT variants. 320x480 resolution is now available (e.g. for TFT 35 V3 etc...).

**Comment by xPew** [comment]
@digant73 Does this feature only works when printing from the TFT? What is the limitation?

**Comment by digant73** [comment]
@xPew yes, it will be the equivalent of Event LED feature on Marlin applied printing from TFT. It still needs to be reworked

**Comment by Guilouz** [comment]
I have TFT43 and TFT70 if I can help.

**Comment by digant73** [comment]
> I have TFT43 and TFT70 if I can help.

thanks. Once the proper 90° and 270° LCD rotation values will be available you could test the portrait mode for TFT43 (if the icons disposal configured in TFT_272X480.h are ok or not). But first we need to wait for proper 90° and 270° rotation values.

@bigtreetech please could you let me know the proper rotation values for 90° and 270° for the following displays?
* RM68042.h (used by TFT35 V1 and V1.1)
* SSD1963.h (used by TFT43 V3, TFT50 V3 and TFT70 V3)
* ST7789.h (used by TFT28 V3)
In the above files, you will see the comment "// TO CHANGE"

**Comment by radry** [comment]
@digant73 
The roation values can be looked up in the data sheet of each controller chip. It's not always obvious how to set the values (because you have to set two bytes and there are 4 combinations possible. That's why testing on actual hardware is necessary.

**Comment by digant73** [comment]
> @digant73 The roation values can be looked up in the data sheet of each controller chip. It's not always obvious how to set the values (because you have to set 3 bits thus there are multiple combinations possible. That's why testing on actual hardware is necessary. Sometimes the datasheet is bad or wrong though.
> 
> RM68042 could be 0x2E and 0x2D (can't find datasheet, but when I follow the logic that other drivers use it should be that). SSD1963 could be 0x02 and 0x05

thanks. Waiting for a confirmation from BTT (having that HW)

**Comment by digant73** [comment]
> I have TFT43 and TFT70 if I can help.

I made some fixes in the code.
If/when you have some free time, please test the Portrait Mode on TFT43/TFT70.
You need to:
1) download my PR
2) compile the fw (as usual) but removing the initial comment symbol ";" at the beginning of the following line in Platformio.ini
   **;**  -DPORTRAIT_MODE=  ; uncomment here to enable Portrait Mode .bin firmware generation
3) the generated bin file will have the suffix "_portrait" to differenciate it from the standard Landscape Mode. Simply remove the suffix from filename
4) flash the fw providing also reset.txt file (it is needed to recalibrate the screen)

thanks!

**Comment by Guilouz** [comment]
I will try soon as possible.

**Comment by Guilouz** [comment]
@digant73 Can you confirm me, event led working only when Neopixel are wired on TFT or it's working when wired on motherboard too ?

**Comment by xPew** [comment]
Glad this PR got merged. I would like to test vertical GUI on my TFT 35 V3 E3. How can I enable this feature? Tried search for it, maybe I am blind but can you help me? :)

**Comment by radry** [comment]
@xPew 
It was described above: 

- compile the fw (as usual) but removing the initial comment symbol ";" at the beginning of the following line in Platformio.ini ; DPORTRAIT_MODE= ; uncomment here to enable Portrait Mode .bin firmware generation
- optional: the generated bin file will have the suffix "_portrait" to differenciate it from the standard Landscape Mode. Simply remove the suffix from filename 
- flash the fw providing also reset.txt file (it is needed to recalibrate the screen)

**Comment by xPew** [comment]
Oh I see now, thanks. I thought since the TFT24/35 is implemented I need to enable it elsewhere! :)

**Comment by oldman4U** [comment]
Maybe we should mention this in the ReadMe!?

Which headline should be used and maybe some additional information like the supported devices could help.

Could someone please provide everything and I will add it to the ReadMe.

**Comment by digant73** [comment]
> @digant73 Can you confirm me, event led working only when Neopixel are wired on TFT or it's working when wired on motherboard too ?

both. M150 is sent to motherboard. Furthermore, AFAIK if Neopixel is wired to TFT it will also be controlled as knob LED. So Ig the TFT provides a knob LED, the neopixel should be also affected

**Comment by Guilouz** [comment]
@digant73 Do you think it's possible to not to turn off leds after printing is finished (after print summary and leds lit in green). Maybe add an option in config.ini to keep lighting.

I use Marlin settings (LED_USER_PRESET_STARTUP) to light on led to white at startup but after each printing leds light off, it's rather boring.

**Comment by traffic-light** [comment]
Thanks for making the led thingy digant!

**Comment by digant73** [comment]
@Guilouz I would avoid that. Then someone else will ask to allow to select the LED color adding a new param

**Comment by Guilouz** [comment]
@digant73 This will also happen when exiting the PID menu, the leds are turned off instead of keeping the previous state.

**Pull request merged**
