### PR TITLE
New icon for update #2084

### PR DESCRIPTION
**Pull request by AntoszHUN**
New icons for update # 2084 have been created.

Two new icons have been added to the Hybrid Red Theme.

By name:
- printing_chamber.bmp
- status_chamber.bmp

The above mentioned icons are included for all display types.
TFT24, TFT28, TFT35, TFT43, TFT50, TFT70

Made by: AntoszHUN

### CODE REVIEW

**Comment by oldman4U** [comment]
👍🏻

Zs.Antal ***@***.***> schrieb am Mo. 2. Aug. 2021 um 21:16:

**Comment by Guilouz** [comment]
@AntoszHUN There is something wrong with all your TFT70 status icons no ? 

TFT43 : 
status_bed copie2

TFT70 : 
status_bed copie

**Comment by Guilouz** [comment]
Sans titre-1 copie

Here corrected icons : 
[icons.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6928062/icons.zip)

**Comment by AntoszHUN** [comment]
> Sans titre-1 copie
> 
> Here corrected icons :
> [icons.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6928062/icons.zip)

The icons are made by me. Anyone who doesn’t like it doesn’t have to use it. If there is a problem with the TFT70 status screen icon, use a different set of icons. It's just like that. But if you don’t like it that much, then I’ll unify it.

I do this for free. That's why it looks the way I want it to.

The TFT70 has a large display. Therefore, the status icon with a gray background looks much better.

**Comment by Guilouz** [comment]
Wooh keep calm… I thought it was a mistake since they don't match with the rest of the theme and compared to other screen sizes. It was just a proposal…

**Comment by AntoszHUN** [comment]
> Wooh keep calm… I thought it was a mistake since they don't match with the rest of the theme and compared to other screen sizes. It was just a proposal…

If there is a problem I will replace it. A new icon pack is also planned. For TFT70 displays only.

**Pull request merged**
