### PR TITLE
Add filament sensor type selection in config

### PR DESCRIPTION
**Pull request by guruathwal**
- Add filament sensor type selection in config to show only relevant options in settings.

Fixes: #1505

### CODE REVIEW

**Comment by guruathwal** [comment]
@oldman4U  Can you test this?

**Comment by oldman4U** [comment]
😮 YES I can! 🙏

**Comment by oldman4U** [comment]
Tested with smart filament sensor and it works great. Thank you Gurmeet.

Please merge

**Comment by Ari-SSO** [comment]
Please somebody can explain me why now are 4 options? 

**Before was (If I am correct):**
0=Ignore the filament runout sensor connected to TFT. So let marlin use the filament runout sensor connected to the mainbord (if it is not configured in marlin then the printer has not any filament sensor).
1 and 2 =Use filament runout sensor connected to TFT, if 1 is a Normal sensor, if 2 the is Smart sensor type

**Now:**
0 or 1=Normal filament runout sensor (0=off, 1=on)
2 or 3=Smart filament runout sensor (2=off, 3=on)

But you only have 3 possible state, the state _OFF (option 0 and 2)_ is redundat. 

May be im missing something, but now you have the same functional code than befero but much complex and large, for example:



**Before (One instruction needed: the _if_): **
      
      void loopBackEndFILRunoutDetect(void) {
      if (infoSettings.runout == FILAMENT_RUNOUT_OFF)          // Filament runout turn off
        return;

**Now (thre instructions needed: _and, not, if_):**
    
    void loopBackEndFILRunoutDetect(void) {
      if (!(infoSettings.runout & 1))   // Filament runout turn off
         return;   

I dont see any functional the difference with the previous code, please somebody can help me to see the functional difference if it exists?

Thanks!!!.

**Comment by guruathwal** [comment]
@Ari-SSO Earlier the setting in the TFT was toggled between three values (OFF -> NORMAL -> SMART). This was creating false triggers because to set the option to OFF it had to first set it to the wrong sensor type. 
Now the value in config is set to four different values to be able to identify the sensor type so that only the correct sensor ON values is toggled. Like, if set to 0 or 1 the sensor type will be NORMAL and on TFT it will toggle only between OFF and NORMAL. Similarly, if it is set to 2 or 3 then it will only toggle between OFF and SMART. The 4 options are provided to allow selecting the default state of the feature (Enable/Disabled) on the first boot.

**Comment by Ari-SSO** [comment]
Ah, Ok!. So the problem was the false triggers, then to set if in OFF mode, is necessary to know the correct sensor type.

you help me to understand the problem, so now i understand the solution.

Thanks you!!!

**Pull request merged**
