### PR TITLE
EXTENDED_CAPABILITIES_REPORT added to Readme

### PR DESCRIPTION
**Pull request by kisslorand**
Updated "Readme.md" with another general must have to be enabled option in Marlin.

### CODE REVIEW

**Comment by radek8** [comment]
So can you add it to both config.ini files as well?

**Comment by kisslorand** [comment]
Sure, thx for the tip.

**Comment by radek8** [comment]
Shouldn't you edit the other one too?
BIGTREETECH-TouchScreenFirmware\Copy to SD Card root directory to update\config.ini

**Comment by kisslorand** [comment]
As far as I remember it is done automatically by a Python script, it is copied to the "Copy to SD Card root directory to update" folder.

**Comment by radek8** [comment]
Ok

**Pull request merged**
