### PR TITLE
Add support for MKS GB boards.

### LINKED ISSUE #2391: [FR] New Artillery not flashing LCD on GD32F305
### Description

There some Artillery Genius PRO or X2 that are not able to flash the LCD firmware.

### Steps to reproduce

Try to flash as usual

**Actual behavior**

MKSTFT28.bin is not detected and the flash is not able to start

### Hardware Variant

It seems that the new microcontroller is based on GD32F305  - VERIFIED

### TFT Firmware Version & Main Board Firmware details

The bootloader is V3.0.4

### Additional Information

https://github.com/artillery3d/genius-pro-tft-firmware this firmware can be flashed without issue

@digant73 i'm not able to reproduce this issue because i have an older lcd but i have some user that can try some beta firmware.

### PR DESCRIPTION
**Pull request by ciotto**
### Requirements

To test this fix you need a MKS board with GigaDevice MCU (used on Artillery Genius Pro and other Artillery 3D printers). 

### Description

As you can see [here](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2391), the new versions of the MKS boards use GigaDevice MCUs.

We know that there are at least 2 versions of the board that use two different versions of the bootloader:

 - [x] TFT Controller v1.2. with bootloader V3.0.4 (tested)
 
TFT Controller v1.2

 - [x] TFT Controller v1.4 with [bootloader V3.0.5](https://github.com/ciotto/teardown/blob/master/artillery-genius-ttf-controller/binary/bootloader_3.0.5.bin) (tested without printer attached)

TFT Controller v1.4

### Benefits

Add support to new versions of the MKS board that use GigaDevice MCUs.

### Related Issues

- fix #2391

### CODE REVIEW

**Comment by digant73** [comment]
Related issue is #2391 not #2885. You have to use the following line to mark #2391 as fixed by this PR so #2391 will be automatically closed once your PR is merged:

fixes #2391

**Comment by digant73** [comment]
@ciotto if you have issues with serial communication it could be possible you need to apply the changes made in #2840 for the new GD MCU

**Comment by ciotto** [comment]
> @ciotto if you have issues with serial communication it could be possible you need to apply the changes made in #2840 for the new GD MCU. Eventually simply use the old implementation (that worked for you) and gradually apply all the not HW based PRs not yet merged in your repo (I don't know how you repo was aligned to this repo in the last months)

No, shouldn't be related, I applied these changes after the rebase (doesn't built without these).

I rebased and tested commit by commit and after some hours of work I found that the problem is on the "last" commit 😑 (156e04b).

I suspect that can be related to the changes on `os_timer.c` because if I comment the `OS_TimerInitMs` call on `HW_Init` I can see the screen.

**Comment by digant73** [comment]
See the bugfixes on GD TFT variants provided by #2885 just merged today

**Comment by ciotto** [comment]
LOL, I found the same issue 😑.

Now I can do some more deep tests.

**Comment by ciotto** [comment]
Ok, seems to work fine on both the known versions.

Ready for review.

**Comment by digant73** [comment]
@ciotto please consider my last review (new PR) on you repo

**Pull request merged**
