### PR TITLE
Error correction in the flow / dosing menu.

### PR DESCRIPTION
**Pull request by AntoszHUN**
I made a correction in the flow / dosing menu. Instead of the 1, 5, 10 percent selectable in the menu, 1mm, 5mm, 10mm icons appeared. I fixed this. 3 new icons for each display type. Registered in the appropriate icon_list.inc file. I also fixed these in the Speed.c file.

Hello, AntoszHUN

### CODE REVIEW

**Comment by GregSKR** [comment]
Looks like unified pictures are in classic menu folder and vice versa?
Also, you should change ICON_E_5_MM to ICON_E_5_PERCENT, line 14 in speed.c
`  {ICON_E_5_PERCENT,          LABEL_5_PERCENT},`

**Comment by AntoszHUN** [comment]
Those files are duplicate files. Their names are just different. See as you wrote. They work perfectly well. It was only because otherwise the system would write an error. And if you rewrite everything in the Speed.c file, it won't be good. Although I don't really understand what you wanted.

**Comment by AntoszHUN** [comment]
Oh, I understand what you wanted. End. I changed line 14! Thanks!

**Comment by GregSKR** [comment]
Sorry for my insistence, but they are not duplicate files, I can see unified icons in classic folders and classic icons in unified folders:
Sans titre-1

**Comment by AntoszHUN** [comment]
Something went wrong here. I put everything where it belonged. Someone confused this.

**Pull request merged**
