### PR TITLE
Beep when temp reached

### LINKED ISSUE #1166: [FR] Pre heat beep/tune/tone to acknoledge the set temperatures have been reached
Is it possible to add a beep tone or tones to give an audible prompt once a pre-heat bed & extruder temperature has been reached ??

I have the slowest heating hot bed on the planet and it can some days take up to 7 mins to get up to 100c then heat the extruder to 235c or there abouts depending on fillament type can be 8 + mins. To help reduce the waiting times I use a pre heat option that heats the bed to 100 and extruder to 160 and this can slice a couple of min off the waiting time. I have pid tuned the bed many times but its still slow as heck. (130W 24v Silicone heatpad on 4mm Aluminium bed with 3mm Glass on top of it)

### PR DESCRIPTION
**Pull request by kisslorand**
### Description

This PR adds an acoustic acknowledge that the desired temperature is reached, given it to be the nozzle, the bed or the chamber.
It is working only if the temperature is set on the TFT by hand or automatically (Load/Unload, Extrude. Preheat, Heat, etc). It's not active if a gCode sets the temperature. It's not active if you set the temperature on the terminal or by any external command.
~It is falling into the rule of "alert_sound" in the Config.ini.~
It makes distinctive sounds, depending on the temperature if it has fallen or risen to the desired one.

The detection algorithm has a hysteresis of 2 °C. 

### Fixes what?

Fixes #1166 and adds more.

### Additional info
If desired, it can be made to be separately adjustable to be on or off, only for nozzle, only for bed, only for chamber, only for nozzle and bed, only for nozzle and chamber, only for bed and chamber, for all three, only for rising, only for falling and any of these combinations.
It's not my idea, I had it like this on a previous custom FW.

### A few hours later...

It's been made configurable by user, it can be enabled or disabled in the "Config.ini" and Menu->Settings->Screen->Sound.
Default is ON.

### CODE REVIEW

**Comment by sarvenn** [comment]
Hi @kisslorand , nice idea.
+1

**Comment by traffic-light** [comment]
Thanks for duplicates....

**Comment by digant73** [comment]
Minor cleanup. As done for all the parameters description, in config.ini append "." at the end of your new param:

#  heater_sound: Enable/disable this to control acoustic feedback when temperature
#                 has reached the desired value on heaters (nozzle, bed, chamber)

**Comment by kisslorand** [comment]
> Minor cleanup. As done for all the parameters description, in config.ini append "." at the end of your new param:
> 
> # heater_sound: Enable/disable this to control acoustic feedback when temperature
> #_________________has reached the desired value on heaters (nozzle, bed, chamber)

Done. Thanks for letting me know.

**Pull request merged**
