### PR TITLE
Fix for missing icons in classic menu and minor bug fix for fan speed display

### LINKED ISSUE #578: [BUG] Icons missing from Classic UI/Theme
### Description

There are several missing icons when updating using the Classic Menu UI/Theme since the menus appear to only be built for the Unified Menu:

- CoolDown.bmp
- global_bed.bmp
- global_nozzle.bmp
- Heat_Fan.bmp
- Home_Move.bmp
- InfoBox.bmp
- MainMenu.bmp
- manual_level.bmp
- printing_bed.bmp
- printing_fan.bmp
- printing_flow.bmp
- printing_nozzle.bmp
- printing_speed.bmp
- printing_timer.bmp
- printing_zlayer.bmp
- status_flow.bmp
- status_speed.bmp
- StatusBed.bmp
- StatusFan.bmp
- StatusNozzle.bmp

Reset.bmp wasn't listed as "not updated", but it's not in the Classic UI/Theme folder 

### Steps to reproduce

1. Grab pre-built binaries from this repo for Classic Menu/UI
2. Update TFT using an SD card
3. Watch for errors at the end listing the missing icons in the list above

**Expected behavior**
Icons for Classic UI/Theme

**Actual behavior**
Missing icons for Classic UI/Theme

### Hardware Variant
All

### TFT Firmware Version & Main Board Firmware details
V.26/most current as of today

Tagging @guruathwal since these icons should be updated when updates are made to the Unified Menu. Note: The Unified UI icons can be copied over, but they don't fit the Classic UI theme.

Please don't forget about the Classic UI!

### PR DESCRIPTION
**Pull request by guruathwal**
- Minor bug fix for fan speed display when SHOW_FAN_ PERCENTAGE is turned off.
- use 'reset_value' icon for resetting values to default in the baby-stepping menu and probe-offset menu.
- Fix for preventing status screen icons update in the classic menu firmware.

Resolves #578

### CODE REVIEW

**Comment by guruathwal** [comment]
@thisiskeithb 
This will prevent searching for extra icons for the status screen only in firmware with **Classic Menu**.
but still, there is no way to prevent users from reporting ID 10 T errors when they update **Unified Menu** firmware with **Classic Menu Icons**. These types of errors will keep popping up because no one reads the full instructions.

**Comment by thisiskeithb** [comment]
> there is no way to prevent users from reporting ID 10 T errors when they update Unified Menu firmware with Classic Menu Icons. These types of errors will keep popping up because no one reads the full instructions.
 
There’s no need to be rude. I used the Classic UI and icons from the correct folder to test this issue on multiple displays.

**Comment by guruathwal** [comment]
@thisiskeithb I am not being rude.. If you find it rude them I am sorry for that.. but I am stated the fact... even you know this. 
 About the Classic Icon issue: it is because the classic icons are not up-to-date for current firmware. There are only two options either update the icon pack or use the Unified Icons

**Comment by thisiskeithb** [comment]
> I am not being rude.. If you find it rude them I am sorry for that.. but I am stated the fact... even you know this.

How else would you expect someone to respond if you called them an idiot? Not cool.

> classic icons are not up-to-date for current firmware. There are only two options either update the icon pack or use the Unified Icons

Yes. That’s what I said in the ticket I opened. 

Just because you don’t use them, it doesn’t mean we should abandon them. The Classic UI/icons are still being used, so it’d be nice if they were updated. If I had the skills to create them, I would.

**Comment by guruathwal** [comment]
@thisiskeithb I told it to you.. not told about you. Stop taking everything on your self. Why would I call you an idiot? I would be the idiot if I call you that.

**Comment by oldman4U** [comment]
Hello Guru.

I hope you are fine.

Since you committed this branch, the start screen of my TFT35 E3 misses some Icons. With the branch right before trim thisiskeithb, this is OK.

Could you please check.

Thank you

Screenshot 2020-05-01 at 07 46 30

**Comment by guruathwal** [comment]
@oldman4U  Yes I am Fine. The icon names were fixed in #619 by @rebel1 but I did not checked it at that time only TFT35 icons were renamed. This should now be fixed in #641.

**Pull request merged**
