### PR TITLE
Display Bilinear Leveling Grid

### PR DESCRIPTION
**Pull request by radek8**
Display Bilinear Leveling Grid

obrazek

### CODE REVIEW

**Comment by Guilouz** [comment]
I think this grid button would have a better place in the ABL menu, no?

**Comment by radek8** [comment]
> Myslím, že toto tlačítko mřížky by mělo lepší místo v nabídce ABL, ne?

It is not a problem

**Comment by traffic-light** [comment]
So, this should also work with ubl?

**Comment by radek8** [comment]
> So, this should also work with ubl?

I don't use UBL
You can try. Send the M420 T0 V1 command via the terminal
If you return a valid grid, then yes.

**Comment by traffic-light** [comment]
Ah. I placed it in slot 0. (It's a invalid mesh. So next time I will place it in slot 1

**Comment by Guilouz** [comment]
Can you update your PR with new change on leveling.c file please ? Thanks.

**Comment by blueeagle69** [comment]
> Ah. I placed it in slot 0. (It's a invalid mesh. So next time I will place it in slot 1

There's no need to move your mesh to a different slot.
Simply change the V1 to V0 at the end of M420 T0 V(slot)  😀

**Comment by radek8** [comment]
> > Ah. I placed it in slot 0. (It's a invalid mesh. So next time I will place it in slot 1
> 
> There's no need to move your mesh to a different slot.
> Simply change the V1 to V0 at the end of M420 T0 V(slot) 😀

OK

**Comment by Guilouz** [comment]
@radek8 There is still a conflict with the 'leveling.c' file located on the master.

**Comment by Guilouz** [comment]
@radek8 Another issue, I use 25 points for mesh leveling and not all values ​​appear, they are truncated.

It's not possible to show values elsewhere than in the terminal ? On a new page maybe ?

**Comment by radek8** [comment]
> @radek8 Another issue, I use 25 points for mesh leveling and not all values ​​appear, they are truncated.
> 
> It's not possible to show values elsewhere than in the terminal ? On a new page maybe ?

Unfortunately, I can't do that, I'm not a programmer
If anyone can do better, I'll close this PR

**Comment by bigtreetech** [comment]
Hello
Thanks for your work, If it can achieve this effect #288 is the best
This PR needs stay here until I finish this or someone submits a PR with a similar implementation

**Comment by radek8** [comment]
> Hello
> Thanks for your work, If it can achieve this effect #288 is the best
> This PR needs stay here until I finish this or someone submits a PR with a similar implementation

OK I understand that.
I wanted at least this to be available before sameone else does it better.

**Comment by traffic-light** [comment]
If no one else will be already making #288 look a like maybe I will start working on it next week.

**Comment by radek8** [comment]
That's great. I like to test on my printer :-)

**Comment by traffic-light** [comment]
Oh. My message wasn't saved.

I will place a draft of the functionality is coming there. Even if it's not ready at all ;) (that's where draft are for isn't it.)

But for now I hope that btt will respond to my email quickly and that I can receive a replacement verry soon.

It's easier with layouts and stuff to have a screen to test it and if it's usable.

**Comment by traffic-light** [comment]
The slow communication of bigtreetech through mail is just horrible... Still waiting for a response since monday...

(And then you want to make them to make their products better ....)

**Comment by digant73** [comment]
> If no one else is already/ will be making #288 look a like maybe I will start working on it next week. I can make some code but can't test it until I receive a replacement of my screen.. the one borrowed is back to its owner :-(
> Hope that the support of btt can help me little faster :-p
> (I know, they're pretty busy at the moment. Lots of emails)
> 
> But:
> Would be great to have it for my ubl.
> 
> It's the only reason why I need the marlin menu at this moment. And I would like to use the expansion ports for some self-made hardware.

Another feature highly requested by a lot of users is the MBL. That would complete all kinds of leveling (auto, manual and graphical grid).
That and the M600 support were features in my agenda but now my holidays terminated and I have not so much time to spend on dev. M600 support seems ready for the merge. So only MBL should be implemented

**Comment by traffic-light** [comment]
I will take a look at it. I neither have a lot of time.
So it will take some time.

**Comment by Guilouz** [comment]
Why this PR is closed ?

**Comment by radek8** [comment]
I'm sorry, but Bigtreetech refused to merge PR, conflicts with new PR are emerging. So there is no reason to keep PR up to date and active.

**Pull request closed without merging**
