### PR TITLE
ExtrusionMenu-Load/UnLoadToMoreMenu

### LINKED ISSUE #1423: [BUG] Unable to change filament during print
I am unable to change filament during print. 
I pause print. I do unload filament, load filament. I'm back in the main menu -> cannot resume print right now. I request print, it asks for continue. I select continue. It does not print I have to select resume, but ok. I resume and Z axis is completely messed - it resumes the print in completely wrong layer. 

Using commit 9148ffe5708ab59e0b5590a4b0e67a44d6bc47d1.

### PR DESCRIPTION
**Pull request by kisslorand**
### Requirements

BTT TFT or MKS TFT

### Description

- added Load/Unload menu to "More" menu during print (replaces Terminal which can be also found under More -> Machine menu)
- "Extrusion" menu overhauled (preheat option if nozzle too cold, "Heat" button instead of "Nozzle" if only one nozzle, question about cooling down when leaving the menu)
- during print Pause, no question about cooling when exiting Load/Unload or Extrusion menu
- Load/Unload button moved to Mainmenu and Extrusion button moved to Move menu, following @mehmetsutas's logic
- rearranged Move menu items

### Related Issues

Fixes #1423

### RAM & Flash impact

**RAM** ->0 bytes extra
**Flash** -> 304 bytes extra

### CODE REVIEW

**Comment by thisiskeithb** [comment]
There's now a GitHub action that will automatically compile & replace existing firmware binaries after a PR is merged or changes are committed directly to the master branch, so those are no longer needed and can be removed.

**Comment by Codel1417** [comment]
> There's now a GitHub action that will automatically compile & replace existing firmware binaries after a PR is merged or changes are committed directly to the master branch, so those are no longer needed and can be removed.

My action didn't previously check what repo it was generating binaries for, just the master branch.

**Comment by thisiskeithb** [comment]
> My action didn't previously check what repo it was generating binaries for, just the master branch.

The PR source wasn't from `master`, so I assumed they were added manually.

**Comment by kisslorand** [comment]
I never work on the master branch, I always create a new branch for every idea, fix, etc. The bin files were generated automatically by VSCode.
I made a commit with the bin files deleted but they still show up in github.

**Comment by oldman4U** [comment]
kisslorand

I guess you are not using the gcode file preview and therefore you do not care even a little bit how this affects other users which are using this function. But you can not change the firmware the way you would like it, without taking a bit care of others. Why you are not making a private version, where you can do whatever you want?

BabyStep

**Comment by kisslorand** [comment]
Beg your pardon? I do not care??? 80% of my work is bugfix and requested features implementation. Thank you!
What have I done this time? How could I upset you adding a feature without removing anything???
Anyway, I know, no good deed remains unpunished.

**Comment by oldman4U** [comment]
You added great things to the firmware and you fixed some painful issues, nobody wanted to fix. But you also removed existing features, just because you did not need it and you wanted to force your own solution.

So in addition to the Back button which opens the same window you get when you press the Print button on the main screen, there is now also a button labeled BabyStep, showing the preview of the printed element.

I wish you would see the benefit of working together, instead of doing what you believe is right, because it works for you.

**Comment by kisslorand** [comment]
What's the issue with babystep? Please read what I did in this PR.

**Comment by oldman4U** [comment]
There is nothing wrong with BabySteps itself, but with the combination. BabySteps has been in the main page and under Menu in case a user uses the preview function. This is far away from being even just a good solution, in fact it is a very bad solution, but still better than a BabyStep button which shows the preview.

I haven't tested THIS PR but the current build and my experience with you is, that it does not matter where and when I write you something, but that you do your thing without looking left or right. And I ask myself where this will end.

Again, you did great things which I can not do and you have my full respect for this. But this is not a one man show and working together seems not to be one of your favourite thing. Would be great if you could proof that I am wrong!

**Comment by kisslorand** [comment]
Can you please point out what is wrong with this PR?

**Comment by Codel1417** [comment]
im getting an idea for another pull request i might look into. an option to pin a button from a menu to the home screen so the location that babystep currently take up on the home screen is customizable

**Comment by kisslorand** [comment]
> kisslorand
> 
> I guess you are not using the gcode file preview and therefore you do not care even a little bit how this affects other users which are using this function. But you can not change the firmware the way you would like it, without taking a bit care of others. Why you are not making a private version, where you can do whatever you want?
> 

I do not have the slightest clue what is this all about.



> i dont see babystep being changed at all in this pr so o dont know what he is on about

Alcohol maybe?

**Comment by oldman4U** [comment]
In case I tell you, you do exactly the opposite. You never had a problem with destroying the work of others, why do you have a problem to change an existing button which is wrong or to change a landing page, so the button makes sense.

@Codel1417
I have a concept for an improved interface which is based on the current design, but has some new elements which would have to be implemented to make the whole thing work. Technically it is possible to do it, but I am sure it is a lot of work. It has custom buttons at the main page: 

[Pre-Print Main Page.pdf](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5761033/Pre-Print.Main.Page.pdf)

**Comment by kisslorand** [comment]
> In case I tell you, you do exactly the opposite. You never had a problem with destroying the work of others, why do you have a problem to change an existing button which is wrong or to change a landing page, so the button makes sense.
> 
You keep missing to explain what is wrong with this PR. Cheers!

**Comment by oldman4U** [comment]
Gurmeet, the person who wrote most of the TFT firmware, supervised the development. It works from 24 up to 35 and with the current "design" by just making the buttons wider, it also works for all the bigger screens. There is a little interface design description and a new navigation tree, which allows to reach ALL functions with a maximum number of three clicks. The main screen can always be reached with a single click, does not matter where you are. In addition there are screens which are currently not available and I have been working on designs to fit the different aspect ratios better. There are also examples for a second nozzle and a heated chamber, things I do not own.

One thing more. I am not ill and I am also not drunken, but I have another opinion than you. I would prefer to keep this conversation on a respectful level. Thank you

**Comment by Codel1417** [comment]
@oldman4U is this an in progress design?

**Comment by oldman4U** [comment]
The design is available for all pages of the TFT35 resolution using 480x320. From this point on it is math to adjust it for other resolutions. What's missing from my side are the buttons itself for all resolutions. Gurmeet started with the implementation but has no time anymore. The first step is to remove the echo window from the main screen and to add the lower bar. To be able to remove the echo window he added the ability to see the last three echo notifications in an extra window which is the button in the lower left corner. This is where it stopped.;-(

**Comment by kisslorand** [comment]
> 
> One thing more. I am not ill and I am also not drunken, but I have another opinion than you. I would prefer to keep this conversation on a respectful level. Thank you

I am glad to hear your health is in a good shape and you are sober. No one asked about your health nor nobody said that you are drunk but it's nice that you shared with us your well-being. (Please do not put words in my mouth I never said, it's disgusting.)
How ironic is that the same person who started to throw mud and spitting on me asks for respect...
I asked multiple times what is wrong with this PR so I can fix it. You were so respectful that you didn't care the slightest amount to explain what's bothering you with this PR. It was more comfortable to spit more. Yeah, you really are the definition of respect itself.

I am asking again, what is wrong with this PR? Please provide that detail so I can fix it.

> kisslorand
> 
> I guess you are not using the gcode file preview and therefore you do not care even a little bit how this affects other users which are using this function. But you can not change the firmware the way you would like it, without taking a bit care of others. Why you are not making a private version, where you can do whatever you want?

What is this "respectful level" all about? What are you even talking about? It is addressed directly to me, accusing me about something that I do not have the slightest clue. Would you please show us how respectful is your level and explain what have I done in this PR and how do I "do not care even a little bit how this affects other users which are using this function"?
The screenshot you provided was like that when I first installed this FW to my TFT, before I made any PR. 
So, again, what is that awful thing I've done?

Babystep, file preview with babystep label, Back were there during print since I first installed this FW to my TFT. Babysteps and More were removed in a later PR but only AFTER print is finished. As @mehmetsutas mentioned:
"Having links to babystep and more menus are useless. When print is finished what can a user do on those menus. Also you say you should design for dumbest user, so users should not have such an option."

> I haven't tested THIS PR but the current build and my experience with you is, that it does not matter where and when I write you something, but that you do your thing without looking left or right. And I ask myself where this will end.

Yeah, you haven't tested it but it must be wrong because it is made by me.  Your sought respect is  bursting with abundance.

In case you missed (again) my request, please explain what is wrong in this PR so I can fix it? Please let me know the awful thing done in this PR that led you to cover me with such an amount of filth.

**Comment by digant73** [comment]
@kisslorand please on extrude.c apply your changes starting from my file in my PR. I changed some indentation.

@oldman4u Overall it seems to me this PR simply makes the load/unload menu available during a print without sacrifacing other features. So it is should be ok. If babystep or other features were removed, I will be the first one asking to revert the changes

**Comment by kisslorand** [comment]
@digant73 
Is it PR #1459? If yes, than it's done.

**Comment by digant73** [comment]
Yes it is. Good

**Comment by kisslorand** [comment]
So, after the circus where @oldman4U  "respectfully" showed us his true colors by his pointless piss contest out of the blue, things can move on to some beautiful prints.

If no one else (than @You_Know_Who) finds any problem with this PR, it can be merged peacefully. 

P.S.: NO, the things introduced in this PR are NOT user selectable, there is NO adjustable thing in config.ini nor in parameters settings. There's NO popup, there's NO info that can/could/should be seen from "a certain distance". Nothing was removed, it's an extra that you can use if you wish or not, that's the only option.

**Comment by oldman4U** [comment]
Following the advice of a good friend, I will not stretch this even further. But maybe others want to know what kind of person you are.

Regarding ill-founded. Please see #1359
Regarding respectful behaviour: "Alcohol maybe? I never saw him this incoherent..."

@digant73 Thank you for checking. It is all good.

**Comment by kisslorand** [comment]
> Regarding respectful behaviour: "Alcohol maybe? I never saw him this incoherent..."

I was trying to find an excuse for you. Since you stated that you were sober, I cannot find any excuse why you were sh**ing
on my face.

> Following the advice of a good friend, I will not stretch this even further. But maybe others want to know what kind of person you are.
 
Good excuse to not explain what is your issue with this PR. Are you women or a man? If you're a women, you're excused, understood. That's what women do...

**Comment by oldman4U** [comment]
So you are also a sexist....

**Comment by kisslorand** [comment]
Yes, I prefer women. :)

**Comment by oldman4U** [comment]
For all of you reading this.

I am really sorry

**Comment by kisslorand** [comment]
Yeah,  you should!

**Comment by Codel1417** [comment]
i hope when btt gets around to reviewing this after they accept/reject the pr the comments are locked

**Comment by kisslorand** [comment]
It will not stop @You_Know_Who to spit on me in the future.

**Comment by kisslorand** [comment]
@bigtreetech 

This is ready to be merged, no bugs related to this PR were reported nor found.

**Pull request merged**
