### PR TITLE
fixed Marlin mode for STM32F10x (bug #933) + cleanup

### PR DESCRIPTION
**Pull request by digant73**
BUG FIXES:
* Fixed bug #933. Marlin mode was not working on STM32F10x due to wrong queue usage in MarlinMode.c
   Now the queue for Marlin mode and new HD44780 simulator are fully handled on SPI_slave.c (as it was prior the the last merge) and HD44780.c for both STM32F2_F4xx and STM3210x. MarlinMode.c simply invokes a function on SPI_slave or HD44780.c to retrieve the data from the proper queue

IMPROVEMENTS:
* BabyStep.c, MachineSettings and ZFade menu: "save icon" and related save function are not displayed/available in case EEPROM support is not provided by the underlying Marlin FW

CLEANUP:
 * FeatureSettings.c, popup.c and Selectmode.c: converted tabs and adjusted indentation

### CODE REVIEW

**Comment by bigtreetech** [comment]
Hello, I have tested the screen of BTT TFT series. The LCD 2004 / 12864 is in normal working state.
Since 2004 and 12864 can only exist one at a time, I hope to use the same memory (queue) to process 2004 / 12864 in order to keep the program concise.
Does the problem of #933 only exist in MKS TFT?

**Comment by Msq001** [comment]
Hello, #951 should fixed Marlin mode problem,  please confirm. If it's ok, please synchronize your PR.
Thank you very much.

**Comment by digant73** [comment]
hi @bigtreetech, @Msq001
Yes, I agree to use only one queue, but it should be better to perfecly decouple MarlinMode from SPI_slave and HD44780.
In this moment we have HD44780 and SPI_slave depending eacho other and also depending on MarlinMode (for the queue). Furthermore HD44780 depends on SPI_slave for the interrupt handler. Plus all the hd44780 code present in the interrupt handler (in spi_svalde.c) should be moved totally on HD44780.c as I did in my code).
Also the queue handling can be managed in spi_slave and hd44780 (as I did providing the xx_getData function.
spi_slave and HD44780 are API, so in my opinion all the implementation must be confined on there.
spi_slave  is a general API that can be used not only for Marlin mode. With the current implementation spi_slave can be used only for Marlin (the queue is instanciated in MarlinMode.c).
If you agree, I can simply define a new file e.g. called CircularQueue.h under HAL directory and spi_slave.c and HD44780.c will simply include that file (instead of MarlinMode.h). On spi_slave.c and HD44780.c I will provide a function to set the queue that will be internally used. It will be responsibility of the utilizer (e.g. MarlinMode) to pass the queue pointer to spi_slave or HD44780 and to deallocate the queue (so the current implementation on MarlinMode remains the same).
With that approach spi_slave, HD44780 API and MarlinMode are perfectly decoupled. I can continue to use spi_slave even for other scopes.
If you agree I can proceed with that adjustement. Please let me know

**Comment by bigtreetech** [comment]
I agree with you, Thank you for your work!

**Comment by digant73** [comment]
> I agree with you, Thank you for your work!

Thanks. I'm going to make the changes

**Comment by digant73** [comment]
> I agree with you, Thank you for your work!

Ok, I merged my improvements on spi_slave, HD44780 and MarlinMode.
Now a pointer to circular queue must be provided in the xxInit (for spi_slave) or xxConfig (for HD44780) functions. The circular queue is defined under /HAL/CircularQueue.h. Just a little bit change was made in the buffer type. "data" field is now an array of uint8_t and not a pointer to uint8_t. So now in MarlinMode.c , it is enough to simply instanciate the circular queue object and passing its reference to spi_slave or HD44780. In spi_slave and HD44780, I always intialize the queue indexes (index_r, index_w and count) before using the queue. I suspect that in the old version the queue indexes could be used with dirty values.
I also made cleanup on spi_slave, HD44780 and MarlinMode, the usual tabs removal, comments adjustment and aligned functions (it allows a better comparison with tools such as "beyond compare" etc...).
For me the PR could be merged (after your testing).
thanks

**Pull request merged**
