### PR TITLE
Processing of base64 encoded PNGs for thumbnails (like generated from PrusaSlicer)

### LINKED ISSUE #1238: Thumbnail visibility for Prusaslicer
Hi Guys,

first of all, many thanks for your effort.

The Cura plugin for the thumbnails is great, but I actually use the Prusaslicer. Is there such a plugin or something for this one?

According to the Internet, you can (like the Mini) add the item Thumbnail to the corresponding printer profile via Prusaresearch.ini.
But I can't get the thumbnail to be displayed. can someone help me?
Hardware:
SKR 1.4 Turbo and Btt TFT35 V3.0

friendly greetings

### PR DESCRIPTION
**Pull request by CyberDeck**
### Description
This PR introduces proper handling of base64-encoded PNGs for gcode thumbnail preview, like the *stock PrusaSlicer generates without any post-processing scripts*.

In addition the thumbnail preview can be configured into three different flavors:

* **Classic**: Basically the current comment style for post-processed gcodes with fixed file locations for the thumbnails.
* **RGB565 bitmap**: Thumbnail encoding is a raw stream of uint16's with RGB565 data encoded as hexstrings. Like the current / classic approach. However, the thumbnail must not be positioned at a specific location. Thumbnail data is identified by the gcode comment `; bigtree thumbnail begin <WIDTH>x<HEIGHT>`. Example:
```gcode
...
; bigtree thumbnail begin 95x95
; DEADBEEF... thumbnail data
; bigtree thumbnail end
...
```
* **Base64+PNG**: Stock PrusaSlicer can generate these thumbnails. Just configure e.g. for the TFT35 to generate 95x95 thumbnails and it will be show on the TFT.

If the firmware is configured to preview **Base64+PNG** it will try to show **RGB565 bitmap** and **Classic** as well (it is only slight flash+ram overhead). If it is configured for **RGB565 bitmap** it will show **Classic**, too. That means that this PR is fully compatible to the way it is currently working.

**But no joy without pain:** **Base64+PNG** is computational expensive (from both memory and runtime). My TFT35 needs approx. 110ms to preview the thumbnail, which I consider acceptable from a UI perspective. However, the included [PNGLE](https://github.com/kikuchan/pngle) library puts additional ~43KB RAM on the table. I modified the library slightly, so that this 43KB is statically allocated and during PNG decoding rougly about 1KB HEAP is utilized.

But this PR is aware of this memory requirement and downgrades a configuration setting for a low RAM device (i.e. <96KB) automatically to the **RGB565** setting.

During my endeavor of implementing this PR on my TFT35 I added some more fine-grained serial debugging capabilities which are included. Additionally, there was a linker script _bug_ for the STM32f2xxx devices where the stack was *NOT* placed to the proper "end of RAM" location.

### Benefits

1. *Stock PrusaSlicer thumbnail preview*s without running any post-processing scripts.
2. *Bugfix of linker script for STM32F2xxxx* with wrong stack location.
3. Fine-grained control for serial debugging.

### Related Issues

Resolves  #1238

### CODE REVIEW

**Comment by oldman4U** [comment]
Very cool. Thank you

**Comment by digant73** [comment]
@CyberDeck can you attach some sample files for testing?

**Comment by CyberDeck** [comment]
@digant73: Here are some [testfiles.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6603113/testfiles.zip):

- **PNG.gcode**: Generated with a stock PrusaSlicer. I just set under _Printer Settings_ the _G-Code Thumbnail_ setting to `95x95` for my TFT35:
 Thumbnail Setting
- **RGB565**: This includes the bigtreetech thumbnails in 95x95 resolution generated with the _usual_ Python post-processing script (only the raw RGB565 data - not the resolution header). 
- **RGB565+PNG.gcode**: Includes both as an example.

The following thumbnail should be shown:
 #base64


(All G-Code files have been stripped to save some space...)

**Comment by CyberDeck** [comment]
I forgot to update CONFIG_SUPPORT and CONFIG_VERSION and updated the PR accordingly with a fourth commit.

**Comment by oldman4U** [comment]
Guten Morgen. Do you believe a short description of the things you have to do in the slicer should be added to the readme?

Could I use your screenshot for this?

**Comment by CyberDeck** [comment]
@oldman4U yes, you can use the screenshots for this.

As a possible starting point for such a short description I had some initial ideas incl. some additional images: [proposal.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6614754/proposal.zip)

**Comment by CyberDeck** [comment]
**Warning!** One should not try out this PR prior to commit 7d6b6d9. It may brick your TFT if you enable the `DEBUG_x` in `Configuration.h` with bad config settings.

During serial debug initialization it print's a string out. However, if one does not have multi-serial enabled in the `config.ini` and flash this, the `dbg_print` stops in an endless loop. 

This initialization is done before running updates from SD so this technically bricks your TFT as mine is now bricked. I will further investigate in this after I received a ST-LINK clone to unbrick it...

**Comment by oldman4U** [comment]
You make me unemployed;-)

Will add it asap.

Cura 4.9.1 crashes on my computer running macOS 10.15.7 while saving using the BTT 3D. Have to try it with other versions of Cura and OS to see which one broke it,

Thank you

**Comment by oldman4U** [comment]
Please check PR#1984 which includes the new ReadMe. Thank you

**Comment by CyberDeck** [comment]
PR #1984 look good for the embedded thumbnail part.
I recognized in the section for MarlinFW's `Configuration_adv.h` that you removed `AUTO_REPORT_POSITION` as a required setting. Is that not needed anymore?

**Comment by sarvenn** [comment]
@CyberDeck hi,
Have you checked effgarces solution here? May be this script may influence your current study. I wanted to share for that purpose.
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1238

I use PrusaSlicer and TFT35. The script that he wrote and shared works perfect.

https://github.com/effgarces/Biqu-Thumbnail-Generator/releases/tag/0.01

**Comment by CyberDeck** [comment]
Hi @sarvenn,

I use the original python post-processing scripts from effgarces, too. 
The script or the whole approach of having fixed storage location within the file has two downsides regarding flexiblity:
- If I modify the post-processed file manually (or by another post-processing script), which modifies the end of line signature from "windows style" to "unix style", the fixed offsets are wrong.
- The post-processing script moves the first comment line from Prusa-Slicer down which results in a failure if you try to reload the file back into PrusaSlicer.

Therefore, the approach of loading the Base64+PNG thumbnail comments is much more flexible.
But even if you enable Base64+PNG, this PR still tries to load thumbnails from the fixed offsets if the file was post-processed, which means it is fully compatible.

**Comment by sarvenn** [comment]
Great! I was hoping someone would fix this issue. I even raised tickets at PS and Superslicer repos as well. I also requested btt to change the fw to be compatible with PS. Good to see your effort now. Thanks. Watching and waiting for your study to finish. Then I will close my other tickets and give info about your update.

**Comment by oldman4U** [comment]
> PR #1984 look good for the embedded thumbnail part.
> I recognized in the section for MarlinFW's `Configuration_adv.h` that you removed `AUTO_REPORT_POSITION` as a required setting. Is that not needed anymore?

I have not removed it and it is still there in the first section. Please check again and let me know.

Thanks

**Comment by bigtreetech** [comment]
Hello，Thank you very much for your excellent work. 
The parsing of PNG increases the flash usage by about 15KByte, so I changed the default `THUMBNAIL_PARSER` setting to 0 to reduce the flash usage.

**Comment by sarvenn** [comment]
> Hello，Thank you very much for your excellent work.
> The parsing of PNG increases the flash usage by about 15KByte, so I changed the default `THUMBNAIL_PARSER` setting to 0 to reduce the flash usage.

Is it possible to add this option to config.ini?

**Comment by oldman4U** [comment]
Hello BTT.

What is the plan to allow TFT's with more memory to activate more features and vice versa? Wouldn't it be good to have a similar method like Marlin or to make certain features only available for certain TFT's?

**Comment by CyberDeck** [comment]
> I will further investigate in this after I received a ST-LINK clone to unbrick it...

Successfully unbricked my TFT35. Quite an easy job *if* you have an ST-Link (clone) available. 
Commit 7d6b6d9 fixed the issue: TFT is still booting up and is able to be reflashed over SD if the setting is wrong. Last commit 
93725af includes some comments about the behavior in Configuration.h.

> I have not removed it and it is still there in the first section. Please check again and let me know.

@oldman4U: Correct. I missed it in the first section and `AUTO_REPORT_POSITION` is included.

> Is it possible to add this option to config.ini?

@sarvenn: You may change the behavior with config.ini (i.e. only parse the usual way or enable to parse Base64+PNG). However, to successfully use it the base64 decoder and PNG decoder needs always to be included withing flash (+15KB) and memory (+45KB) which is not possible on all TFT platforms. 
However, the Configuration.h setting is agnostic to the RAM sizes and downgrades the possible parsing options if not enough memory size is available.

From my humble point of view, we are ready to go!

**Comment by sarvenn** [comment]
> which is not possible on all TFT platforms.

I hope TFT35 is OK to work properly 🙏🏻

**Comment by sarvenn** [comment]
Hi @CyberDeck ,

Could you please look to this issue? #2300 .
I was using thumbnail parser as classic (setting 0-default in configuration.h), so I was using the standalone script with my PS 2.3.3 ( https://github.com/effgarces/Biqu-Thumbnail-Generator/releases/tag/0.01 ).
Then I updated my slicer to 2.4.0 beta1. Standalone auto py to exe file did not work with PrusaSlicer 2.4.0. Meanwhile I compiled a new firmware for my TFT35 choosing the thumbnail parser to Base64 PNG (setting 2).
Then I tried the files on my TFT35. I noticed that babystep icon is not replaced with thumbnail icon in printing menu. My old files with standalon script modified gcode files had no issue at all.
Now effarges updated his standalone script exe. I tried it. Those gcode file replaces the babystep button in printing menu.

But there is a common issue for both PrusaSlicer default gcodes and the ones modified with post processing script, when I open the TFT directory, all the thumbnails are visible as expected but when I go to next page and turn back to previous page again, thumbnail icons are not visible, default gcode icon is replaced the thumbnails. It doesn't matter if I go back and forth between pages, when I go back and enter to directory again thumbnails are visible again, or if I click on a file after thumbnail dissappeared, and decline the printing prompt pop up, page is refreshed and thumbnails are alive again.

**Pull request merged**
