### PR TITLE
Updated extruder tuning, max brightness on messages and more

### PR DESCRIPTION
**Pull request by traffic-light**
## short description ##
I've updated the extrude tuning tool and did some small changes

## What is changed ##
 * The tune extruder menu is updated. See _what is the tune extruder menu capable of_
 * When there is a toast, popup or a sd-card/ USB-stick is removed/ placed the screen will be set to max brightness
      > The reason I did this is because it's sometimes hard to see it, when there is a pop-up or something else, on the idle brightness.
      > Yes. When you.re not near the screen you will always miss it ;-)
      >
      > For now it's hard coded. But maybe it's handy to place a option in the feature menu to switch this on/ off
 * Added the roatary knob to the PID tuning menu for changing temperatures

## what is the tune extruder menu capable of ##

* In the first screen you can set the temperature you want
* When the temperature is reached you can press extrude
* First you will be informed to mark 120mm
* After marking 120mm there will be 100mm of filament extruded
* When the user notice that it's done he can measure the length.
* When the length is correct the tune extruder menu will be closed. (hot end will cool down
* When the length is incorrect the user can give the length in mm. New e-step will be automatically calculated

I think I will ad in another version a check if you have more then 1 extruder. When there is more then one extruder you can select which one should be extruding and calibrated.

I tested this on a screen that i borrowed from a friend (kudos for him :-) ). So it's tested now.

## feedback is welcome ##
I want some feedback on my code. That's why I marked it  as  a draft.
This is my first big adjustment in the firmware. So I like to hear from you guys what you think.
Especially those who are already working in this code for a long time.

(@guruathwal @radek8  @Msq001 @digant73  you guys know a lot about the firmware and the way it should look like/ layout (syntax?))

Oh. And I changed the uint8_t in language.h and c to 16_t
8_t is not enough anymore -_-'

I hope that you guys can give me some good feedback.
When you edited some code you can also make a pull-request on my git if you would like that it will be merged.
For now, I go to my bed. It's 4:18 AM :fearful:

## Some pictures ##
image
Cold extrusion prevented:
image
image
Temp not reached yet:
image
Tell the user to mark 120mm
image
After pressing extrude this message appears:
image
When pressing the button "tuning" the menu to adjust the steps appears
image
Adjusted steps:
image
After pressing the save button:
image

I noticed that, after pressing the save button, the e-steps disappears. So I've got to fix that ;-)
I already edited the decimal precision by old and new e-steps to .2

### CODE REVIEW

**Comment by traffic-light** [comment]
I made some pictures of the menu:
image
Cold extrusion prevented:
image
image
Temp not reached yet:
image
Tell the user to mark 120mm
image
After pressing extrude this message appears:
image
When pressing the butten "tuning" the menu to adjust the steps appears
image
Adjusted steps:
image
After pressing the save button:
image


I noticed that, after pressing the save button, the esteps disappears. So I've got to fix that ;-)

**Comment by digant73** [comment]
The extrude 100 was originally added just as a simple gcodes invocations without the need to add an extra menu to handle pre heating. Pre heat menu was/is already present so the extrude 100 relies on preheat menu as pre-requisite. Extrude 100 was initially provided because extrude menu was not capable to set desired low speed. If it is possible now, extrude menu could be used for the 100 mm extrusion.
Your code seems Ok, but obviuosly it will require some testing.
In the PID menu a will restore the indentation I used for "break" statements. Also the part you added in the "switch" statement does not require the {} external block

**Comment by traffic-light** [comment]
@digant73  Thank you for the feedback.
The reason why I added the heating menu is to make it more easy for the user.
Select the desired nozzle and the desired temperature for the current filament.
After that give some little hint to mark 120mm.
Extrude slowly and when it's not right you can update the e-steps without a calculator.

So in my opinion it's  a handy addition to the tuning menu. 
But if people think it's just a unnecessary update I will used on my own ;-)

I will fix the part that the new and old steps disappears.
That is the only thing I should test for now.

About the {}: they are needed when you've got longer code in a switch case.
I will resotre the indentation on the breaks in the PID. 

Thank you for the feedback.

**Comment by traffic-light** [comment]
I updated the code. It's now working correctly.
The e-steps were not called by reference

**Comment by traffic-light** [comment]
Only thing to do:
Change the name in the tuning menu.
Now it's called ext.100mm
It should be tune ext.

**Comment by traffic-light** [comment]
I did change the button name in the tuning menu.
Maybe it's better to have other icon? One that tells you that it is for changing the e-steps?

**Comment by guruathwal** [comment]
@traffic-light  This message can be skipped and ask for entering the measured length and display a calibration ok message if no calibration is needed.
https://user-images.githubusercontent.com/37051137/90334894-17486200-dfd1-11ea-9d86-5829d8a8bb79.png

**Comment by traffic-light** [comment]
Thanks.that is true. Will do that

**Comment by traffic-light** [comment]
@guruathwal Done!

**Comment by traffic-light** [comment]
Did a last check on code and functionality after changes were made.
Everything is working correctly and is ready to merge ;-)

**Comment by traffic-light** [comment]
Did a last check on code and functionality after changes were made.
Everything is working correctly and is ready to merge ;-)

**Comment by traffic-light** [comment]
@bigtreetech I see that you changed Language.c and .h
There are too many keywords in the languages files to make textSelect 8 bit. (there are more then 255)

When it's 8 bit you get this warning: 
image

**Comment by ETE-Design** [comment]
@traffic-light Great idea with making it possible to make E-Step direct from the screen... Looking forward for this feature being merged...

**Comment by traffic-light** [comment]
> @traffic-light Great idea with making it possible to make E-Step direct from the screen... Looking forward for this feature being merged...

Thank you for you comment. I was thinking the same when programming it :-P

**Comment by ETE-Design** [comment]
@traffic-light Then only M600 need to work as it should then it is almost perfect :-) BTW, is your merged up to the newest version?

**Comment by traffic-light** [comment]
I don't see the point of using m600 ;-)

It's not merged with the version on btt GitHub. It's 1 version older.

I could merge if you want

**Comment by ETE-Design** [comment]
@traffic-light But some og is do ;-) Would be great if you merge, then I Will try your version ASAP :-)

**Comment by traffic-light** [comment]
It's merged with the master.

**Comment by traffic-light** [comment]
@ETE-Design feel free to give me some feedback ;-)

**Pull request merged**
