### PR TITLE
improved menus + new menus + new popup type + custom ACK message handling + cleanup and fixes

### PR DESCRIPTION
**Pull request by digant73**
Improved existing menus such as:
* ProbeOffset: added new functions (save, XY axis unlock...) via a new submenu + cleanup
* ManualLeveling: Added new functions (XY axis unlock, bed edge distance menu...) via a new submenu + cleanup
* MachineSetting: Added new functions (save, restore, reset) via a new submenu
* ZFade: added save button (saving feature is now the same as in ProbeOffset and Babystep menus)
* UnifiedMenu: improved ABL ON/OFF update + cleanup

New menus:
* ConnectionSetting: Any connection settings such as baudrate, disconnect button, shutdown button were migrated AS IS in this new menu located under Settings menu
* Tuning: it contains features such as PID autotune menu and typical 100mm extrusion button (usefull for calculating proper steps-per-unit). The menu is located under Settings menu
* PID autotune: menu allowing to handle the entire PID process for bed + nozzles. A dialog box will popup the result of the process (success, fail, timeout)
* LevelingEdgeDistance: it allows to set the "level_edge" parameter. Thus to set the bed edge distance of the four leveling points

New features:
* added new "notification" popup type. A notification popup is displayed for few seconds (by default set to 1.5 seconds, configurable in Configuration.h). No user interaction is needed
* added a configurable popup type and buzzer type for the "known" echo messages (registered in parseACK.c).
    
    Available popup types are:
      none:         no popup. The echo message is silently discarded
      reminder:     reminder popup. A reminder popup is displayed. A user interaction is needed
      notification: notification popup. A notification popup is displayed for few seconds. No user interaction is needed
    
    Furthermore, the use of buzzer (on or off) is also selectable

    Functions signature to read and set the parameters for any known echo message are available in parseACK.h.
    E.g. I used that in Z Fade menu to temporary disable some echo messages

* added a configurable popup type and buzzer type for the error ACK and echo ACK messages.
    
    Available settings, provided in config. ini and FeatureSetting menu, are:
      OFF:   no popup. The message is silently discarded
      ON:    A reminder popup is displayed. A user interaction is needed
      SMART: A notification popup is displayed for few seconds. No user interaction is needed

    That feature is useful for example to temporary suppress any kind of error or echo ACK message

Fixes:
* general cleanup (converted tabs to spaces + correct indentation) on different files
* restored slovenian language in config.ini file (it was removed by mistake in the last BTT merge)
* changed some label names (e.g. ABL_start) whose values have a "general" meaning (e.g. "start", "down" etc...) in order the label names can be reused in more than one context and/or menus.
* fixed some wrong settings for MKS TFT + added correct SPI slave code to allow integration with SKR 1.3 main board

-----------------------
UPDATE HISTORY:
-----------------------
* 2020-08-05: Merge with BTT main branch
* 2020-08-04: Added all new icons for all TFT, for both Unified and Classic menu styles.
                       Thanks to **@bryan065** for his fast and fantastic work!

-----------------------
MISSING TASKS:
-----------------------
* NONE: This PR was fully tested on current BTT main branch and no bugs were discovered. The PR can be considered ready to be merged on BTT branch. Any suggestion/question is welcome!

### CODE REVIEW

**Comment by Tygrys-1** [comment]
How do you handle the M117 from GCode? at current implementation it stay at the to until clicked. It is inconvinient, as it hides the print time and temps under the window. Marlin is displaying this in the status line, without overlaping the screen. I am using this to display the layer number and pressing "ok" after each layer change has no sense.

**Comment by AntoszHUN** [comment]
Hi!
I am now working on a new icon set. For now, it looks like this. She's ready soon. I just don't know how to upload a folder. Because there will be a whole new folder for all displays, from TFT24 to TFT70.

IMG_20200801_134953
IMG_20200801_135002
IMG_20200801_135047
IMG_20200801_135129
IMG_20200801_135142

**Comment by digant73** [comment]
> How do you handle the M117 from GCode? at current implementation it stays at the top until clicked. It is inconvinient, as it hides the print time and temps under the message window. Marlin is displaying this in the status line, without overlaping the screen. I am using M117 to display the layer number and pressing "ok" after each layer change has no sense.

yes I know. that M117 handling is present in the last BTT merged branch. I didn't change it. it is generated on interfaceCmd.c (line 575). The M117 is generated by the last added UBL leveling

**Comment by digant73** [comment]
> Hi!
> I am now working on a new icon set. For now, it looks like this. She's ready soon. I just don't know how to upload a folder. Because there will be a whole new folder for all displays, from TFT24 to TFT70.
> 
> IMG_20200801_134953
> IMG_20200801_135002
> IMG_20200801_135047
> IMG_20200801_135129
> IMG_20200801_135142

they are nice, but I think the icons must be compliant to the unified and classic style in order the PR is eventually merged by BTT

**Comment by AntoszHUN** [comment]
> 
> 
> > Hi!
> > I am now working on a new icon set. For now, it looks like this. She's ready soon. I just don't know how to upload a folder. Because there will be a whole new folder for all displays, from TFT24 to TFT70.
> > IMG_20200801_134953
> > IMG_20200801_135002
> > IMG_20200801_135047
> > IMG_20200801_135129
> > IMG_20200801_135142
> 
> they are nice, but I think the icons must be compliant to the unified and classic style in order the PR is eventually merged by BTT

This is a completely separate icon pack. I made a separate folder for it that includes all of it, as with the Unified and Classic icons. This is called the RedMenu icon pack.

**Comment by ETE-Design** [comment]
@digant73 Seems like you have an MKS Also... Have a question about the LED Part... My board running the RGB Led on mainboard in Marlin, seems like it is not possible to tell the screen to use 3 pins instead of one? Is it possible to make it support the RGB Led feature Marlin offer?

**Comment by bryan065** [comment]
@digant73 I can update all the icons to match the unified theme & classic themes. Also how's the filament change (M600, M701, M702?) coming along?

**Comment by digant73** [comment]
> @digant73 Seems like you have an MKS Also... Have a question about the LED Part... My mainboard using the RGB Led in Marlin, but seems like it is not possible to tell the screen to use 3 pins instead of one? Is it possible to make it support the RGB Led feature Marlin offer?

try to remove the comment on:

//#define LCD_LED_PIN            PD14

in the pin_MKS_TFT32_V1_4.h

and let me know if it works. I will then commit the change

**Comment by digant73** [comment]
> @digant73 I can update all the icons to match the unified theme & classic themes. Also how's the filament change (M600, M701, M702?) coming along?
> 
> I'll create the entire icon set for:
> 
> * [ ]  connection_settings.bmp
> * [ ]  eeprom_save
> * [ ]  eeprom_restore
> * [ ]  eeprom_reset
> * [ ]  extrude_100.bmp
> * [ ]  level_edge_distance.bmp
> * [ ]  pid.bmp
> * [x]  tuning.bmp
> * [x]  xy_unlock.bmp

that should be great, thanks! just my thought about what I would like:
* connection_settings: the stile (for unified theme) is already good. The picture should be scaled for all the TFT
* tuning: That's already preaty good (compliant to unified style). Just a shadow could be added
* xy_unlock: I was thinking to an image similar to the Point_5 but with arrows araount the point
* level_edge_distance: similar to the existing one but more compliant to the unified style (so the orange arrow must be replaced with a more neutral color)
* For the 3 eeprom picture, I would provide a top to down arrow for the "save", a bottom to up for the "restore" and a cycling (like in the reset_value icon) sign for the reset.
* PID: I really like that picture

**Comment by ETE-Design** [comment]
@digant73 This is what is defined in Configuration.h in Marlin...
#define RGB_LED
//#define RGBW_LED

#if EITHER(RGB_LED, RGBW_LED)
  #define RGB_LED_R_PIN 5
  #define RGB_LED_G_PIN 4
  #define RGB_LED_B_PIN 6
  #define RGB_LED_W_PIN -1
#endif

But how to tell the screen the pins used when more than one?

**Comment by digant73** [comment]
> @digant73 This is what is defined in Configuration.h in Marlin...
> #define RGB_LED
> //#define RGBW_LED
> 
> #if EITHER(RGB_LED, RGBW_LED)
> #define RGB_LED_R_PIN 5
> #define RGB_LED_G_PIN 4
> #define RGB_LED_B_PIN 6
> #define RGB_LED_W_PIN -1
> #endif
> 
> But how to tell the screen the pins used when more than one?

On my printer (Sidewinder X1) those are the RGB components for the LED typically located in the extruder. And it perfectly works

**Comment by ETE-Design** [comment]
@digant73 Same here, have a Sidewinder X1, so I just need to uncomment //#define LCD_LED_PIN PD14 then it should work?

**Comment by digant73** [comment]
> @digant73 Same here, have a Sidewinder X1, so I just need to uncomment //#define LCD_LED_PIN PD14 then it should work?

No, for the LED in the extruder, you don't need to change anything. Try the PID autotune. You should see the LED changing color according to the status of the PID process

**Comment by digant73** [comment]
> > How do you handle the M117 from GCode? at current implementation it stays at the top until clicked. It is inconvinient, as it hides the print time and temps under the message window. Marlin is displaying this in the status line, without overlaping the screen. I am using M117 to display the layer number and pressing "ok" after each layer change has no sense.
> 
> yes I know. that M117 handling is present in the last BTT merged branch. I didn't change it. it is generated on interfaceCmd.c (line 575). And it seems that those M117 are generated by the last added UBL leveling. You can simply comment the popupReminder on interfaceCmd.c

I commented out the popupReminder for M117. You should not be annoyed by the popup dialog box now. You should only see a message in the status bar. I don't know why that popup message was introduced. However, It was the only one present

**Comment by bryan065** [comment]
@digant73 Tried to match the icons to your originals as best as I can while keeping the unified theme look. I have a few more icons I want to update to keep in line with the unified look, mind if you include those in this PR too? (will attach the other icons in a bit)
icons

**Comment by bryan065** [comment]
Here's the matching classic icons
test
[digant-icons-classic.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5020061/digant-icons-classic.zip)

**Comment by guruathwal** [comment]
@digant73  Not good idea to auto-remove notifications. this might miss important messages from the printer if the user is not paying attention or not nearby.

**Comment by digant73** [comment]
> @digant73 Not good idea to auto-remove notifications. this might miss important messages from the printer if the user is not paying attention or not nearby.

The functionality was thought to give the possibility to switch (typically just temporary) at runtime the type (off, reminder and notification). The reminder type remained the default configured type. But often (e.g. with Octoprint, Pronterface) you can receive a lot of error messages that you would like to simply discard in that moment (e.g. you know that they are not important and not preventing the work). Switching to notification type, the messages are still dispalyed but as notification (no need to continuosly press on the OK button to close the popup).
The same is applied to the echo ACK configured in parseACK. According to the context or menu (e.g. the Z fade) you can temporary change the type of the popup that otherwise will bother you with continous popup). In that case the new implementation is moving to your idea to provide info and not to suppress. Echo such as "bed leveling", "fade off" etc... are configured as notification in parseACK while with the current implementation they will be silently discarded. With the ProbeOffset menu you will be notified with "soft endstop" notifications while this could not happen with the current implementation.

**Comment by digant73** [comment]
> @digant73 Tried to match the icons to your originals as best as I can while keeping the unified theme look. I'm not sure how I feel about the edge distance one, so let me know if you have ideas for readability. I have a few more icons I want to update to keep in line with the unified look, mind if you include those in this PR too? (will attach the other icons in a bit)
> 
> icons
> [digant-icons.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5019439/digant-icons.zip)
> 
> I just updated the save/load icons to match the colors of EEPROM save/load for consistency:
> test
> [Update-save-icons.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5019448/Update-save-icons.zip)
> 
> Also just wanted to update the RGB icon to look a bit better. There's a light and dark style. The light style that has a background that matches the terminal icon in the same menu better.
> test
> [update-RGB-icon-dark.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5019513/update-RGB-icon-dark.zip)
> [update-RGB-icon-light.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5019524/update-RGB-icon-light.zip)
> 
> I'll be finishing up the classic icons in a bit

They are fantastic! thank you very much for your work. I will add them immediately

**Comment by ETE-Design** [comment]
Settings -> Features seems to freeze on the MKS TFT 28... Another thing who is pretty wierd, I have the RGB On the MKS Gen L like Artillery placed it... But Still can't change color, it just stays blue also when PID :-(
Is there a reason that some features/menus now are more than one place?

**Comment by digant73** [comment]
> Settings -> Features seems to freeze on the MKS TFT 28... Another thing who is pretty wierd, I have the RGB On the MKS Gen L like Artillery placed it... But Still can't change color, it just stays blue also when PID :-(
> Is there a reason that some features/menus now are more than one place?

did you use the last version (including the fix released yesterday on BTT main branch)?. I didn't have any freeze at all.
For the LED, the first check you can do is verify if the LED cable is correctly plugged in the extruder.

**Comment by ETE-Design** [comment]
I downloaded it direct from your Github, should that be enough? Or how to else?

**Comment by digant73** [comment]
Yes, it is enough. Just compile and install using the new config.Ini file and pictures. A reset of eeprom could help to solve the issues you have

**Comment by digant73** [comment]
@bigtreetech you didn't give time to merge CZ language on my PR.
attached the cz language PR merged with my PR, Please override that in your main branch or let me know if I have to open a PR for that.

[language_cz.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5034241/language_cz.zip)

**Comment by ETE-Design** [comment]
@digant73 Nice with the new menu "bed edge distance" is there a way to tell if distance from X and Y is different, or can you tell me how to make it?

**Comment by BlueBlue58** [comment]
Hi Guys
I updated the firmware yesterday on my BIGTREE_TFT35_V3.0_E3 and got 2 errors. One is missing bmp file which is not in the library of downloadable files, and the other is an error with fan_control?
See pics.
Screenshot_Fan_error
Screenshot_Firsterror

**Pull request merged**
