### PR TITLE
Fix pausing print from onboard SD card, update French translation

### LINKED ISSUE #488: [BUG] TFT Mode and SKR V1.4 Turbo no connection.
Problem:

The problem is clearly visible in the pictures. The display works in Marlin mode. Connected to the system board. However, you no longer want to connect in Touch mode. Something went wrong with the firmware. Works with older TFT fimware. Not currently downloadable. Please correct this error. Hope I'm not wrong with me. TFT mode is not good!

IMG_20200331_124827730

IMG_20200331_124809524

### LINKED ISSUE #1523: [BUG] Resume does not work after pausing print from onboard SD card (SKR mini E3 2.0 TFT35 E3 V3.0)
### Description

After pausing a print in touch mode it will do the filament purge in the last printing point instead of the top left corner and will present a resume dialog box. After that, impossible to resume by clicking on the ok button until power off.

### Steps to reproduce

1. Launch a print in touch mode from board SD card
2. Pause the print

**Expected behavior**
To retract, raise the Z axis, and move to the top left corner of the bed for filament purge.
To present a dialog box with the resume question
To resume the print after clicking ok on the dialog box 

**Actual behavior**
Z axis raises, moves to the top left corner but comes back to the last printing point for filament purge
presents the resume dialog box but impossible to continue from there until power off

### Hardware Variant
TFT35 E3 V3.0
### TFT Firmware Version & Main Board Firmware details
TFT firmware BIGTREE_TFT35_V3.0.26.x (config version 20201218) - Marlin 2.0.7.2

### Additional Information
Was reported in SKR-mini-E3 as https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/issues/488
IMG_4533
IMG_4534

### PR DESCRIPTION
**Pull request by Guilouz**
Pause when printing from onboard SD card have issue when using M25 command.

Marlin related issue here : https://github.com/MarlinFirmware/Marlin/issues/18191

Solution is to use Head Park command (M125).

Before :
- Pressing pause on screen
- Print is paused and Hotend is parked but go back immediately at the last position where the pause was made without user interaction
- Purge is done above the print
- Screen tell to user to Continue

After :
- Pressing pause on screen
- Print is paused and Hotend is parked
- Screen tell to user if he want to purge or continue printing
- After pressing Continue, hotend go back to the last position where the pause was made and printing

Tested on 2 printers (CR-10S Pro and Sidewinder X1), working like a charm.

Fix #488
Fix #1523

### CODE REVIEW

**Comment by kisslorand** [comment]
What if ADVANCED_PAUSE is not enabled in Marlin?

**Comment by digant73** [comment]
the new setting STRING_HEATER_SOUND (just merged in the main branch) seems to be missing.
It has to be provided after STRING_ALERT_SOUND

**Comment by Guilouz** [comment]
> What if ADVANCED_PAUSE is not enabled in Marlin? In that case with your PR the print will not pause at all.
> I wrote about this problem [here](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1523#issuecomment-764005977).

So, what can you do for that ?

**Comment by kisslorand** [comment]
Right now, as we speak, I am checking Marlin again to find a solution on the Marlin side. TFT is not responsible for this problem.

**Comment by Guilouz** [comment]
> Right now, as we speak, I am checking Marlin again to find a solution on the Marlin side. TFT is not responsible for this problem.
> It's not the first time TFT is blamed when the bug is on the Marlin side.

I think it's not a problem, in config.ini it's already specified to enable :

# Options to support M600 with host & (Un)Load menu:
#   Options to support dialog with host (as pre requisite)
#   NOZZLE_PARK_FEATURE (in Configuration.h)
#   ADVANCED_PAUSE_FEATURE (in Configuration_adv.h)

**Comment by kisslorand** [comment]
As it is written there, it is an option. The TFT firmware must function as intended on every option selected.
I think I found something in Marlin but I would need other's opinion about that. I just have to find a way to discuss a Marlin issue in this repository.

**Comment by Guilouz** [comment]
> As it is written there, it is an option. The TFT firmware must function as intended on every option selected.
> I think I found something in Marlin but I would need other's opinion about that. I just have to find a way to discuss a Marlin issue in this repository.

Take a look to the last comment of this  : https://github.com/MarlinFirmware/Marlin/pull/19803#issuecomment-770158006

**Comment by kisslorand** [comment]
That brings me back to the first question: what if ADVANCED_PAUSE is not defined in Marlin?

**Comment by Guilouz** [comment]
> That brings back the first question: what if ADVANCED_PAUSE is not defined in Marlin?

Yes the main problem is in Marlin for sure, this is the only current solution, issue in Marlin has been present for several months without resolution until now...

**Comment by kisslorand** [comment]
Wait a sec please, I have a solution:

_will be filled in a few minutes_

**Comment by Guilouz** [comment]
> Wait a sec please, I have a solution:
> 
> In "Prining.h":
> `__case BOARD_SD:`
> `____case BOARD_SD_REMOTE:`
> `______infoPrinting.pause = is_pause;`
> `______if (is_pause)`
> `#ifdef NOZZLE_PAUSE_M600_M601`
> `_________request_M125();`
> `#else`
> `________request_M25();`
> `#endif`
> `______else`
> `________request_M24(0);`
> `______break;`
> 
> If `NOZZLE_PAUSE_M600_M601` is defined, it must mean that `ADVANCED_PAUSE` is also defined in Marlin.

Yes it's a good workaround ! Thanks.

**Comment by kisslorand** [comment]
Thank you for understanding my concerns and the willingness to work together.

**Comment by Guilouz** [comment]
> Thank you for understanding my concerns and the willingness to work together.

I had not thought of this solution, good job !

**Comment by Guilouz** [comment]
@kisslorand Nothing to see with this PR but I have you seen my issue with onboard SD reported here ? https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1326#issuecomment-769565252

**Comment by kisslorand** [comment]
Yes, I did. It is already mentioned in the ticket you fixed https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1523#issuecomment-769309107

**Comment by Guilouz** [comment]
> Yes, I did. It is already mentioned in the ticket you fixed [#1523 (comment)](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1523#issuecomment-769309107)

@kisslorand No not fixed, I have a issue with screen stay on "Loading..."

I can access to onboard SD, run a print but if I cancel it, screen stay on "Loading..." screen. Need to reset screen.

**Comment by kisslorand** [comment]
I know, you fixed another issue. Your issue is mentioned in that ticket also. In my opinion it would be better to have an open ticket about the exact issue, it makes it easier to track and makes it easier for others to chime in.

**Comment by Guilouz** [comment]
> I know, you fixed another issue. Your issue is mentioned in that ticket also. In my opinion it would be better to have an open ticket about the exact issue, it makes it easier to track and makes it easier for others to chime in.

I have opened it.

**Comment by Guilouz** [comment]
@bigtreetech PR is now ready to be merged.

**Comment by oldman4U** [comment]
Hi.

Pausing works, but why does the head park above the print and not at parking position?

**Comment by Guilouz** [comment]
> Hi.
> 
> Pausing works, but why does the head park above the print and not at parking position?

Not really understand what do you mean. Normal operation is that the hotend must park at the positions indicated in NOZZLE_PARK_FEATURE and stay at this position and purge before user interaction.

**Comment by digant73** [comment]
@Guilouz @kisslorand I'm not sure using NOZZLE_PAUSE_M600_M601 is the proper solution. NOZZLE_PAUSE_M600_M601 is used to emulate M600, so M600 is not sent to Marlin (during a print). It is meant in case ADVANCED_PAUSE is not configured in Marlin. While this PR is considering the opposite (if I'm not wrong)

**Comment by kisslorand** [comment]
Good catch! 
Looking again `NOZZLE_PAUSE_M600_M601` is used to replace M600 and M601 with a regular pause. If `NOZZLE_PAUSE_M600_M601` is defined than M600 and M601 commands are not sent from TFT.
In this case maybe `#ifdef LOAD_UNLOAD_M701_M702` can be used, since it needs the `FILAMENT_LOAD_UNLOAD_GCODES` to be defined in Marlin which needs the `ADVANCED_PAUSE_FEATURE` to be defined.

**Comment by Guilouz** [comment]
> NOZZLE_PAUSE_M600_M601

Maybe better to found a way to detect if Marlin has PARK_HEAD_ON_PAUSE enable or not no ?

**Comment by kisslorand** [comment]
I will test my idea later today. I am very busy at the moment.

**Comment by kisslorand** [comment]
> Maybe better to found a way to detect if Marlin has PARK_HEAD_ON_PAUSE enabled or not no ?

I found a way to make use of `PARK_HEAD_ON_PAUSE` defined in Marlin. I tested with `ADVANCED_PAUSE_FEATURE` enabled & disabled, with `PARK_HEAD_ON_PAUSE` enabled & disabled in Marlin. It works in every combination, it parks the head only when both are enabled, otherwise just simply pauses.
May I include the solution in my PR #1588 or do you want to rewrite yours?

**Comment by Guilouz** [comment]
> #1588

As you want, you can included it in your PR.

**Comment by kisslorand** [comment]
OK, I included in my PR #1588 amongst many other bugfixes. I really appreciate your help. Thank you!

**Pull request merged**
