### PR TITLE
Layer number display during print

### PR DESCRIPTION
**Pull request by kisslorand**
### Requirements

BTT or MKS TFT

### Description

This PR adds the option to show the layer number during print . It can be altered between layer height and layer number by pressing the Layer (nozzle) icon/display area. The default layer display type can be set in the `config.ini` file.
The information is read from the gCode. Most slicers put a comment at each layer start, a comment that shows the layer number to be printed. This PR uses that comment.
Unfortunately this info can be read only if printing from the TFT SD Card or TFT USB.

### Benefits

At some point there was a request for this but I cannot find it.

### Related Issues

There are no bugfixes in this PR.

### Notes

This PR opens a door for future features. It introduces the parsing of comments from the gCode file. 
There are many other useful infos in the comments that slicers generate, it is is now easier to interpret and use them if needed.

For the moment this PR is marked as draft as it is in conflict with PR #2084.

### CODE REVIEW

**Comment by radek8** [comment]
@kisslorand
And does the layer height icon have to be clicked?
If you give options in Config.ini
- show layer height
- display layer number
- toggle between height and layer number

That would be absolutely great and it will not conflict with the PR2084.

I would like to automatically switch between height and layer number rather than a static display of one or the other information.

**Comment by oldman4U** [comment]
I asked for it and this is great.

Thank you

**Comment by Guilouz** [comment]
Why not display layer height AND layer number at the same time at the same time? Like duration / percentage icon.

**Comment by kisslorand** [comment]
@radek @Guilouz 
Good ideas!

**Comment by kisslorand** [comment]
Option to show both (layer height & number) implemented.

**Comment by Guilouz** [comment]
@kisslorand do you think it's possible if ;LAYER:0 is seen to add +1, to display layer 1 / 1561 on TFT and not 0 / 1561 ? 

Because Cura start the first layer at value 0, like this : 

;LAYER_COUNT:1561
;LAYER:0 (first layer)
...
;LAYER:1560 (last layer)

Otherwise at the last layer we will have 1560 / 1561.

**Comment by kisslorand** [comment]
@Guilouz 
It was in the agenda, it has been implemented.
Now layer number "0" means the printer is not printing an actual layer, instead it is doing some preliminary job before the actual print begins (like nozzle prime, etc).

**Comment by kisslorand** [comment]
I think this PR is ready to go to his master :)

**Comment by sarvenn** [comment]
Does anyone know how can I see layer number using prusaslicer? Verbose mode?

**Pull request merged**
