### PR TITLE
Add new E-steps stored to EEPROM

### PR DESCRIPTION
**Pull request by Guilouz**
Add new E-steps stored to EEPROM

### CODE REVIEW

**Comment by traffic-light** [comment]
There is a reason that's not saving in eepprom. You should do it yourself. Just like in marlin.  It's bad to save too many times to eeprom

@bigtreetech: please ignore this pull request...

**Comment by Guilouz** [comment]
Why too many ? Once you have tune your e-steps, you save it once and that's all...

**Comment by traffic-light** [comment]
Every save cycle makes the eeprom live shorter. It's a max of 100000 cycles. When you press the button 2 times the eeproms live is shorten with 2 possible saves

**Comment by Guilouz** [comment]
Yes I know, but what is the difference between saving it directly or exiting the menu and going to save it in another menu?
Or maybe add an optional button to save it in eeprom for people want to save it directly ? 
Generally we do not save in the eeprom many times once the settings have been made and saved.

No the third commit is for updating translation file...

**Comment by traffic-light** [comment]
Saving it directly saves it on the ram of the microcontroller. Save it with m500 saves it in eeprom.
Ram memory gets 0 on reboot/ powerloss. Eeprom stays the same.

Eeprom memory is some sort of burn memory. When writing to it it's life cycle goes down.

So she. Writing to eeprom ALL the parameters in the ram of your microcontroller will be written to eeprom.


There is already a button in the machine settings. It will be a mess when placing everywhere a eeprom save button.

I know it's updating the language. But it could be in one pull request.

Title could've been: update language_xx and tune extruder menu

**Pull request closed without merging**
