### PR TITLE
model preview for cura plug-in unit

### PR DESCRIPTION
**Pull request by Msq001**
### Description
* Directly read the icon in gcode exported after installing BTT Cura plug-in unit， need not .bmp files
* the BTT Cura plug-in unit in here https://github.com/bigtreetech/Bigtree3DPlugin/tree/master

### CODE REVIEW

**Comment by rebel1** [comment]
Great !

**Comment by juavinas** [comment]
> 
> 
> Works Great. Tested on Bigtreetech 3.5 and an MKS Clone on my Sidewinder

Where did you get *.27 firmware?

from: https://github.com/bigtreetech/Bigtree3DPlugin
Update touch screen firmware after this Pull request, The first release to include this feature is Vx.x.27

**Comment by BsCmOD** [comment]
> 
> 
> > Works Great. Tested on Bigtreetech 3.5 and an MKS Clone on my Sidewinder
> 
> Where did you get *.27 firmware?
> 
> from: https://github.com/bigtreetech/Bigtree3DPlugin
> Update touch screen firmware after this Pull request, The first release to include this feature is Vx.x.27

Infact it's the same question I've done to my self! I've tested this funtion before read firmware update note to x.x.27 version but I can't find it nowhere

**Comment by NicoletoAerials** [comment]
It works great!!!!!!! Compiled from the master and tested on TFT 35 v3 and SKR mini E3 v1.2 on an ender 3

**Comment by BsCmOD** [comment]
> 
> 
> It works great!!!!!!! Compiled from the master and tested on TFT 35 v3 and SKR mini E3 v1.2 on an ender 3

Have you used the actual firmware which is in tft repesotari of btt? So, with x.x.26 the thumbnail works?

**Comment by NicoletoAerials** [comment]
> > 
> 
> > 
> 
> > It works great!!!!!!! Compiled from the master and tested on TFT 35 v3 and SKR mini E3 v1.2 on an ender 3
> 
> 
> 
> Have you used the actual firmware which is in tft repesotari of btt? So, with x.x.26 the thumbnail works?

Yes I used the oficial master x.x.26 firmware. As far as I know is the one that has the newest modifications and fixes. 

Anyway, both, the master or the bug fix x.x.26.1 should work just fine. The changes needed are compatible with both firmware versions.

**Comment by bigtreetech** [comment]
@BsCmOD the Vx.x.27 is the first RELEASE version support this feature,  the firmware will support this feature  as long as this PR is merged. This week I will test and fix bugs in the firmware and release Vx.x.27 at the weekend

**Comment by reeftanker** [comment]
so where exactly is Vx.x.27 located, i cant find it and it doesn't work for me with .26 firmware for me

**Comment by Tygrys-1** [comment]
> 
> 
> so where exactly is Vx.x.27 located, i cant find it and it doesn't work for me with .26 firmware for me

None yet. You may just use this PR commit and build firmware by youself.

**Comment by reeftanker** [comment]
> > so where exactly is Vx.x.27 located, i cant find it and it doesn't work for me with .26 firmware for me
> 
> None yet. You may just use this PR commit and build firmware by youself.

oh, i dont know how to do the building firmware, too complex for me

**Comment by GregSKR** [comment]
Nice work.
I can see that compilation shows some problems:

/TFT/src/User/API/UI/ui_draw.c
lines 59 and 88
unused variable 'mybr' [-Wunused-variable]

/TFT/src/User/my_misc.c
lines 172 and 191
array subscript has type 'char' [-Wchar-subscripts]

After removing lines 59 and 88 in ui_draw.c,
and replacing
`for (char i = 0; i < 2; i++)`
with
`for (uint8_t i = 0; i < 2; i++)`
in my_misc.c (lines 172 and 191)
problems as gone!..

**Comment by BsCmOD** [comment]
> 
> 
> @BsCmOD the Vx.x.27 is the first RELEASE version support this feature, the firmware will support this feature as long as this PR is merged. This week I will test and fix bugs in the firmware and release Vx.x.27 at the weekend

Have you got some news?

**Comment by BsCmOD** [comment]
> 
> 
> @BsCmOD the Vx.x.27 is the first RELEASE version support this feature, the firmware will support this feature as long as this PR is merged. This week I will test and fix bugs in the firmware and release Vx.x.27 at the weekend

@bigtreetech Have you got some news?

**Comment by redgod** [comment]
ya esta la version x.27?

**Comment by redgod** [comment]
no funciona con firmware x.26.x tft24 1.1

**Comment by SkifBor** [comment]
The plugin works great. Thank you! Can I change the color of the model?

**Comment by SkifBor** [comment]
The plugin works great. Thank you! Can I change the color of the model?

**Comment by BsCmOD** [comment]
> The plugin works great. Thank you! Can I change the color of the model?

Yes, if you change material color in Cura it will change also the preview color on tft

**Comment by SkifBor** [comment]
Thank you very much!

**Comment by aqasna** [comment]
> > > Works Great. Tested on Bigtreetech 3.5 and an MKS Clone on my Sidewinder
> > 
> > 
> > Where did you get *.27 firmware?
> > from: https://github.com/bigtreetech/Bigtree3DPlugin
> > Update touch screen firmware after this Pull request, The first release to include this feature is Vx.x.27
> 
> Infact it's the same question I've done to my self! I've tested this funtion before read firmware update note to x.x.27 version but I can't find it nowhere

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/releases

copy 
1. config.ini
2.bin file (depend ur model)
3. on the theme folder got pack..only copy pack for ur lcd size

**Pull request merged**
