### PR TITLE
Fix Icons & fix misspelt U_DISK_SUPPROT bug 

### LINKED ISSUE #638: Reset fails to reset touch rotation setting.
### Description

When using reset settings, the display rotation is reset, but the rotation setting of the touch remains rotated.

### Steps to reproduce

1. Rotate screen using Rotate UI and calibrate display.
2. Reset settings from the feature menu

**Expected behavior**
Display and touch calibration should be reset

**Actual behavior**
Display rotation is reset, but touch remains rotated.

### Hardware Variant
TFT24 V1.1
TFT24_V1_1_26

### LINKED ISSUE #639: USB disks are not loaded - for guruathwal
for @guruathwal :
In bigtreetech/BIGTREETECH-TouchScreenFirmware#627
You have an error.
USB disks are not loaded after editing
U_DISK_SUPPROT is not U_DISK_SUPPORT

After overwriting to U_DISK_SUPPROT it is functional.
I also stopped reading SD on the board. I did not find an error.
Can you check it?
Thank you
chyba USB1
chyba USB2
chyba USB3

### PR DESCRIPTION
**Pull request by guruathwal**
- Rename missing icons for TFT24 & TFT28 not renamed through #619
- Fix misplaced new icons for 'percentage'
- Fix misspelt U_DISK_SUPPROT to U_DISK_SUPPORT
- Fix Rotate UI on reset and rename Reset file only after completing reset process
Resolves #639, resolves #638

### CODE REVIEW

**Comment by oldman4U** [comment]
Great you are fine!

I will check and let you know in case. One day I have to register to buy you a coffee or two;-)

THANK YOU

**Comment by AntoszHUN** [comment]
I did something normally. Why did it have to be varied now? I don’t think it makes sense for someone to do something and then ruin the other person. :(

**Comment by guruathwal** [comment]
@AntoszHUN what are you talking about?

**Comment by AntoszHUN** [comment]
I scanned the percent marker icons. Now someone was in trouble with him. Now the icons are confused. And you fixed the icons. So far, why has it been as good as it was? I put all three icons where I needed to go. But the percentages are confused. I don’t understand why I try to do something meaningful when someone else makes sense of it. Why weren't the icons as good as they were?

I'm talking about this: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/615

**Comment by AntoszHUN** [comment]
Never mind. I don't want to argue. There are just a lot of pointless fixes. What was wrong with UDISK? It worked perfectly for me. What was wrong with the icons? Their name was as good as it was. I think there are a lot of pointless fixes. Instead of correcting real bugs by "big programmers" ... The filament motion sensor is handled well by arduino. TFT display software does not. I think you should book that. I made a request for it. Nobody cares about that. But I'm sorry if I hurt someone.

**Comment by guruathwal** [comment]
@AntoszHUN  I still can not understand what you are trying to say. 

> Never mind. I don't want to argue. There are just a lot of pointless fixes. What was wrong with UDISK? It worked perfectly for me. What was wrong with the icons? Their name was as good as it was. I think there are a lot of pointless fixes. Instead of correcting real bugs by "big programmers" ... The filament motion sensor is handled well by arduino. TFT display software does not. I think you should book that. I made a request for it. Nobody cares about that. But I'm sorry if I hurt someone.

The `U_DISK_SUPPROT` in the file **Print.c** was accidentally changed to `U_DISK_SUPPORT` by me in my last PR #627. Because of this, the UDISK was not visible in TFT35 V3 as the original word was misspelt. So I had to open a PR to fix the mistake then why not fix the whole misspelt word to avoid any mistake in future?

Some Icons were not renamed to match the list in firmware because of this they were not being updated. @rebel1 renamed icons for TFT35 but not for TFT24 & TFT28. that's why I renamed them.

The Percent Icons added by you are not renamed. They are just moved to the correct folder.

in #638 the touch was not resetting properly if the screen was rotated 180 degrees before reset. 
even I had issues with reset file. The touchscreen failed to calibrate but the reset file was renamed. due to this, I had to redo the whole reset file process again.

there is nothing else fixed. 

To be clear, I am not associated with BTT.  They do not pay me anything for my contribution. I am just a user of the BTT products. I do not earn anything from my contribution in this repository. 

Are you talking about #629? if yes, then I do not have **The filament motion sensor** so I cannot diagnose it. I can fix a problem only if I know how to fix it and when I have the tools to fix it.

**Comment by AntoszHUN** [comment]
All right. I understand. I made an optical filament motion sensor. That's how I was able to test that it works in Marlin. The obliterator ignores it.

**Pull request merged**
