### PR TITLE
Changed the ReadMe to cover the new language.ini, added "The Round Miracle" and the "Hybrid Red" themes and removed the "Classic" theme

### LINKED ISSUE #896: Folder upload
How do I upload a folder?

### LINKED ISSUE #1175: BIGTREETECH TFT35 V2.0 BITMAPS MISSING ISSUE IN NON-UNIFIED UPDATE
AFTER FAILED UPDATES OF THE TFT35 V2 FIRMWARE I NOTICED THAT THE BMP FILES ITS ASKING FOR ARE MISSING FROM THE BMP FOLDER.. THE UNIFIED FIRMWARE HAS ALL OF THE BMPS BUT THE OTHER ONE, I GUESS ITS THE WORDED TYPE AND NOT PICTURE ICON UNIFIED BECAUSE IT WORKS.. SO THE ORIGINAL WORDED ICON BITMAP FOLDER HAS BITMAPS MISSING... @BIGTREETECH PLEASE FIX THE TFT35 MISSING NON-UNIFIED BITMAPS.. IF IM INCORRECT THEN PLEASE TELL ME WHAT THE ISSUE IS. I FOLLOWED ALL POSTED ADVICE ON HERE BUT NOTHING WORKS EXCEPT USING THE UNIFIED FOLDER BITMAPS..  I PREFER THE OTHER ONES, NOT THE UNIFIED PICTURE TYPES..  THANKS FOR ANY INSIGHT.

### PR DESCRIPTION
**Pull request by oldman4U**
The new language.ini works different than it is described in the ReadMe today, which could confuse the user.
Added information about the cabling, because there are some users which do not understand how many cables to connect.

I removed the Classic menu, because it is not supported by the last firmware and added two themes which are supporting all TFTs from 24 to 70.

resolves #896 
resolves #1175

### CODE REVIEW

**Comment by AntoszHUN** [comment]
> 
> 
> The new language.ini works different than it is described in the ReadMe today, which could confuse the user.
> Added information about the cabling, because there are some users which do not understand how many cables to connect.
> 
> I removed the Classic menu, because it is not supported by the last firmware and added two themes which are supporting all TFTs from 24 to 70.
> 
> resolves #896
> resolves #1175



> 
> 
> The new language.ini works different than it is described in the ReadMe today, which could confuse the user.
> Added information about the cabling, because there are some users which do not understand how many cables to connect.
> 
> I removed the Classic menu, because it is not supported by the last firmware and added two themes which are supporting all TFTs from 24 to 70.
> 
> resolves #896
> resolves #1175

Then now it will be good hopefully! Thanks for all the help and work! As soon as it is included, I will update the icons because I see case_light.bmp is not included. This needs to be remedied urgently.

**Comment by AntoszHUN** [comment]
> 
> 
> The new language.ini works different than it is described in the ReadMe today, which could confuse the user.
> Added information about the cabling, because there are some users which do not understand how many cables to connect.
> 
> I removed the Classic menu, because it is not supported by the last firmware and added two themes which are supporting all TFTs from 24 to 70.
> 
> resolves #896
> resolves #1175

Then now it will be good hopefully! Thanks for all the help and work! As soon as it is included, I will update the icons because I see case_light.bmp is not included. This needs to be remedied urgently.

**Comment by oldman4U** [comment]
Hope so too😁

Can you sent me the missing icons so I add them to this PR. Who knows when btt pushes PRs again.

**Comment by AntoszHUN** [comment]
> 
> 
> Hope so toogrin
> 
> Can you sent me the missing icons so I add them to this PR. Who knows when btt pushes PRs again.

Here you go. I didn't know how to send it. But you can download it from here. :)

[All TFT new icon.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5543051/All.TFT.new.icon.zip)

**Comment by oldman4U** [comment]
Done. Please check.

**Comment by AntoszHUN** [comment]
> Done. Please check.

Okay. Super. Thanks!

**Comment by Acenotass** [comment]
Hello @oldman4U 
Thanks for your work! It makes sense to update the preview of my theme with the latest changes (colored bars ), as well as add the rounded corners info. You also need to remove the MSK folder from my theme in your repository.

**Comment by oldman4U** [comment]
Round Miracle Mainscreen 2

OK?

Other things you mentioned will also come with next update

**Comment by oldman4U** [comment]
Round Miracle Main Screen

Hope this is OK now. Other things will come with next update

**Comment by Acenotass** [comment]
Perfect!

**Comment by oldman4U** [comment]
Update in 5min

Please check again.

Thank you

**Comment by Acenotass** [comment]
As far as I understand MSK TFT is the same size as the TFT24 screen. In this case, IconPack from TFT24 should be suitable.

**Comment by oldman4U** [comment]
No idea, but we did not call it BTT TFT only, so hopefully people know what to use. I am not gonna buy MKS hardware to test it, but a TFT43 last week only for testing...

**Comment by Acenotass** [comment]
@AntoszHUN hi!
Your IconPack lacks tune_extruder.bmp, there are outdated images s_load.bmp, s_save.bmp and extrude_100.bmp. For compliance, I recommend checking with the list from the file \TFT\src\User\API\icon_list.inc

**Comment by AntoszHUN** [comment]
> 
> 
> @AntoszHUN hi!
> Your IconPack lacks tune_extruder.bmp, there are outdated images s_load.bmp, s_save.bmp and extrude_100.bmp. For compliance, I recommend checking with the list from the file \TFT\src\User\API\icon_list.inc

@oldman4U 
I'll fix it as soon as I know. I attached tune_extruder.bmp. Downloadable. I think oldman4U can do it. I would like to delete the files s_load.bmp, s_save.bmp and extrude_100.bmp. Thanks for the help!

By: AntoszHUN
[tune_extruder All TFT.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5548719/tune_extruder.All.TFT.zip)

**Comment by oldman4U** [comment]
Hi.

So there is one new icon and in exchange I have to delete the 3 files s_load.bmp, s_save.bmp and extrude_100.bmp.

Correct?

**Comment by oldman4U** [comment]
Please check and let me know in case you find something else.

**Comment by Acenotass** [comment]
The folder for TFT43 is also incorrectly named, should be called TFT43 instead of TFT40

> Hi.
> 
> So there is one new icon and in exchange I have to delete the 3 files s_load.bmp, s_save.bmp and extrude_100.bmp.
> 
> Correct?

Yes. Correct.

**Comment by AntoszHUN** [comment]
Super. Thanks for the help!

**Comment by oldman4U** [comment]
Yesterday after committing, everything was fine, now suddenly there are conflicts.... Is this because of the PR which was merged a few hours ago?

**Comment by oldman4U** [comment]
I use 43 anyway.

Thank you

Acenotass <notifications@github.com> schrieb am Di. 17. Nov. 2020 um 04:15:

**Comment by oldman4U** [comment]
Please check again.

Do you know if I can remove the language packs from the Theme folders?

**Comment by Acenotass** [comment]
@oldman4U 
I think that in general it is necessary to revise the folder structure

**Comment by Acenotass** [comment]
1  Copy to SD Card root directory to update (root) - includes .BIN .INI
2 Themes (subfolder root) - Unified Menu Material , The Round Miracle, Hybrid Red
3 Language Packs (subfolder root)- languages .INI

**Comment by oldman4U** [comment]
OK, so the language packs are part of the current Theme folders, so I keep it as it is and will see if they get updated through the language script made by Gurmeet or not. We will see.

For me this PR is ready to be merged in case you do not find anything new.

**Comment by ETE-Design** [comment]
@oldman4U I have an MKS TFT28, and there is "no" need for a special folder... But people who own a MKS TFT 28 have to add an directory called MKS on their SD-Card, and copy BMP + FONT to that folder... And they also need th rename the *.bin to mkstft28.bin for it to work...

**Comment by oldman4U** [comment]
Thats more something for the ReadMe, right!?

Send me the text and I add it or let me know what to do.

ETE-Design <notifications@github.com> schrieb am Di. 17. Nov. 2020 um 15:50:

**Comment by ETE-Design** [comment]
@oldman4U Now that MKS TFT28 has it's own Compile Target, should it then still be added to the Readme?

**Comment by oldman4U** [comment]
I have no such TFT, so I can not really speak for users using it. What would you suggest?

**Comment by AntoszHUN** [comment]
I don’t think MKS TFT displays should have been mixed in. The firmware on it works on a completely different principle. Closed source in addition. I messed with them that year. There's no point in dealing with it in my opinion. Stay with BTT. It's smarter and more functional. But this is just my opinion. I don't want to hurt anyone. :)

AntoszHUN

**Comment by oldman4U** [comment]
I agree, but the same time I do not want to decide this.

In general I am wondering why there are so many MKS and Sidewinder customers. Are the corresponding companies are not offering any help/updates?

**Comment by ETE-Design** [comment]
@oldman4U Think there are many Artillery users here cause it is possible to use BBT Firmware on the Stock Sidewinder X1/Genuis... The Firmware delivered with the screen dosen't offer many features... And Artillery choosed to Clone the MKS TFT 28 on their printers...
Have an Sidewinder X1, and the BBT Firmware work great at it, but again it is not the BBT Community's assignment to make it work with that screen... I'm just glad it does :-) Think there is almost if not noone develop firmware for the TFT on Artillery's Printers...

**Comment by oldman4U** [comment]
Could "someone" be you?

I help wherever I can, but not having the hardware limits my possibilities and I will not buy the hardware, just to be able to give support - like I do with some of the TFTs I bought.

Someone has to take over, otherwise it will end up like the Classic Interface Theme.

**Comment by ETE-Design** [comment]
@oldman4U I'm really not into programmeng :-( But seems like I only need to figure out how to remove "Version" it add to the filename....
Why should you also just but TFT's just to help develop if it dosen't have your interest :-D

**Comment by oldman4U** [comment]
I am no. Developer too so I try to help otherwise.

Hope BTT merges this PR soon. Many annoying tickets are coming in because of the outdated firmware and documentation.

**Comment by AntoszHUN** [comment]
> I am no. Developer too so I try to help otherwise.
> 
> Hope BTT merges this PR soon. Many annoying tickets are coming in because of the outdated firmware and documentation.

I'm already looking forward to the merger.

**Comment by oldman4U** [comment]
👍🏻

Zs.Antal <notifications@github.com> schrieb am Sa. 21. Nov. 2020 um 20:30:

**Comment by oldman4U** [comment]
@bigtreetech @Msq001 

This is now the third time that I have to resolve conflicts because you are not merging my commit. Please let me know if you would like to have further commits from me, or not.

Thank you

**Comment by bigtreetech** [comment]
merged now.   so sorry for the delay.

**Comment by oldman4U** [comment]
Thank you.

Your inability to show a minimum engagements results in people going away from you.

**Comment by bigtreetech** [comment]
I'm sorry to make you tired.  I will invest time in this project. And pay attention to bugs and FR list

**Comment by oldman4U** [comment]
We the community will take care for the tickets which are coming in, but we need your help for those things we can not do and this is most important to merge PRs. The Bot installed by Gurmeet already closes unused and useless tickets, the centralised FR and hopefully soon centralised Bug list helps to organise the important Bugs and FR's.

For you ToDo:
1. Please merge #1255 as soon as possible
2. Please pin #1218 instead of #290 and change the order of the pinned tickets like described:
Please make ticket 1218 the most left, followed by the FR ticket #1170 and the Read Me Before Posting #1047 the one most to the right. This would place it right above the button to start a "New issue" which would make it more likely that people read it.
3. readek8 will update the #1265 with the PR from today, please update it once available

I believe it is time to release a new version. In case you let us know how this works - we can do it.

Thank you

**Comment by AntoszHUN** [comment]
@bigtreetech @oldman4U @Msq001 

Thank you so much for your help! Also thank you for joining! I am very glad that a Hungarian (I) designed icon pack has been included. That means a lot to me!

Thanks! Respect!
AntoszHUN

**Comment by bigtreetech** [comment]
> For you ToDo:
> 
> 1. Please merge #1255 as soon as possible
> 2. Please pin #1218 instead of #290 and change the order of the pinned tickets like described:
>    Please make ticket 1218 the most left, followed by the FR ticket #1170 and the Read Me Before Posting #1047 the one most to the right. This would place it right above the button to start a "New issue" which would make it more likely that people read it.
> 3. readek8 will update the #1265 with the PR from today, please update it once available
> 
@oldman4U Hello, 
for 3. I have updated the precompiled firmware, and clean up the structure of the precompiled folder.
for 2. It's ok now
for 1. #1255 It was submitted by my colleagues, but it has not passed the stress test, so it has not been merged yet. I will merge it after the test is completed

**Comment by oldman4U** [comment]
This is GREAT!

Thank you

This is all for now, I will update the ReadMe asap, so it reflects the new structure.

You made many users very happy today, I really appreciate

**Comment by oldman4U** [comment]
You are VERY welcome.

Thank you

Zs.Antal <notifications@github.com> schrieb am Fr. 27. Nov. 2020 um 15:07:

**Pull request merged**
