### PR TITLE
Add new Printing Screen, change font & icon flash addresses,Improve model preview, add more option in setting in list mode and other bug fixes (details in description), increase software version to 25.2

### PR DESCRIPTION
**Pull request by guruathwal**
photo_2020-01-26_17-32-04

photo_2020-01-26_23-37-01

- Add option for enabling or disabling sending g-code before and after printing in the settings menu.
- clean up feature setting menu in List-Mode.
- Add 'S' & 'T' in numeric keypad in the g-code terminal
- Add option for enabling or disabling global temp info in the settings menu.
- Add a new printing screen.
- Fix font and icon flash address overlapping #248 
- Fix for printer stuttering / lagging #282 (needs enabling `RAPID_SERIAL_COMM` in configuration.h).
- fix missing preview images.
- display BMP preview file faster without writing to flash (saving flash write cycles). Preview images now load faster.
- increase software version to 25.2 and add 25.1 to archive (as on 16-Jan-2020)
- Permanently enable List-Mode in feature settings.
- add an option in feature settings to toggle List-Mode in file viewer menu no need to enable or disable list mode in configuration.h
- fix some bugs & remove unused icons.
- Option to keep UART connected in Marlin mode to allow connecting Octoprint to TFT controller's UART Expansion Port (needs enabling 'CLEAN_MODE_SWITCHING_SUPPORT') by @hfog
- Add saving of Knob led color setting & moved some default settings to configuration.h (by @GeminiServer).

**Full update required (including icons and font) after flashing**

### CODE REVIEW

**Comment by guruathwal** [comment]
@JWolfJr 
> What resolution do you download your stl files in? I usually use fine, but on some of the forums I read a lot of people say medium is enough. Between that and lowering the print resolution when slicing it helps with the issue a lot. What have you done to work around this? Besides working on the code of coarse.

I printed both hi res and low res models. I did not notice any difference in serial performance when printing with only one serial connected, I have noticed that the probelm appears on the serial port which is defined as `-1`. While printing through host connected on serial port `-1` if the printer receives commands (like M105)  from another host connected on serial port `0`, it will stutter or freeze some times. I am still trying to pinpoint the exact problem.

**Comment by JWolfJr** [comment]
I for one appreciate you working on this.  What's the best way to keep posted of your findings, this page?  I know enough C++ and python for some home projects, nothing to the extent of Marlins whole ecosystem.  So can't help too much there, I have tried adjusting some of the buffer numbers.  No noticeable change.  I'd be happy to try what ever you come with and give some feed back.

**Comment by guruathwal** [comment]
@JWolfJr sure...  the main issue thread is #282

**Comment by JWolfJr** [comment]
Thank you!

**Comment by robbycandra** [comment]
> a few users have reported problem when both octopi and TFT are connected to the printer. there seems to be problem with the marlin firmware when two serial ports are used. I do not use octopi but I have encountered similar problem when printing through PC with repetier host.

I have make a PR about serial port in marlin. It is merged with the last bugfix2.0 version

**Comment by guruathwal** [comment]
Hi @robbycandra .. we need to confirm the time stamp in the marlin firmware every one is using.. please post references to your PR in #282, its the main thread for the print issue

**Comment by Scope666** [comment]
> Hi @robbycandra .. we need to confirm the time stamp in the marlin firmware every one is using.. please post references to your PR in #282, its the main thread for the print issue

@guruathwal   I believe that PR is from 8 days ago, I looked and I have those changes in my build, yet the issue still remains... I can't be in Touch mode at all while Octoprint is printing or I get massive stuttering / zits / blobs.

**Comment by r0xbeat** [comment]
Where can I download this Version here?

**Comment by pdeswardt** [comment]
Is it possible to add the resume print function after power failure in Touch mode ? Currently after power interruption, there is no resume of print available ...

**Comment by guruathwal** [comment]
@r0xbeat currently you can get it from https://github.com/guruathwal/BIGTREETECH-TouchScreenFirmware until this PR is merged

@pdeswardt the resume print function is already in the TFT firmware, it only works when you print form sdcard on the TFT.

**Comment by Piscanc** [comment]
@guruathwal Please consider modding start print code to:
#define PRINT_START_GCODE "G28\nG29\nG0 Z20\n" // home and abl , raize Z to 20
It will prevent nozzle being on the print surface during heating
reasoning:
with the manual setup (no abl), most times position 0,0,0 means nozzle will be touching the bed.
several issues with that, if you also heat up in that position... heating nozzle with closed end can lead to clogged hotend with low quality parts, heating build surface to hotend temps in one spot isnt good it. 

other than that, kudos for your work :)

**Pull request merged**
