### PR TITLE
New icon update Hybrid Red Theme to #2054

### PR DESCRIPTION
**Pull request by AntoszHUN**
New icon for all display types.

- Icon name: calibration.bmp
- Updated displays: TFT24, TFT28, TFT35, TFT43, TFT50, TFT70

Sorry I'm late!

Made by: AntoszHUN

### CODE REVIEW

**Comment by oldman4U** [comment]
You are not late. You are the first. Thank you

**Comment by radek8** [comment]
Where did you come up with this icon?
Where is it used?

**Comment by oldman4U** [comment]
Pr 2054

**Comment by AntoszHUN** [comment]
> 
> 
> Where did you come up with this icon?
> Where is it used?

#2054

**Pull request merged**
