### PR TITLE
M03/M05 to control Laser_new main menu spindle icon_new laser power icons

### PR DESCRIPTION
**Pull request by ghost**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description
I have written new Laser.c and Laser.h to change the commands that control the laser power away from the fan control commands M106/M107 to M3/M5 as used commonly in the machining industry.

[TFT35_My Version.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4707797/TFT35_My.Version.zip)
I have also changed the Icon in the main screen for the spindle on/off and produced new icons to control setpoints for laser power in the laser menu

### Benefits

I can now use CAM applications that control the laser power with M03/M05

### Related Issues

 This also involved the following changes to TFT/SRC/USER/API/interfaceCMD.c -
:199 comment out reference to LaserSetSpeed
:211 comment out reference to LaserSetSpeed
:378 comment out reference to LaserSetSpeed
:388 comment out reference to LaserSetSpeed
:405 comment out reference to LaserSetSpeed
:390 comment out reference to SetLaserSendWaiting

Also commented out API/parseACK.c:344 reference to LaserSetSpeed

### CODE REVIEW

**Comment by jeffeb3** [comment]
Hey Dart!

@bigtreetech, I'm not sure where to have this conversation, but there is a corner of the Marlin community that uses Marlin for CNC milling and laser engraving. We are trying to work in some features for those functions into this screen firmware. Dart and Loki have been doing a good job with this using #defines, but with the new config.ini features, it makes more sense to do it that way. I have been working on a version that does just that, and I want to start the conversation about how to get these features into the mainline (so I don't have to keep merging destructive upstream changes, and the CNC version will keep up to date with new hardware BTT creates).

I have a first copy here: https://github.com/jeffeb3/BIGTREETECH-TouchScreenFirmware/tree/loki . 

The config.ini has two new settings: cnc_mode, which mostly disables stuff that is directly related to having an extruder and laser_mode, which turns the fan into lasers. I think it makes sense to also have a spindle option, and possibly an option to use M3/M5 or M106/M107. I think it makes sense to focus the settings in a parallel way to Marlin, where they allow EXTRUDERS=0, and LASER_SPINDLE options.

Having these merged into this repository would mean we would be able to pull down new hardware support you developed, and new bugfixes that you get in. It would also mean that our language files wouldn't end up with a bunch of merge conflicts whenever there was a new feature added upstream. I'm willing to put in a bit of work to make that happen. I'm willing to compromise a lot too. I am also willing to just keep our work in the V1Engineering fork.

So here's the question: Is getting CNC/Laser/Spindle features into the mainline something that interests BTT? If so, I can make a new PR (and I think we could close this one), and we can review and see what needs to change to get the first version into mainline.

**Comment by bigtreetech** [comment]
@jeffeb3  hello,  Thanks for your work,  We are very interested in this feature, but we don't have much energy to test/optimize at present. If there is a perfect PR to submit this feature, it will be the best, and we are willing to merge it.

**Comment by jeffeb3** [comment]
> @jeffeb3 hello, Thanks for your work, We are very interested in this feature, but we don't have much energy to test/optimize at present. If there is a perfect PR to submit this feature, it will be the best, and we are willing to merge it.

Thank you. I will work towards a consumable PR.

**Comment by digant73** [comment]
@dart1680, @jeffeb3 In order to avoid zombie PRs, could you please close the PR if no more needed?

**Pull request closed without merging**
