### PR TITLE
Restore "pause fix", extrude menu selected nozzle heat fix, polling fix

### PR DESCRIPTION
**Pull request by kisslorand**
### Description

Merging PR #1580 broke the pause fix made by PR #1588.
This PR restores pause fix, so Marlin parks the nozzle and stays there if `PARK_HEAD_ON_PAUSE` is defined or just simply pauses the print if `PARK_HEAD_ON_PAUSE` is not enabled.
Also fixes a bug in the Extrude menu. If the user selected the preheat option in the minimum extrusion temp warning popup, not the selected nozzle was preheated but the nozzle selected in the (Un)Load menu.

Includes [suggestions](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1598#issuecomment-771471930) by @digant73.

Includes [polling fix](https://github.com/luc-github/ESP3D-WEBUI/issues/158#issuecomment-771965307) by @luc-github.

### CODE REVIEW

**Comment by digant73** [comment]
in that case, please in config.ini add

PARK_HEAD_ON_PAUSE  (in Configuration_adv.h)

just after

ADVANCED_PAUSE_FEATURE (in Configuration_adv.h)

**Comment by kisslorand** [comment]
@digant73 
It's done.
There are more problems in the "language_hu.h" but I won't touch it (ex. "Load" is translated as a noun by the meaning of "the force of a weight", not as a verb). Mr. Antosz doesn't like someone else to edit/comment the "language_hu.h" file.

**Comment by digant73** [comment]
@kisslorand For hungarian translation I cannot help you for sure :-). Not a problem the comments were translated by a mistake.
Just a possible cleanup. the function setHotendMinExtTemp() is defined in menu LoadUnload.c and it is then used also by Extrude.c. Probably it's better to move it on the API Temperatue.c

**Comment by kisslorand** [comment]
Not possible because parameter cannot be parsed in a dialog's OK action and you have to send what nozzle do you want to heat. Your observation just made me discover a bug. In the Extrude menu the nozzle selected in the (Un)Load menu was heated.
I am working on fixing it.

**Comment by digant73** [comment]
does your PR fix 1528 and 1590? eventually, it should be it important to identify and fix that bug

**Comment by kisslorand** [comment]
I don't know because I cannot reproduce any of those bugs.

**Comment by bigtreetech** [comment]
@kisslorand Hello, Thank you very much for your help in the project. Do you have Facebook to communicate with? If it is not convenient to publish, you can send your contact information to our email “Tech@biqu3d.com”

**Pull request merged**
