### PR TITLE
Add option for fullscreen sim

### PR DESCRIPTION
**Pull request by MangaValk**
adds the option for fullsceen st7920 simulator

### CODE REVIEW

**Comment by Sthopeless** [comment]
a better replacement for the display text for sure. thank you so much @MangaValk

**Comment by thisiskeithb** [comment]
tft35-v3-fullscreen

That's fullscreen!

**Comment by bigtreetech** [comment]
Full-screen display will produce float numbers, stm32f105, stm32f207 do not have FPU, the speed of screen refreshing will be much slower, on TFT24 is not good.

**Comment by MangaValk** [comment]
Great to see my change merged :)

**Pull request merged**
