### PR TITLE
Fixed too thin ASCII fonts on TFT24/TFT28

### PR DESCRIPTION
**Pull request by guruathwal**
**Before:**
*Font in `Copy to SD Card root directory to update` folder*

Annotation 2019-11-26 080547

*Font in `Copy to SD Card root directory to update - Unified Menu Material theme` folder*

Annotation 2019-11-26 081258

**After:**

Annotation 2019-11-26 080419

### CODE REVIEW

**Comment by extesy** [comment]
@guruathwal can you post pre- and post- screenshots?

**Comment by guruathwal** [comment]
@extesy  Updated  preview please check..👍

**Comment by thisiskeithb** [comment]
Can these be updated to use the same [Ubuntu font](https://design.ubuntu.com/font/) that’s used for the TFT35?

Users will appreciate the sans serif font.

**Comment by guruathwal** [comment]
@thisiskeithb like this?
Annotation 2019-11-26 200600

**Pull request merged**
