### PR TITLE
Change ENC_ACTIVE_SIGNAL logic to disable encoder in Marlin firmware when TFT is not in Marlin mode.

### LINKED ISSUE #680: When encoder used in touch mode to adjust values, feed rate changes as well.
As the title says. I have noticed that If I use the encoder knob to adjust values such as the fan speed in menus in the touch screen mode, it's also cranking the feed rate up and down. So say I crank my fan up from 0 to 100% in the touch menu, if I then go back to LCD mode, the FR will show as something like 175%. It seems like the encoder is being passed to marlin regardless of which mode the screen is in.

EDIT: In fact, it adjusts the feed rate in touch mode too, regardless of what menu I'm in. If I turn the encoder on any menu, then back out to the main touch screen menu, the feed rate has been cranked up, regardless of what I was using it for. I like to use the encoder to move the axis quickly so this is annoying.

### LINKED ISSUE #1045: [BUG] Turning knob in any (sub)menu will result in speedchange
### Description

Turning the knob to change XYZ Position, Heat etc. will result in also changing the speed (%) parameter

### Steps to reproduce

1. Go into Bed Heating
2. Use knob to set Bed Temp to 60C
3. Look at the Speed rate 
4. See that Speed rate has also changed 

**Expected behavior**
Speed rate should not change unsell iam in the Speed rate menu

**Actual behavior**
Speed rate changes

### Hardware Variant
TFT35 V3 Ender3
### TFT Firmware Version & Main Board Firmware details
2.0.26 - just updated, still same bug

### Additional Information
Configuration.h https://pastebin.com/7YZD1hi0

### LINKED ISSUE #1206: PID TUNING INCREASE OR LOW PRINT SPEED / FAN SPEED BTT TFT35 E3 V3.0
When printing, and adjust live PID tunning also affect at the print speed too, like the fan speed  make the same issue......
 BTT TFT35 E3 V3.0
UPDATED WITH THE LAST FIRMWARE

### PR DESCRIPTION
**Pull request by guruathwal**
- Change `ENC_ACTIVE_SIGNAL` logic to disable encoder in Marlin firmware when TFT is not in Marlin mode. Details in https://github.com/MarlinFirmware/Marlin/pull/19796
- clean-up
- Add stale bot config to manage old abandoned issues. @bigtreetech Needs installing stale app for the repository from here: https://github.com/apps/stale

This will fix #680 after https://github.com/MarlinFirmware/Marlin/pull/19890 is merged in marlin firmware.
Resolves #1206 , Resolves #1045

### CODE REVIEW

**Comment by traffic-light** [comment]
Cool! Good job!

**Review by digant73 — CHANGES_REQUESTED** [review]
hi,
BabystepControl.c and Babystep.c have been modified in my PR. The changes you made are not needed (e.g. babyInitZOffset is no longer present now). Also BabystepControl.c follows exactly the same indentation I applied to all the other files I worked to. It's a personal style (e.g. I always separate by an empty line any function related to gcodes invocation, variable definition etc... It should make the code more readable for anyone)

**Comment by oldman4U** [comment]
Resolves #1206

**Comment by bigtreetech** [comment]
Thanks for your work! EXP1 & EXP2 can also simulate the interface of LCD2004. If Marlin mode is set to LCD2004, this function will not work normally.

**Comment by radek8** [comment]
Correction of encoder behavior in touch mode when using SKR1,4 and TFT32 E3 boards works perfectly.
Thank you

**Pull request merged**
