### PR TITLE
Added M73 and M117 support for remaining print time

### LINKED ISSUE #1891: [FR] Show remaining time
Would be possible to add the remaining time during a print?

### PR DESCRIPTION
**Pull request by digant73**
**IMPROVEMENTS:**
* added M73 support printing from TFT:
  * format "M73 PXXX RXXX" (P: actual progression of print (%) - R: remaining time (minute)
* added M117 support for remaining print time printing from TFT:
  * format "M117 Time Left XXhYYmZZs"
* added action notification support for remaining print time printing from onboard SD
  * format "notification: Time Left XXhYYmZZs" (the notification is due to gcode "M117 Time Left XXhYYmZZs")
* autodetect M115 Cap:BUILD_PERCENT:. If the capability is supported by Marlin, when printing from TFT the M73 gcode is forwarded to Marlin
* improved progress bar layout displaying also 10% progress markers. It helps in case progress value cannot be displayed (not enough space on screen available) on screen (such as for TFT43/TFT50 having a low resolution)
* some code cleanup

If gcode M73/M117 or action notification for remaining print time is intercepetd and its value is greater than 0, then that information is displayed on the Time area in the Printing menu.
If gcode M73 P is intercepted, then progress value will be updated only by further gcode M73 P (controlled by slicer). That means the update performed by TFT has no more effect.
The print progress percentage value has been moved on the left of the progress bar. It was needed to free space for remaining time in Time area. Furthermore, that location is probably better. they are different representations of the same information (a print progress percentage).

**NOTE:** this PR is a review of PR #1410 started by belese. Thanks belese for your original work!

resolves PR #1410
resolves #1891

**PR STATE:** ready to merge

**LAYOUT FOR TFT DIFFERENT THAN TFT43/TFT50:**

IMG_20210529_175356

IMG_20210529_175914

**LAYOUT FOR TFT43/TFT50 (emulated on my TFT28):**

IMG_20210529_182322

IMG_20210529_182419

### CODE REVIEW

**Comment by radek8** [comment]
Can you also comment on the required Merlin settings (LCD_SET_PROGRESS_MANUALLY) in the config.ini files?

**Comment by digant73** [comment]
I can. Although that setting is needed printing from onboard SD while the main purpose of this PR was to add support printing from TFT

**Comment by radek8** [comment]
> I can. Although that setting is needed printing from onboard SD while the main purpose of this PR was to add the support printing from TFT

Yes. but I think if you don't enable it in Marlin and there is an M73 command in the print file, Marlin will report an unknown command.

**Comment by digant73** [comment]
it is, but M73 enabled in Marlin does not provide any support to M73 implemented on TFT fw. config.ini should report settings needed in Marlin to allow the TFT fw to provide some fetaures. In this case M73 enabled in Marlin is not required by TFT fw. Marlin does not provide any kind of ack to TFT fw to inform TFT a progress or remaining time change

**Comment by radek8** [comment]
Good job.
I installed on the display. Time message M73 Rxxx and also M117 work.
I will test tomorrow while printing.

**Comment by radek8** [comment]
I'm looking at the generated files from Cura and
PrusaSlicer.
Both add a print length to the generated file as a comment.
If this information was used, the time until the end of printing could also be read, but the countdown would have to start after the printer has warmed up.

Cura (time in seconds)
; TIME: 1489

PrusaSlicker
; estimated printing time (normal mode) = 20m 59s

It is also without activated M73.

**Comment by radek8** [comment]
Hello
I tested the PR
It works great.
I recommend merging :-)

Some findings to set Cura.
Allows you to set:
M73 Pxxx print run. It works without problems.
M73 Rxxx time to end, allows to set repeat 15s, 30s, minute, layer.
The ideal setting is minute, because M73 it can only set whole minutes. Otherwise, there are unstable transcripts of the seconds value.

M117 same options as the previous one, but the value is sensitive seconds and no overwrites occur on any option. But even in this case, the choice of minute is ideal.


image

image

**Comment by sarvenn** [comment]
Hi,
What should be the proper configuration setting for this function to work correct?
For example I had change my settings like below.
I disabled print job timer auto start.
I added M75 at the end of my start print script in my slicer (PrusaSlicer).
I added M77 ant the beginning of the end print script in my slicer.
I wanted to exclude the time for waiting the HE and HB heating but it didn't work as I expected in touch screen mode. I haven't tried this PR yet.

So, other users may also be interested in the marlin side settings to work correct with this PR and touch screen mode.

image

**Comment by digant73** [comment]
@radek I see from your screenshot that M117 should support also progress percentage. Could you provide the format of m117 in a gcode file and a file sample? Currently for m117 only remaining time is parsed

**Comment by radek8** [comment]
No, Cura does not support the M117 progress percentage.
In both cases it is M73 Pxx.

M73

image

M117

image

**Comment by digant73** [comment]
@radek8 ah ok thanks. so no change is needed

**Comment by Guilouz** [comment]
@digant73 @radek8  So what is the best to use ? M73 or M117 ?

**Comment by radek8** [comment]
If you set the repeat frequency per minute, both options are equally functional when printing from the SD card slot to the TFT.
If you want to print from the touch screen from the on board SD slot, the M117 is a better choice.
If you want to print from Merlin and enable the M73 option in Merlin, then it is better to use M73.

**Comment by radek8** [comment]
@oldman4U, can you mention the use of M73 and M117 in connection with the remaining time in the manual on the title page after merging PR?
Thank you

**Comment by radek8** [comment]
@digant73 
I had another thought.
The remaining time is accurate when the print speed is set to 100%.
If the print speed changes, the time will no longer correspond to reality.
If the print speed were controlled and the time reported via M73 (M117) was increased or decreased accordingly by the same number of percent, it would be much more accurate even when the print speed was changed.
Unfortunately, I don't know how laborious this adjustment is.

**Comment by radek8** [comment]
It would then be enough to change the print speed, wait for the next update with the M73 (M117) index and I would immediately see how much s e shorten the print at the given setting

**Comment by oldman4U** [comment]
Hi radek8

What exactly should be the text?
The same problem applies to filament use, when you change the Flow value during print. It shows the amount of filament which would have been used with 100% Flow setting during the whole print.

**Comment by kisslorand** [comment]
> It would then be enough to change the print speed, wait for the next update with the M73 (M117) index and I would immediately see how much s e shorten the print at the given setting

That would be true in case of zero deacceleration and infinite acceleration.

**Comment by Guilouz** [comment]
Just try your PR, all is working fine (print time, time left, progress bar) but I don't have percentage text to the left
 of the progress bar.
 
 I use TFT43 for info.

**Comment by digant73** [comment]
@Guilouz probably for TFT43 the rectangle where the text is displayed is not enough big. I will try to increase the height.

@radek8, @oldman4U, @kisslorand as said by kisslorand the solution is easy. It is just enough to divide the time value provided in the gcode by the speed multiplier. E.g. time = 60 sec and speed multiplier = 0,5 (50%) then remaining time = 60 / 0,5 = 120

**Comment by Guilouz** [comment]
@digant73 Not sure text can be added between two icons, fonts on TFT43/TFT50 is very large :

016D6BB6-694E-4BC2-96C3-49ADCE5B67DF

**Comment by radek8** [comment]
@digant73 
It would be great. So can you add a time correction according to the percentage of print speed?
Thank you

**Comment by radek8** [comment]
@Guilouz 
Nice icons :-)

**Comment by Guilouz** [comment]
> @Guilouz
> Nice icons :-)

Thanks. I created them in blue for my Sidewinder X1 and in red for my CR-10s Pro :)

**Comment by digant73** [comment]
@radek8 added the speed factor to  the remaining time formula. I didn't test it (I'm at office now) but it should work
@Guilouz I see. Probably the vertical space between the picons should be reduced

**Comment by kisslorand** [comment]
> Probably the vertical space between the picons should be reduced

That would not be enough. Just check the height of the fonts. 

Maybe put back the percentage where it was and add a config to show either the elapsed or the remaining time.

**Comment by radek8** [comment]
Thank you, it was speed :-)
I'm also not at the printer's, but I'll test it tonight when I get home.

**Comment by radek8** [comment]
If the icon were edited, percentages could appear in the center of the circle

image

**Comment by radek8** [comment]
Perhaps even the percentage number might not be displayed on some displays (if they can't do it due to the resolution), it would be enough if there were indices of 10% on the progress bar, which could then be easily read according to the position.

**Comment by Guilouz** [comment]
Or maybe rotating info with time/time remaining and percentage like speed and flow ?

**Comment by digant73** [comment]
IMHO the solution from radek is the better one. The alternating text is too much confusing (already tested and discarded). Also the progress in the time icon was more a workaround than the better solution. For TFT variants were text cannot be provided, I think it could be better, and more easy, to use the progress bar (the original one starting from left to right) reporting some markers (every 10%). The markers can be applied also to the TFT variants were the text can be dispalyed. For me both the elapsed and remaining time should be dispalyed (the progress percentage is an extra info that can be sacrified if progress bar with markers could be available)

**Comment by Hitamku** [comment]
> Thank you, it was speed :-)
> I'm also not at the printer's, but I'll test it tonight when I get home.


Until now I have not managed to display the remaining time on my Biqu B1. Is there anything to change in the dimarlin? maybe this has an effect?
Configuration_adv.h
 // # define USE_M73_REMAINING_TIME // Use remaining time from M73 command instead of estimation

**Comment by digant73** [comment]
@Hitamku you don't need to enable any setting in Marlin if you print from TFT's SD or USB.
Printing from onboard SD needs LCD_SET_PROGRESS_MANUALLY enabled in Configuration_adv.h but only time provided by M117 is reported to the TFT while time provided by M73 is not reported to the TFT

**Comment by kisslorand** [comment]
Why it is so important to have both elapsed and remaining time?
How could it be more important to have both than the numerical representation of the percentage?

**Comment by Hitamku** [comment]
> @Hitamku you don't need to enable any setting in Marlin if you print from TFT's SD or USB.
> Printing from onboard SD needs LCD_SET_PROGRESS_MANUALLY enabled in Configuration_adv.h but only time provided by M117 is reported to the TFT while time provided by M73 is not reported to the TFT

Inkedunnamed_LI

But all I've tried, and I can't show it until now. I wonder if it only applies to Mks

**Comment by radek8** [comment]
> Why it is so important to have both elapsed and remaining time?
> How could it be more important to have both than the numerical representation of the percentage?

For me, information about print length and time to finish is more important than accurate percentage information. All I need is an estimated percentage.
If I print the pyramid, when I print 2/3 (66%) of the pyramid, I will be at 50% of the print height.
Percentages are just gross information and a bar indicator is enough.

**Comment by kisslorand** [comment]
...and how does elapsed time help you in that case better than the percentage?

**Comment by radek8** [comment]
> > @Hitamku you don't need to enable any setting in Marlin if you print from TFT's SD or USB.
> > Printing from onboard SD needs LCD_SET_PROGRESS_MANUALLY enabled in Configuration_adv.h but only time provided by M117 is reported to the TFT while time provided by M73 is not reported to the TFT
> 
> 
> 
> But all I've tried, and I can't show it until now. I wonder if it only applies to Mks

You need to use this PR and Print a file that has generated M73 or M117 indexes

**Comment by radek8** [comment]
> ...and how does elapsed time help you in that case better than the percentage?

For me, time is a real quantity by which I know how much it measures.
The percentage is only virtual and 10% has a different length of time for each print.
But 1 hour is still 1 hour.
If there is your tape indicator with indexes, the percentages will also be available. The number to the left of the tape can also remain there, only low-resolution displays will not display them, just as the 7 "display also has a different icon layout and no one minds.

**Comment by digant73** [comment]
@kisslorand IMHO they both are related to time and so better fit in the Time icon. They provide specular information while at the end percentage value is the same information provided by progress bar but in a different way. Clearly, if possible both progress representation are welcome but if some TFT variants don't allow to provide both at the same time, I would prefer the progress bar (visible also from distance). With the small improvement (adding a 10% marker) it will be more than an acceptable solution (you will simply miss the detail only in a 10% window). In any case I need to test it. Obviously there is always time for improvements in further PRs. At the end the main target of this PR is to add M73 and M117 support

**Comment by Hitamku** [comment]
> You need to use this PR and Print a file that has generated M73 or M117 indexes



> > > @Hitamku you don't need to enable any setting in Marlin if you print from TFT's SD or USB.
> > > Printing from onboard SD needs LCD_SET_PROGRESS_MANUALLY enabled in Configuration_adv.h but only time provided by M117 is reported to the TFT while time provided by M73 is not reported to the TFT
> > 
> > 
> > But all I've tried, and I can't show it until now. I wonder if it only applies to Mks
> 
> You need to use this PR and Print a file that has generated M73 or M117 indexes

I used Cura, and enabled a remaining time script. I tried M73 or M117 to print a file. But the results are as drawn

**Comment by radek8** [comment]
> 
> I used Cura, and enabled a remaining time script. I tried M73 or M117 to print a file. But the results are as drawn

You didn't use this PR

**Comment by kisslorand** [comment]
@digant73
I am all in for new features but not by removing old ones.
Till this time noone had any problem with the numeric percentage. Since when it became an unwanted option?

**Comment by Hitamku** [comment]
> > I used Cura, and enabled a remaining time script. I tried M73 or M117 to print a file. But the results are as drawn
> 
> You didn't use this PR
> 
> What is your display?

I'm sorry, I don't really understand this. Can you tell me what it is like? I'm using a BTT B1 TFT35 V3.0 screen

**Comment by radek8** [comment]
Sometimes old things have to make a better place.
The percentages remain, but in their place.

**Comment by radek8** [comment]
@Hitamku 
[BIGTREE_TFT35_V3.0_B1.27.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6555032/BIGTREE_TFT35_V3.0_B1.27.x.zip)

**Comment by kisslorand** [comment]
@radek8 
Please make me understand why elapsed time is more important than numeric percentage.
I mean not for you , but for everybody. Why is better to everybody to see the elapsed time and not the numeric percentage.

**Comment by Hitamku** [comment]
> @Hitamku
> [BIGTREE_TFT35_V3.0_B1.27.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6555032/BIGTREE_TFT35_V3.0_B1.27.x.zip)


O yeah, this just worked. Thank you very much for helping me. What's missing here, can you tell me?

**Comment by radek8** [comment]
But percentages can stay there, as Digant73 wrote.
Let him finish the job and then we'll try and express ourselves.
Alternatively, then suggest a better solution.

**Comment by radek8** [comment]
> > @Hitamku
> > [BIGTREE_TFT35_V3.0_B1.27.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6555032/BIGTREE_TFT35_V3.0_B1.27.x.zip)
> 
> O yeah, this just worked. Thank you very much for helping me. What's missing here, can you tell me?

This is still a proposal for modification, it is not yet included in the main FW

**Comment by kisslorand** [comment]
@radek8 
I do not have a solution to have all 3 elements displayed in all TFT variants.

**Comment by Hitamku** [comment]
@radek8 
Okay, I got it. I will enjoy it first and try to compile my FW

**Comment by radek8** [comment]
Let the digant finish it, after merging the changes, propose a change and bigtreetech will decide what he likes.

**Comment by digant73** [comment]
@kisslorand it's not an unwanted option also for me. I simply moved the percentage value close to the progress bar just because it seems to me more clear to read than to have a look to the progress bar and then to the time area to see the numeric representation and it also allowed to provide the new remaining time info at the same time. Also decoupling time and progress reduced the redraw of the time icon and inner text (the drawing of progress value does not need to redraw the entire Time icon). Unfortunately a compromise emerged in case there is no space to display the progress value. As I said, in this moment I'm more interested that the main purpose of this PR is working properly with a minimun change on the UI. After that, further improvements on the featture and UI are welcome.

**Comment by kisslorand** [comment]
I really like the numeric percentage in front of the progress bar. Actually I wanted to do that myself when I made the progress bar.
What I do not like is the lack of numeric progress percentage (regardless of its position) on some TFT variants.
It seems I've been misunderstood (again).

**Comment by digant73** [comment]
@kisslorand yes I understood. Same layout on all TFT variants is the preferred choice for developers first more than it is for all users, We will see how to improve the UI in further PRs for sure.

**Comment by radek8** [comment]
> @radek8 added the speed factor to the remaining time formula. I didn't test it (I'm at office now) but it should work


Tested and works as expected.
As the print speed increases, the time shortens.
As the print speed decreases, the time increases.

**Comment by oldman4U** [comment]
Question. Do I understand it right that the percent value shown depends on the number of layers already printed? So when you print a pyramid 10cm high you see 50% at 5cm print hight even the time it will take to finish the print will be substantially lower?

**Comment by radek8** [comment]
In my opinion, the percentages are calculated according to the filament consumed and not by the layer.
For example, when printing a 10cm pyramid, you will be at a height of 5cm for 75% of the print.
But maybe I'm wrong. Put something in the press that has a big basic and look at the percentage in the middle :-)

**Comment by kisslorand** [comment]
Percentage is calculated based on the current position in the gCode file.
It reflects how many gCodes were executed.

**Comment by oldman4U** [comment]
Same as progress bar?

**Comment by kisslorand** [comment]
> For example, when printing a 10cm pyramid, you will be at a height of 5cm for 75% of the print.

If you print a 10 cm tall pyramid without infill, bottom layer and support, you'll be at 50% at 5cm.

**Comment by radek8** [comment]
@kisslorand
 It looks logical, there is the same number of steps so 5cm is 50%.
But if the progress is 50%, printing will not be in the middle of printing time.
Because in the upper half of the pyramid the steps will be shorter and therefore the printing time will be significantly shorter.

**Comment by kisslorand** [comment]
> But if the progress is 50%, printing will not be in the middle of printing time.
> Because in the upper half of the pyramid the steps will be shorter and therefore the printing time will be significantly shorter.

I explained how the percentage shown is calculated in this FW. I never said it will reflect the elapsed time percentage.
Sure, it can be implemented to reflect the elapsed time percentage if the elapsed and remaining time are known.

**Comment by radek8** [comment]
The 50% progress does not say that I am halfway through the required time, nor that I have consumed half of the filament.
50% say I'm in the middle of a file I'm printing.
@kisslorand  Why is an exact numerical value so important to you?

**Comment by kisslorand** [comment]
Let's say I got the hang of it.
What I mean is that I mostly print things that I designed myself so I kind of get used to approximate time and filament based on that percentage.
I print mostly technical stuff with regular 3D shapes. Of course, on the BabyYoda I wouldn't know how to estimate things based on that percentage.
Anyway, I usually take notice of the print time and filament length needed in the slicer.

**Comment by radek8** [comment]
If the progress is now displayed according to what Cura generates to M73, it may be different, for example according to the fiber consumed. It will depend on how Cura calculates it.
But basically it's just in terms of normal shape, the results will always be similar and we will forgive the pyramid :-)

**Comment by radek8** [comment]
@kisslorand 
This solution would be acceptable to you.

image

**Comment by oldman4U** [comment]
Sorry in case I missed the information, but the progress bar is based on the same information as the % or on something different?

**Comment by Hitamku** [comment]
@radek8 
I have tried it for printing multiple files and for reduction and speed increase it works fine. Maybe if I could give a suggestion when I finished printing the screen would show something like that, maybe it could be with the word Time, Total, Done or something else

IMG-1734

**Comment by radek8** [comment]
image

**Comment by Hitamku** [comment]
@radek8 
Yes I know that, but before it was the total time and the percentage there it's just that it looks empty once done

IMG-1734 (1)

**Comment by sarvenn** [comment]
My suggestions:
alternating time elapsed and time left at time display window.
Progress percentange and progress bar below just like above picture.

**Comment by radek8** [comment]
@sarvenn 
do you want to test the current PR?
[BIGTREE_TFT35_V3.0_E3.27.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6564201/BIGTREE_TFT35_V3.0_E3.27.x.zip)

**Comment by oldman4U** [comment]
I recommended alternating also but the problem is that you need something (text, color or symbol) which tells what is shown on screen or in this case you would have to show it longer so you see if the time counts up or down.

The simplest thing is to keep everything like it is and to replace the percent with the remaining time in case this information is available. Since kisslorand introduced the progress bar, the percent value is redundant.

**Comment by radek8** [comment]
Everything is available in this PR.
Thank you digant73.
Oldman Just try it :-)

**Comment by bttguy** [comment]
This is such a great addition to the TFT firmware, thank you the work!

**Comment by radek8** [comment]
@digant73 
TFT 43 and TFT50 have the same resolution, so I will have the same problem.
you should therefore include the TFT50 in the alternative look.

**Comment by radek8** [comment]
I might ask stupidly, but wouldn't it be possible to move the bottom row of icons a few pixels lower on the TFT43 to create space above the bottom icon?

**Comment by digant73** [comment]
> I might ask stupidly, but wouldn't it be possible to move the bottom row of icons a few pixels lower on the TFT43 to create space above the bottom icon?

No, those icons are compliant to standard menu. The alternative for progress value on TFT43/TFT50 can be on notification area. So append the progress value as prefix to file name. E.g. "27% - Cura_sample.gcode"

**Comment by digant73** [comment]
closing and reopening the PR due to not working rebase

**Pull request closed without merging**
