### PR TITLE
It was missed

### PR DESCRIPTION
**Pull request by AntoszHUN**
A language_en.ini was left out. There’s so much of it already that I didn’t notice. I don't know why so much. But there must be a reason.

By: AntoszHUN

### CODE REVIEW

**Comment by oldman4U** [comment]
You mean why there are so many language files?

**Comment by AntoszHUN** [comment]
> You mean why there are so many language files?

Why do I need 3 locations for INI file?

**Comment by oldman4U** [comment]
One in each Icon theme. Otherwise the user has to jump from one folder to another. But this would also be possible. Then the question is why this has to be the case for font and config.ini also.

**Comment by AntoszHUN** [comment]
> One in each Icon theme. Otherwise the user has to jump from one folder to another. But this would also be possible. Then the question is why this has to be the case for font and config.ini also.

I see. :)

**Pull request merged**
