### PR TITLE
Improve multiline text display to respect words

### PR DESCRIPTION
**Pull request by guruathwal**
- Improve multiline text display to respect words. Long sentences/strings will now be split into multiple lines without breaking words that are difficult to read.

### CODE REVIEW

**Comment by Guilouz** [comment]
Why this string #define STRING_STATUS_SCREEN was removed from translation files / Language.inc and not from language_keywords.h ?

This string is not used anymore ?

**Comment by guruathwal** [comment]
yes

**Comment by Guilouz** [comment]
You have also missed to remove #define STRING_STATUS_SCREEN in language_cn.h

**Comment by kisslorand** [comment]
In some cases new line is intended. Please take this into account when removing "\n".

**Comment by guruathwal** [comment]
The display of lines is the same like it would display on a PC.

**Pull request merged**
