### PR TITLE
fix missing E stepper current

### PR DESCRIPTION
**Pull request by rebel1**
for TMC in parseACK.c

### CODE REVIEW

**Comment by AntoszHUN** [comment]
Hi! What error does this fix?

**Comment by radek8** [comment]
The extruder motor current is not displayed
Corrects this problem.

**Comment by rebel1** [comment]
> Hi! What error does this fix?

The current for the E stepper is in the feature menu always 0.00 without this fix

**Comment by thisiskeithb** [comment]
In the future, please fill out the [PR template](https://raw.githubusercontent.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/master/.github/pull_request_template.md) when submitting PRs so 1. It's clear what you're submitting and 2. What benefits it brings:

```md
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

<!--

We must be able to understand your proposed change from this description. If we can't understand what the code will do from this description, the Pull Request may be closed at the maintainers' discretion. Keep in mind that the maintainer reviewing this PR may not be familiar with or have worked with the code recently, so please walk us through the concepts.

-->

### Benefits

<!-- What does this fix or improve? -->

### Related Issues

<!-- Whether this fixes a bug or fulfills a feature request, please list any related Issues here. -->
```

**Comment by guruathwal** [comment]
This is technically a Marlin Firmware issue, as the M503 response sent by Marlin firmware was missing EOL in Stepper current settings in Bugfix Branch, which got fixed in https://github.com/MarlinFirmware/Marlin/pull/17893

**Comment by bigtreetech** [comment]
Hello. After https://github.com/MarlinFirmware/Marlin/pull/17893, has this issue been fixed? and should this PR be closed instead of merged?

**Comment by rebel1** [comment]
With Marlin bugfix_2.0.x this issue is fixed.

**Pull request closed without merging**
