### PR TITLE
Added MKSTFT35V1_0

### PR DESCRIPTION
**Pull request by darkspr1te**
Added MKS TFT35 V1 board support 
  Complete support for this board in it's default configuration 
Added for stm32f4xx boards SDIO_DMA/Polling support for SDCARD
 Usable on other boards - fully configurable via .h file , does not conflict with existing DMA usage 
Added stm32f4xx boards I2C Support for EEPROM flashStore (polling) 
  Saves wear and tear on boards with I2C eeproms - DMA not implemented to save DMA channels 
Added support for ILI9488 via FSMC DMA->SPI 
 FSMC can now be configured on board by board basis 
Added STMFLASH support for flashStore for F4xx boards with flash region calculations to support various sized bootloaders 
 Easier to move params flashStore location without referring to datasheet 

Known bugs 
minor graphics corruption on lower portion of lcd after 5 minutes , appears to be info text of unknown origin
touch calibration fails 90% of the time unless user shifts the last touch to 1cm below and to the left of last center dot - fix in progress.
image

### CODE REVIEW

**Comment by oldman4U** [comment]
Hi.

I believe you can define tickets to be close automatically once the issue is solved. Could you please add this ticket, so it is close automatically.

Thank you

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/589

**Comment by traffic-light** [comment]
Resolves #589

**Comment by chrisdaloa** [comment]
Sorry I don't understand, how can I compile for mks-tft35? Thanks.

**Comment by darkspr1te** [comment]
> Sorry I don't understand, how can I compile for mks-tft35? Thanks.

load into platformio, select Default button at bottom to produce dropdown menu , 
image
then select env:MKS_35_V1_0 , 
this will select the correct build options. please note that you may need to switch bootloader or encrypt the firmware to work directly with the factory bootloader, more info here https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/589#issuecomment-691439259

**Comment by chrisdaloa** [comment]
> 
> 
> > Sorry I don't understand, how can I compile for mks-tft35? Thanks.
> 
> load into platformio, select Default button at bottom to produce dropdown menu ,
> image
> then select env:MKS_35_V1_0 ,
> this will select the correct build options. please note that you may need to switch bootloader or encrypt the firmware to work directly with the factory bootloader, more info here [#589 (comment)](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/589#issuecomment-691439259)

I've done it but there is no the MKS_35_V1_0 declaration in platformio.ini :)

;BIGTREE_TFT35_V1_0
;BIGTREE_TFT35_V1_1
;BIGTREE_TFT35_V1_2
;BIGTREE_TFT35_V2_0
;BIGTREE_TFT35_V3_0
;BIGTREE_TFT35_E3_V3_0
;BIGTREE_TFT43_V3_0
;BIGTREE_TFT50_V3_0
;BIGTREE_TFT70_V3_0
;BIGTREE_TFT28_V1_0
;BIGTREE_TFT28_V3_0
;BIGTREE_TFT24_V1_1
;MKS_32_V1_4
;MKS_32_V1_4_NOBL

**Comment by darkspr1te** [comment]
you need a 3.3v serial adapter to program  the mcu , 
heres a windows app to program the mcu , https://github.com/turingo/stm32ss/tree/master/tools/FlyMcu ,
i cant find the guide for it right now, will add later

**Comment by chrisdaloa** [comment]
> 
> 
> you need a 3.3v serial adapter to program the mcu ,
> heres a windows app to program the mcu , https://github.com/turingo/stm32ss/tree/master/tools/FlyMcu ,
> i cant find the guide for it right now, will add later


ok, so

first: I program the MCU with the bootloader (I'm looking for the guide)
second: I compile the firmware and I insert the firmware (and others folders) in the sd, then turn on the display

But I need to know how to insert the MKS_35 declaration in platformio.ini, it misses. Can you help me with this?

Thanks

**Comment by darkspr1te** [comment]
the firmware (btt touch firmware ) should be placed on the root of the sdcard named mktft35.bin , to compile the firmware in platformio you must switch from default environment to mktft35 build option . you can either select the default button at the bottom of the screen and then select env:mkstft35 BL (bl is bootloader, no_bl is no bootloader /direct flash for development ) 
image

 or you can edit platformio.ini and change 
default_envs = BIGTREE_TFT35_V3_0 
to default_envs = MKS_35_V1_0

**Comment by chrisdaloa** [comment]
OK, if I flash now with the MKS_35_V1_0 (including BL), is it possible then restore the original firmware? In the PCB of display there are not tx and rx pins.

**Comment by darkspr1te** [comment]
all files to restore to factory are here https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/589#issuecomment-691439259

**Comment by chrisdaloa** [comment]
> 
> 
> all files to restore to factory are here [#589 (comment)](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/589#issuecomment-691439259)

Yes I know, but the files to restore original firmware is hex,  I need bin to upload via sd card

**Comment by darkspr1te** [comment]
> > all files to restore to factory are here [#589 (comment)](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/589#issuecomment-691439259)
> 
> Yes I know, but the files to restore original firmware is hex, I need bin to upload via sd card

you need a bootloader hex file, then use the factory mkstft firmware from the mks github to restore the main firmware, that is a bin file, bootloader hex file can be uploaded via serial/flymcu or stlink/stlinkv2 adapter

**Comment by chrisdaloa** [comment]
> 
> 
> > > all files to restore to factory are here [#589 (comment)](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/589#issuecomment-691439259)
> > 
> > 
> > Yes I know, but the files to restore original firmware is hex, I need bin to upload via sd card
> 
> you need a bootloader hex file, then use the factory mkstft firmware from the mks github to restore the main firmware, that is a bin file, bootloader hex file can be uploaded via serial/flymcu or stlink/stlinkv2 adapter

I have 2 issue:

1. on the display pcb there are no pins TX e RX and no other PINS. So where could I connect de adapter? :)

2. I copied alla BTT files on SD but nothing appens on turn on, maybe I have to upload the bootloader before? But how can I do it if the display have no pins?

**Comment by darkspr1te** [comment]
> > > > all files to restore to factory are here [#589 (comment)](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/589#issuecomment-691439259)
> > > 
> > > 
> > > Yes I know, but the files to restore original firmware is hex, I need bin to upload via sd card
> > 
> > 
> > you need a bootloader hex file, then use the factory mkstft firmware from the mks github to restore the main firmware, that is a bin file, bootloader hex file can be uploaded via serial/flymcu or stlink/stlinkv2 adapter
> 
> I have 2 issue:
> 
> 1. on the display pcb there are no pins TX e RX and no other PINS. So where could I connect de adapter? :)
> 2. I copied alla BTT files on SD but nothing appens on turn on, maybe I have to upload the bootloader before? But how can I do it if the display have no pins?
> 
> edit: I attach the picture of the display board
> 
> immagine

Thanks because that is NOT a MKS TFT 35 V1 board so non of the support I have provided is valid for a product that is different.

**Comment by chrisdaloa** [comment]
Yes it is, it works well with the MKS firmware. It's a clone rebranded whitout usb and sd on board.

**Comment by darkspr1te** [comment]
> Yes it is, it works well with the MKS firmware. It's a clone rebranded whitout usb and sd on board.

ok, but sadly that means it's not pin for pin compatible with our firmware, as both my bootloader and my additions to the code require the sd-card/eeprom and i2c flash for mkstft35 v1 boards, is there any schematic ? diagram? i've no clue where the tx/rx ext is as it's not the board i wrote the code for and i personally dont have a sample to confirm with.

**Comment by chrisdaloa** [comment]
> ok, but sadly that means it's not pin for pin compatible with our firmware, as both my bootloader and my additions to the code require the sd-card/eeprom and i2c flash for mkstft35 v1 boards, is there any schematic ? diagram? i've no clue where the tx/rx ext is as it's not the board i wrote the code for and i personally dont have a sample to confirm with.

I only know that if I put the MKS-TFT35 firmware in the SD, it works, so I think it's the same connection as MKS-TFT35.

I compiled BTT firmware with bootloader, I put it on the sd, turn on but nothing appened. I also renamed the .bin like the MKS firmware, turn on but nothing appened.

Maybe I should use the BTT in NO-BL version.

May I ask you what's the instructions to load the BTT firmware in MKS-TFT35 standard? It's necessary to upload the bootloader before?

thanks a lot

**Comment by darkspr1te** [comment]
on the official MKStft35 the firmware is encrypted using the MKS-robin encryption, this is why there is a new bootloader in my repo, it provides the system with encoded or non  encoded firmware, i dont know yet if yours also has that encoding enabled ( many other mks dont) , the new bootloader is flashed using the wifi TX/RX pins or stlink/jtag pins. 
for the official bootloader the flash filename for the sd-card is mkstft35.bin , on my bootloader it uses same file for encrypted firmware and a different filename for non encrypted. instructions can be found here https://github.com/darkspr1te/mkstft35_V1_open_bootloader

**Comment by chrisdaloa** [comment]
ok, sorry but I don't understand:

supposing I would trie to load the BTT firmware using the original bootloader, I compile the BTT firmware then I have this files/folders

immagine

How can I convert this to the format accepted by mks?

files name, folder names and image extensions are different from the compiled mks firmware

**Comment by darkspr1te** [comment]
"if" its the same as a real mkstft35 device , the firmware has to be placed in the root of the sdcard named mkstft35.bin along with the tft35 folder renamed MKS  and config.ini , it may or may not require encryption, I dont know, just guessing at this point.

**Comment by chrisdaloa** [comment]
I tried but nothing happened

**Comment by darkspr1te** [comment]
please try Robin_nano35.bin as the firmware filename and let me know.

**Comment by karabas2011** [comment]
Hi, any chances to solve the problems with EEPROM and touchscreen calibration?

**Pull request closed without merging**
