### PR TITLE
Improve Cancel Gcode setting

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Users can now enable/disable Cancel Gcode through the Feature menu. Disabled by default.

### Benefits

See above.

### Related Issues

None.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
@guruathwal Mind testing this on your end?

**Comment by bigtreetech** [comment]
Is it more appropriate to name "Abort printing" than "Cancel" ?

**Comment by guruathwal** [comment]
Looks good...👍...

**Comment by thisiskeithb** [comment]
> Is it more appropriate to name "Abort printing" than "Cancel" ?

Either would work.

To add to the confusion, the button to abort/cancel/stop a print is labeled "Stop".

**Comment by guruathwal** [comment]
> > Is it more appropriate to name "Abort printing" than "Cancel" ?
> 
> Either would work.
> 
> But to add to the confusion, the button to abort/cancel/stop a print is labeled "Stop".

"Stop" is well suited for this purpose as it is easily recognizable even if someone does not know English properly.

**Pull request merged**
