### PR TITLE
ProgressBar during print

### PR DESCRIPTION
**Pull request by kisslorand**
This PR draws a progress bar during print.
The color chosen is Orange because it is easy on the eye if you like to stare at your TFT yet easily seen from a distance. It's not user configurable (yet).

It might affect the print quality so it will be kept as a draft until it gets the blessing from you.
I could only test it on 32bit system with large enough buffers and had no print quality issues.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
> It's not user configurable.

With the menus, icons, and various other TFT color options being configurable, why not?

**Comment by Guilouz** [comment]
Do you have a screenshot of that ?

Maybe progress bar can be enabled/disabled by user in config.ini ?

**Comment by kisslorand** [comment]
> With the menus, icons, and various other TFT color options being configurable, why not?

Because it is a draft, Orange should do it just fine for testing purposes. If it turns out it really doesn't hurt the print quality, than user config will be introduced.

> Do you have a screenshot of that ?

ProgressBar

> Maybe progress bar can be enabled/disabled by user in config.ini ?

Possible but at the cost of wasted codespace. If progress bar is disabled, the upper icons should be moved back to their original space. For this to be possible both positions should be defined and kept in the flash memory.
If really needed, yes, possible.

**Comment by kisslorand** [comment]
Commit [07a92b7](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1728/commits/07a92b7c20501fac651f877905f598cd96a99015) brings some GUI polishing and a very fast progress bar drawing. It makes progress bar drawing faster than any other item refresh during print. 
It makes it the least invasive GUI update amongst all.

**Comment by gordo3di** [comment]
Ooh this is another part of my wish list from a while back https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/732

**Comment by kisslorand** [comment]
I started working on the progressbar enabled/disabled and color customization and it adds RAM usage and extra code to the printing process.
I am not fond of neither of these side effects so I just stopped.
There will be no customization implemented just for the sake of it.

**Comment by oldman4U** [comment]
Which TFT's should I test it with and what exactly? Just the drawing of the bar on the TFT or also the print quality (which is a bit hard to test...).

Mainboard matters or can I use any mainboard?

**Comment by kisslorand** [comment]
@bigtreetech 
It can be merged.

If there will be a real need for customization, it can be done. Until than an orange progress bar is better than none.

**Comment by bttguy** [comment]
Like this feature @kisslorand ! Is this also working with RRF? We just got print status monitoring, in #1743 that needed some special schanes in our fw for be useful? Can you check it on the code I should expect is to work?

**Comment by kisslorand** [comment]
Sorry, I cannot test it other than Marlin.

**Comment by oldman4U** [comment]
bttguy

The PRs are available here so users can test them before they are merged. Once they are merged it is too late. Please test now and let us know. Thank you

**Comment by bttguy** [comment]
Oh, I see @oldman4U . If I wanna test PRs I need to use kissroland's fork where he did the changes and pushed the changes here or is there a button where I can download the fw including this PR? Still leraning github, but willing to learn :)

**Comment by kisslorand** [comment]
It was a draft for 8 days for this very reason, to be tested BEFORE merge.

**Comment by bttguy** [comment]
@kisslorand Since print progress just been added recently, I was busy testing that first. But now I compiled your PR for my TFT 24, and it works as you intended at a first glance also for us RRF users. Both in simulation and in an actual print. So thanks you for your work, next time I will be more careful to test these kind of changes.

**Comment by oldman4U** [comment]
Hi. I always use the repository and must say that I do not know if there is
another (better) way😁

Good to hear it works👍🏻

bttguy ***@***.***> schrieb am Mo. 22. März 2021 um 17:50:

**Comment by labotecno** [comment]
Seem this PR work with tft 35 e3 

You do a great  work with this progress bar .

**Comment by kisslorand** [comment]
@bigtreetech 
Any reason holding this back?

**Pull request merged**
