### PR TITLE
Add support to be able to control case light

### PR DESCRIPTION
**Pull request by mak0t0san**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description
This PR adds a button in Machine Settings that allows a user to view and modify the brightness of the case lights.  The button is only visible if the capabilities reported by the machine indicates that it has a case light.

### Benefits

This allows a user to easily change the case light brightness, or even toggle it on and off. Without this change, a user has a couple of workarounds, none of them very convenient including:
- Switch to Marlin mode screen
- Go to terminal and type in gcode 
- Create custom actions

### Related Issues
#1194 

Here are some pictures of what the button looks like on a TFT35 and TFT24

TFT35
TFT24

And pictures of the controls

### CODE REVIEW

**Review by digant73 — CHANGES_REQUESTED** [review]
hi
In all the german language files there is a duplication for
#define STRING_NOTIFICATIONS          "Notifications"
Remove that entry (leave the german translation). Also I would append the new label at the end of each language file (so after the mesh tuner label).
The same in includes.h. I would append the new .h after the mesh tuner and probeHeightControl

**Comment by mak0t0san** [comment]
> hi
> In all the german language files there is a duplication for
> #define STRING_NOTIFICATIONS "Notifications"
> Remove that entry (leave the german translation). Also I would append the new label at the end of each language file (so after the mesh tuner label).
> The same in includes.h. I would append the new .h after the mesh tuner and probeHeightControl

Thanks. I'll fix those up.  I merged in the latest changes from the upstream branch and it brought the mesh tuner strings to the bottom.  I'll update this PR with those changes.

**Comment by Acenotass** [comment]
hi @mak0t0san 
The backlight on my printer is WS2812 RGB Led Strip Light with a choice of colors and / or effects. It would be nice to include support for such functionality.

**Comment by mak0t0san** [comment]
> hi @mak0t0san
> The backlight on my printer is WS2812 RGB Led Strip Light with a choice of colors and / or effects. It would be nice to include support for such functionality.

@Acenotass , does the current RGB functionality do what you need?  The touchscreen firmware has code to be able to control RGB lights via the M150 gcode command.

**Comment by Acenotass** [comment]
@mak0t0san 
At least backlight color control

**Pull request merged**
