### PR TITLE
Update italian language

### PR DESCRIPTION
**Pull request by BsCmOD**
Update italian language

### CODE REVIEW

**Comment by radek8** [comment]
Also add an ini file to PR.

**Comment by BsCmOD** [comment]
Off course but I don't know how to do it

**Comment by radek8** [comment]
If you are using VS Code, just tap on the sprout in the crew you made the adjustment.
Close VS Cde and it will be generated automatically when restarted. Then just publish.

**Comment by radek8** [comment]
added to
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1698

**Pull request merged**
