### PR TITLE
changes from other pulls & cooldown on aborting print & center the progress percentage

### PR DESCRIPTION
**Pull request by Hans007a**
### Requirements

TFT display ;-)

### Description

0. changes from other pulls
1. cooling down all heaters after aborting print from TFT SD
2. center the printing progress percentage for more visibility

### Benefits

the most important is the cooling down all heaters after aborting the print

### Related Issues

I have none issues

### CODE REVIEW

**Comment by guruathwal** [comment]
these commits are already in PR #302 . please avoid pushing duplicate commits. it may make it hard to track the changes.

**Comment by Hans007a** [comment]
Sorry, I'm not so familiar with the git. Next time I will try to publish only my changes

**Comment by guruathwal** [comment]
@Hans007a please close this PR

**Comment by thisiskeithb** [comment]
> @Hans007a please close this PR

I came here to suggest the same since re-commiting old commits makes tracking down bugs a chore and can possibly break things.

**Pull request closed without merging**
