### PR TITLE
Separate char icons from list API and Change list menu API

### PR DESCRIPTION
**Pull request by guruathwal**
- Separate char icons from list API.
- Change list menu API to reduce memory usage and make it more consistent.
- Fix wrong keywords index in secondary language due to language flash sign not updated after adding new keywords.

Build Report:

Device | Old RAM Usage | New RAM usage | RAM Reduced | Old Flash Size | New Flash Size | Flash Size Reduced
-- | -- | -- | -- | -- | -- | --
TFT35 V1.0 | 17856 | 17540 | -316 | 152360 | 150480 | -1880
TFT35 V1.1 | 17856 | 17540 | -316 | 152360 | 150480 | -1880
TFT35 V1.2 | 17856 | 17540 | -316 | 152232 | 150352 | -1880
TFT35 V2 | 18624 | 18288 | -336 | 161756 | 159764 | -1992
TFT35 V3.0 | 19052 | 18712 | -340 | 180200 | 178032 | -2168
TFT35 E3 V3.0 | 19080 | 18716 | -364 | 180968 | 178704 | -2264
TFT35 B1 V3.0 | 19080 | 18716 | -364 | 180968 | 178704 | -2264
TFT43 V3.0 | 19080 | 18716 | -364 | 180972 | 178708 | -2264
TFT50 V3.0 | 19080 | 18716 | -364 | 180972 | 178708 | -2264
TFT70 V3.0 | 19208 | 18844 | -364 | 182128 | 179880 | -2248
TFT28 V1.0 | 17856 | 17540 | -316 | 152408 | 150512 | -1896
TFT28 V3.0 | 19080 | 18716 | -364 | 180808 | 178544 | -2264
TFT24 V1.1 | 19004 | 18688 | -316 | 176128 | 174000 | -2128
MKS TFT32 V1.3 | 18964 | 18624 | -340 | 175676 | 173564 | -2112
MKS TFT32 V1.4 | 18964 | 18624 | -340 | 176116 | 174004 | -2112

### CODE REVIEW

**Comment by digant73** [comment]
The keys on Numpad are displayed with small font. Could you also fix it?

**Comment by guruathwal** [comment]
> The keys on Numpad are displayed with small font. Could you also fix it?

The keys are already displayed with large fonts.

**Comment by digant73** [comment]
> > The keys on Numpad are displayed with small font. Could you also fix it?
> 
> The keys are already displayed with large fonts.

hmm not in my screen. Just try the "Z fade" menu. I see small font for the keys.

**Comment by digant73** [comment]
With material theme disabled, the keys are displayed with small fonts. With material theme enabled, the large font is used

IMG_20210419_194802

**Comment by guruathwal** [comment]
@digant73 fixed in #1854

**Pull request merged**
