### PR TITLE
Bugfixes, cleanup

### LINKED ISSUE #1523: [BUG] Resume does not work after pausing print from onboard SD card (SKR mini E3 2.0 TFT35 E3 V3.0)
### Description

After pausing a print in touch mode it will do the filament purge in the last printing point instead of the top left corner and will present a resume dialog box. After that, impossible to resume by clicking on the ok button until power off.

### Steps to reproduce

1. Launch a print in touch mode from board SD card
2. Pause the print

**Expected behavior**
To retract, raise the Z axis, and move to the top left corner of the bed for filament purge.
To present a dialog box with the resume question
To resume the print after clicking ok on the dialog box 

**Actual behavior**
Z axis raises, moves to the top left corner but comes back to the last printing point for filament purge
presents the resume dialog box but impossible to continue from there until power off

### Hardware Variant
TFT35 E3 V3.0
### TFT Firmware Version & Main Board Firmware details
TFT firmware BIGTREE_TFT35_V3.0.26.x (config version 20201218) - Marlin 2.0.7.2

### Additional Information
Was reported in SKR-mini-E3 as https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/issues/488
IMG_4533
IMG_4534

### LINKED ISSUE #1582: [BUG] "Loading..." screen after canceling a print from onboard SD
### Description

After canceling a print from onboard SD, TFT stay on "Loading..." screen. Need to reset screen to go back on home menu.

### Steps to reproduce

1. Start a print from onboard SD
2. Cancel this print
3. TFT stay on "Loading..."

**Expected behavior**
After canceling a print, onboard SD card content need to be reloaded and displayed.

**Actual behavior**
After canceling a print, TFT stay on "Loading..." screen.

### Hardware Variant
TFT43 V3.0

### TFT Firmware Version & Main Board Firmware details
Latest master for TFT and latest Marlin 2.0 bugfix for Main Board.

### Additional Information
No issue when canceling a print from TFT SD/USB.

### PR DESCRIPTION
**Pull request by kisslorand**
### Requirements

BTT TFT or MKS TFT

### Description

* fixed "Loading..." screen hanging after canceling a print from onboard SD
* fixed "Loading..." screen hanging after pausing and than later canceling a print from onboard SD
* fixed nozzle moving away from parking position after "Pause" when `PARK_HEAD_ON_PAUSE` is enabled in Marlin
* fixed some memory allocation not being released after no longer needed
* fixed `request_M0` not being parsed
* fixed a hidden bug that could become active in a future development (`requestCommandInfo` is used ONLY when printing from TFT and onboard SD, in no other case)
* tiny code cleanup
### Benefits

- everyone

### Related Issues

Fixes #1582
Fixes #1523
Probably fixes other or some issues related to "Pause".

### CODE REVIEW

**Comment by blueeagle69** [comment]
> ### Requirements
> BTT TFT or MKS TFT
> 
> ### Description
> * fixed "Loading..." screen hanging after canceling a print from onboard SD
> * fixed some memory allocation not being released after no longer needed
> * fixed `request_M0` not being parsed
> * fixed a hidden bug that could become active in a future development (`requestCommandInfo` is used ONLY when printing from TFT and onboard SD, in no other case)
> * tiny code cleanup
> 
> ### Benefits
> * everyone
> 
> ### Related Issues
> Fixes #1582

Amazing, thank you.

**Comment by kisslorand** [comment]
Upon further testing I came across another nasty bug. If a print was paused and afterwards it was canceled the TFT would hang.
It was a hard nut to crack but it's fixed now.

Slowly I am getting tired of this....

**Comment by mehmetsutas** [comment]
Although this PR is already is merged. It is not a good practice to send M876 S0 commands without letting the user decide what is being approved or dismissed. It would be better to avoid missing prompts by improving host prompt. User should decide on what is being approved or dismissed.

**Review by mehmetsutas — COMMENTED** [review]
Not checked on Marlin source but it was adviced as M25 P1 instead of M25 P in MarlinFirmware/Marlin#18191

**Comment by mehmetsutas** [comment]
> Not checked on Marlin source but it was adviced as M25 P1 instead of M25 P in [MarlinFirmware/Marlin#18191](https://github.com/MarlinFirmware/Marlin/issues/18191)

Just seen that #1598 corrected.

**Comment by kisslorand** [comment]
> Although this PR is already is merged. It is not a good practice to send M876 S0 commands without letting the user decide what is being approved or dismissed. It would be better to avoid missing prompts by improving host prompt. User should decide on what is being approved or dismissed.

Generally it is true. In this case you mention I just  sent the M876 S0 for a not-shown prompt message. It wasn't me who decided not to show the "Resume Print" prompt, it was like that since... forever.

Regarding M25 P or M25 P1, if you check the Marlin code, it checks only if P is there or not.
`const bool show_lcd = TERN0(HAS_LCD_MENU, parser.boolval('P'));`

**Comment by mehmetsutas** [comment]
@kisslorand excuse me for false comment. I just realized that I was checking the code against my customized copy which I have changed the hostprompt logic some time ago. Your logic is right,

**Comment by scathappens** [comment]
does this mean that there is anew firmware available now that works as expected?

**Pull request merged**
