### PR TITLE
language_de.h with UTF-8 encoded U-2103

### PR DESCRIPTION
**Pull request by MarkusThur**
german language with better translations and correctly UTF-8 encoded U-2103

### Description

replaces the °C encoded temperature with correct UTF-8 encoded &#x2103; in the german file
some improved translations.

### Benefits
better translation of some items
better representation of °C through using &#x2103;
getting german back to be in sync with the other translations 

### Related Issues
#1963

### CODE REVIEW

**Comment by radek8** [comment]
Add the generated INI file

**Comment by oldman4U** [comment]
Congrats, first contribution!

Lust auf mehr? https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1170

#296 would be a nice project

oldman

**Comment by MarkusThur** [comment]
> Congrats, first contribution!
> 
> Lust auf mehr? #1170
> 
> #296 would be a nice project
> 
> oldman

Thx... As far as I understood, yes a nice one to find into the system.....
But I fear someone has to explain a little closer what is whished :-)

It feels a little like:
https://www.programmwechsel.de/lustig/management/cartoon-projekte.png

I try to comment there, to discuss if I understood it right

**Comment by oldman4U** [comment]
Hehe. Most of the time you believe you understand what the other is asking for - until you find out...

Just use the ticket for further discussion (and hopefully someone answers)

;-)

**Pull request merged**
