### PR TITLE
NEW Hybrid Red Menu Icon PACK

### PR DESCRIPTION
**Pull request by AntoszHUN**
A brand new Menu Icon system. It was named Hybrid Red Menu because it contains icons from multiple areas. It has MKS TFT icon. It has BTT TFT icon inside. Most of the icons are dominated by red. That is why it became the name of Hybrid Red Menu. It works accurately and hopefully flawlessly. Feel free to contact me with questions.

She's in a ZIP folder because I couldn't create a folder for her in the root directory. And it would look better that way.

Tested on: BIGTREETECH TFT35 display

Hello, AntoszHUN

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Do you have any preview images?

**Comment by radek8** [comment]
> Máte nějaké náhledové obrázky?

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/899

**Comment by AntoszHUN** [comment]
> 
> 
> Do you have any preview images?

Of course. Will that be enough? If I have to do more.

IMG_20200801_134953
IMG_20200801_135002
IMG_20200801_135047
IMG_20200801_135129
IMG_20200801_135142

**Comment by GeminiServer** [comment]
I like your icon pack. 

But there are some missing icons such as:
- Point_5.bmp
- e_100_mm.bmp
- e_200_mm.bmp
- ... etc. 

Please check all files/icons again.

**Comment by AntoszHUN** [comment]
> I like your icon pack.
> 
> But there are some missing icons such as:
> 
>     * Point_5.bmp
> 
>     * e_100_mm.bmp
> 
>     * e_200_mm.bmp
> 
>     * ... etc.
> 
> 
> Please check all files/icons again.

When I posted even those icons were not missing. :( I'll fix it as I know.

**Pull request closed without merging**
