### PR TITLE
Fix heater indexes

### PR DESCRIPTION
**Pull request by creamywhite**
### Description

Fix for wrong heater indexes issue that caused last heater to be ignored in some functions

### Benefits

M109 will work as intended when printing from TFT

### Related Issues

None that I know of.

### CODE REVIEW

**Comment by AntoszHUN** [comment]
Does this solve the problem of starting to print without a heated extruder?

**Comment by creamywhite** [comment]
@AntoszHUN, if that problem is caused by ignorance of M109 gcode command, then yes.

**Comment by martinj** [comment]
Can we get this merged? This problem is really annoying.

**Comment by digant73** [comment]
it is fixed by #663

**Pull request merged**
