### PR TITLE
Delete Hungarian language and my own icon pack

### PR DESCRIPTION
**Pull request by AntoszHUN**
Hi!

In today's update, I will delete the Hungarian language and the icon pack I created.

The consequence of this is what is happening in the world.
I do not intend to make anything for free.

And the BigTreeTech team hasn’t been writing back for several months. Any request I make to them will be denied.

On the other hand, development is not going well, if I can see clearly. There is no point in dealing with these systems anymore. The future belongs to Klipper and Fluid.

Thank you for your understanding!

Signed-off-by: AntoszHUN <zsikaiantal@gmail.com>

### CODE REVIEW

**Comment by oldman4U** [comment]
Maybe you can also remove the icon pack from the readme. Thank you and good luck

**Comment by AntoszHUN** [comment]
> 

It's done.

**Comment by radek8** [comment]
Delete your icons. You were the only one who used it. 
But prpč delete hungarian translation? More people worked on it. You are not the only owner.

**Comment by AntoszHUN** [comment]
> 

I created the Hungarian language. Some people reached in, stabbed him, but didn't make any substantial repairs. But I kept it up to date and I created it. I don't want to deal with it. For other reasons. Thank you for your understanding.

**Comment by kisslorand** [comment]
I fully support AntoszHUN's decision as these days red is not the most popular and friendly color and for people from Hungary it wouldn't hurt to learn some English and stop relying on Google translate service (which is horrible for Hungarian language).

> The consequence of this is what is happening in the world.

I highly doubt that the monstrosity happening these days is the consequence of this PR made by AntoszHUN. This text is an example of the wonders Google Translate can do...

I guess no big harm is done if this PR is merged, message received, although the gesture itself reminds me of the kindergarten where kids often ask back things they give away.

Again, I fully support the decision made by AntoszHUN, may his attitude make this world a better place!

**Comment by radek8** [comment]
@AntoszHUN 
You probably don't have many friends :-(

**Comment by AntoszHUN** [comment]
Everyone was given the opportunity to show off better. I have a reason to take it out. It's all simple. From now on, everyone thinks of me what they want. Individual right. There are just as many friends as I can expect in life. No more! Lots of friends, lots of trouble. ;)

**Comment by digant73** [comment]
> > 
> 
> I created the Hungarian language. Some people reached in, stabbed him, but didn't make any substantial repairs. But I kept it up to date and I created it. I don't want to deal with it. For other reasons. Thank you for your understanding.

It's an open source project where other people contributed to the translation. IMHO, for a feature like that, it's not so nice to ask a rollback for the changes (in the meanwhile) made also by other contributors

**Comment by radek8** [comment]
@AntoszHUN ,
You have contributed your code under the GPL V.3 license and more after you.
You can't take your code now without hurting the work of others.
You can propose a change of code by removing the Hungarian language. But the repository manager (bigteeetech) doesn't have to merge your post if he thinks your PR is bad or the software is harms.
As for your icons, I would really remove them, if there is no one to keep them up to date, they are unnecessary.
As for the Hungarian language, there will definitely be someone who will keep it up to date ...

**Comment by AntoszHUN** [comment]
Well. Do what you want then.

**Pull request closed without merging**
