### PR TITLE
Add new settings categories and clean up

### PR DESCRIPTION
**Pull request by guruathwal**
- Add Marlin mode settings menu in screen settings.
- Add Brightness settings menu in screen settings.
- Remove some items from the Feature settings menu, which should only be configured through the config file.
- Replace the word 'Simulator' with 'Emulator'.
- Replace u8, u16, u32 with uint8_t, uint16_t, uint32_t.
- Enable post-processor for displays with SSD1963 to reduce banding on some devices.
- Move frequently polled commands to the top in parseACK.c

**Build Report:**
Device Variant | Old RAM Usage | New RAM usage | RAM Reduced | Old Flash Size | New Flash Size | Flash Size reduced
-- | -- | -- | -- | -- | -- | --
TFT35 V1.0 | 20728 | 20620 | -108 | 144028 | 143164 | -864
TFT35 V1.1 | 20728 | 20620 | -108 | 144028 | 143164 | -864
TFT35 V1.2 | 20728 | 20620 | -108 | 143908 | 143044 | -864
TFT35 V2 | 21520 | 21388 | -132 | 153572 | 152624 | -948
TFT35 V3.0 | 22028 | 21824 | -204 | 171532 | 171028 | -504
TFT35 E3 V3.0 | 22052 | 21848 | -204 | 172200 | 171692 | -508
TFT35 B1 V3.0 | 22052 | 21848 | -204 | 172208 | 171700 | -508
TFT43 V3.0 | 22052 | 21848 | -204 | 172180 | 171684 | -496
TFT50 V3.0 | 22052 | 21848 | -204 | 172180 | 171684 | -496
TFT70 V3.0 | 22180 | 21976 | -204 | 173240 | 172744 | -496
TFT28 V1.0 | 20728 | 20620 | -108 | 144044 | 143188 | -856
TFT28 V3.0 | 22052 | 21848 | -204 | 172008 | 171504 | -504
TFT24 V1.1 | 21952 | 21772 | -180 | 167336 | 166980 | -356
MKS TFT32 V1.4 | 22704 | 22536 | -168 | 167596 | 166856 | -740
MKS TFT28 V1.0 | 22704 | 22536 | -168 | 167596 | 166856 | -740

### CODE REVIEW

**Comment by oldman4U** [comment]
So there are no new Icons with this PR, right?

**Comment by guruathwal** [comment]
two icons are replaced

**Comment by oldman4U** [comment]
@Acenotass @AntoszHUN

The font and background colour icons are removed and there are 2 new icons for Marlin Mode and Brightness.

Could you please take care.

THANK YOU

**Comment by AntoszHUN** [comment]
> @Acenotass @AntoszHUN
> 
> The font and background colour icons are removed and there are 2 new icons for Marlin Mode and Brightness.
> 
> Could you please take care.
> 
> THANK YOU

Again, he was unnecessarily changed because of a little nonsense. I don’t have time for this right now to edit icons unnecessarily again. I'm lying in bed. I caught the covid. Solve the stupidity. I'm getting out! You have to vary something with the icons and the menu every month. Do what you want. Hi!

**Comment by sarvenn** [comment]
Could you give more details for this item please?
"Remove some items from the Feature settings menu, which should only be configured through the config file."

**Comment by Guilouz** [comment]
Your icon Mesh Editor for TFT43 is not centered : 

mesh_editor

10px on top, 7 px on bottom, 15px on left ans 17px on right

Fixed : 

mesh_editor_good

[mesh_editor.bmp.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6005438/mesh_editor.bmp.zip)

**Comment by oldman4U** [comment]
> > @Acenotass @AntoszHUN
> > The font and background colour icons are removed and there are 2 new icons for Marlin Mode and Brightness.
> > Could you please take care.
> > THANK YOU
> 
> Again, he was unnecessarily changed because of a little nonsense. I don’t have time for this right now to edit icons unnecessarily again. I'm lying in bed. I caught the covid. Solve the stupidity. I'm getting out! You have to vary something with the icons and the menu every month. Do what you want. Hi!

Hi Antosz.

Wish you the best. No reason to be rude.

Köszönöm

**Comment by kisslorand** [comment]
> I'm lying in bed. I caught the covid.

I wish you fast recovery! Stay away from stress and take care of your health.

**Comment by traffic-light** [comment]
> > @Acenotass @AntoszHUN
> > The font and background colour icons are removed and there are 2 new icons for Marlin Mode and Brightness.
> > Could you please take care.
> > THANK YOU
> 
> Again, he was unnecessarily changed because of a little nonsense. I don’t have time for this right now to edit icons unnecessarily again. I'm lying in bed. I caught the covid. Solve the stupidity. I'm getting out! You have to vary something with the icons and the menu every month. Do what you want. Hi!

I wish you the best! I hope you will have a fast recovery. And I hope you will get rid of all the covid symptoms (or how to call it...) I still have the problem that I'm quickly tired and trying to hurry on my bike is even worse ...

**Comment by traffic-light** [comment]
> Could you give more details for this item please?
> "Remove some items from the Feature settings menu, which should only be configured through the config file."

Touchme, invert axis and some more. Take a look in the changed files

**Comment by sarvenn** [comment]
> > @AntoszHUN

> Again, he was unnecessarily changed because of a little nonsense. I don’t have time for this right now to edit icons unnecessarily again. I'm lying in bed. I caught the covid. Solve the stupidity. I'm getting out! You have to vary something with the icons and the menu every month. Do what you want. Hi!

Get well soon.

**Comment by sarvenn** [comment]
> > Could you give more details for this item please?
> > "Remove some items from the Feature settings menu, which should only be configured through the config file."
> 
> Touchme, invert axis and some more. So, pretty useless to configure easily trough the settings menu.
> 
> Take a look in the changed files.
@traffic-light hello,
I'm still learning about github :) I'm not familiar with coding but I have some skills about UX/UI from my daily job :). Hope to contribute with my best.
I checked the "files changed" tab above and noticed the deleted labels from the language.ini files.

I think these are better to stay in the feature menu:
label_default_mode:Default Mode
label_fil_runout_inverting:Inverted Filament Runout Logic

inverting the logic of the switch in the screen would be very user friendly and fast way to install and get it run properly. I also use my runout sensor connecte to my TFT35. While installing my runout sensor, I noticed that the logic was wrong and at that time I didn't know it was in config.ini file. First thing that I checked was the feature menu. Runout sensor type selection was there but logic selection was missing. After that it was added along with other labels. I think it should stay there. It is more intuitive to see that in the feature menu.
Default mode is not something that I use but setting the default mode through the screen is also user friendly, fast and intuitive. 
Other labels are not something to change time to time, I agree, they are better to stay in the config.ini only.
Please evaluate my suggestions above and comment.
Thanks.

Good job @guruathwal . You may remember me from facebook :) Good to see your PR here.

**Comment by radek8** [comment]
@guruathwal 
Why did you delete the M503 S0 command from the MachineParemeters.c file
They had a purpose there. Now the display of these parameters is damaged after editing.

**Comment by radek8** [comment]
Example of a problem after deleting the M503 command
https://youtu.be/teW10NSVqm4

**Comment by radek8** [comment]
Errors occur when updating language packs.

IMG_20210219_232050_resized_20210219_112309449
IMG_20210219_232040_resized_20210219_112309674

**Comment by guruathwal** [comment]
@AntoszHUN Get well soon.
@sarvenn  Good to see you here also. The default_mode option is useless to show in feature settings as it will automatically change to the current mode after switching to another mode. settings like runout_inverting should only be in config files only so that they are not lost after some firmware updates that require resetting settings. keeping them in config file make sure that these settings are saved and can be used to restore after a full reset without the need to figuring out what they were and manually setting all of them.

@radek8 the language pack problem is solved. I removed `M503 S0` because it is not good for changing parameters while printing and may cause print stutter while printing at hi-speeds. The wrong values are displayed because parsing of gcode for second extruder was added only in **parseACK.c** and not in **interfaceCmd.c**. This should now be fixed in https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1633/commits/3bbf84b903a5d2ef39221140976b5652b7191371. Please check and see if the problem is solved.

**Comment by sarvenn** [comment]
> @sarvenn Good to see you here also. The default_mode option is useless to show in feature settings as it will automatically change to the current mode after switching to another mode. Settings like runout_inverting should be in config files only, so that they are not lost after some firmware updates that require resetting settings. keeping them in config file make sure that these settings are saved and can be used to restore after a full reset without the need to figuring out what they were and manually setting all of them.
> 
Alright, you are the guru, not me :) I also edit my config.ini file while updating my firmware.

**Comment by radek8** [comment]
I think the M503 command could have remained. After all, no one will change the number of steps when printing.

Tested
The M92 does not work well when updating the E-axis on a single-extruder printer
M92 does not work well when updating the E2 axis on a printer with two extruders.
M203 - OK
M201 - OK
M209 - OK
M900 - OK
M906 - OK
M913 - OK
M218 - There is a problem. As soon as I edit the X axis, the previous parameter will also be saved incorrectly and after a while clicking on the display, the display will freeze.

**Comment by radek8** [comment]
481 / 5000
Výsledky překladu
Printer with 2 estruders and 1 hotend
responds to the M92 command, with a value only with the extruder active
>>> T0
SENDING: T0
echo: Active Extruder: 0
>>> M92
SENDING: M92
echo: M92 X100.0300 Y100.0300 Z800.0000
echo: M92 T0 E146.2000
>>> T1
SENDING: T1
echo: Active Extruder: 1
>>> M92
SENDING: M92
echo: M92 X100.0300 Y100.0300 Z800.0000
echo: M92 T1 E146.1000
Conversely, command M503 does not respond to all extruders
M503
   M92 X100.0300 Y100.0300 Z800.0000
   M92 T0 E146.2000
   M92 T1 E146.1000

**Comment by radek8** [comment]
Why did you remove the temperature icons in the upper right corner? They were useful.

**Comment by kisslorand** [comment]
// joking mode ON
He's the remover!
// joking mode OFF

**Comment by radek8** [comment]
Sorry, my mistake.
It was turned off in the test configuration :-)

**Comment by kisslorand** [comment]
// joking mode ON
Aha! So it's you who is the remover!
// joking mode OFF

**Comment by radek8** [comment]
Missing Marlin mode description

image

**Comment by radek8** [comment]
Ikony pro Round Miracle Menu 3,5"
image

[Round Miracle 35.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6016869/Round.Miracle.35.zip)

**Comment by radek8** [comment]
Your M218 fix in InterfaceCmd.c will not work

Marlin responds to M503:
M218 T1 X10.5500 Y-0.3000 Z0.000

Marlin responds to M218:
SENDING: M218
echo: Hotend offsets: 0.00,0.00,0.000 10.55, -0.30,0.000

**Comment by guruathwal** [comment]
> Your M218 fix in InterfaceCmd.c will not work
> 
> Marlin responds to M503:
> M218 T1 X10.5500 Y-0.3000 Z0.000
> 
> Marlin responds to M218:
> SENDING: M218
> echo: Hotend offsets: 0.00,0.00,0.000 10.55, -0.30,0.000

@radek8 Did you tried it? **InterfaceCmd.c** is for parsing gcodes originating from TFT.

**Comment by radek8** [comment]
Patch tested.
You're right, now the M218 is working.
I misunderstood the principle of analyzing the interfaceCmd.c file
You have a little typo in the description
image

The E axis is still not correct in the set step length (M92)
see video
https://youtu.be/ZWL2C5YVrQY

**Comment by radek8** [comment]
The different behavior is if I enter an integer or decimal with one, two, or 3 decimal places

https://youtu.be/vsdq-ljjGGg

**Comment by radek8** [comment]
interfaceCmd.c uses the X_AXIS variable
and
parseACK.c uses the X_STEPPER variable
It's good?

image
image

**Comment by guruathwal** [comment]
@radek8 Line 527 should be cmd_float();. both _AXIS and _STEPPER are same thing with _STEPPER having extra E2_STEPPER

**Review by radek8 — CHANGES_REQUESTED** [review]
Please repair the Machine parametrs.c file
M913 T0 E% .0f \ n 

 {"M913 X%.0f\n",    "M913 Y%.0f\n",     "M913 Z%.0f\n",     "M913 T0 E%.0f\n",     "M913 T1 E%.0f\n"},   //TMC Hybrid Threshold Speed

**Comment by digant73** [comment]
I would also optimize the parseAck moving on top of the "if then else" sequenze all the periodically/frequently requested received status such as "FR", "Flow" etc.. and the prompt messages that could be received during a print such as "paused for user", "//action:" etc.. They are currently provided at the bottom so, they will match after performing hundreads of previous "if then else". The list must be arranged in order to have to most frequently used patterns on top and the least on the bottom (such as Capabilities and machine settings that are normally requested once at startup or in general when not printing)

**Comment by radek8** [comment]
Hi
I found another problem with loading the Linear Advance parameter
After switching on, a zero value is always read, even though there is a valid value in eeprom. After editing, it will display well until the restart.
The problem is therefore in ParseACK.c
IntefaceCmd.c is fine.
It was loading properly after the restart before your intervention.
Don't want to revert to the original syntax?

**Comment by digant73** [comment]
Remove "K" on line 657 of parseAck

**Comment by radek8** [comment]
> Remove "K" on line 657 of parseAck

Will you make the repair before merging?

**Comment by bigtreetech** [comment]
> 
> I think these are better to stay in the feature menu:
> label_default_mode:Default Mode
> label_fil_runout_inverting:Inverted Filament Runout Logic
> 
May be necessary to put some common settings and non-common settings in different lists ?
for example
```
->0. Frequently-used settings
        ->1. Common settings
                ->2. File list mode
                ->2. filament sensor
->0. Not frequently-used settings
->0. System settings
```

The advantage of this is that users need not use SD to plug in the computer to modify the settings, and almost all the settings can be modified on the screen directly.
The disadvantage is that these label strings will take up a lot of memory flash

**Comment by oldman4U** [comment]
> > I think these are better to stay in the feature menu:
> > label_default_mode:Default Mode
> > label_fil_runout_inverting:Inverted Filament Runout Logic
> 
> May be necessary to put some common settings and non-common settings in different lists ?
> for example
> 
> ```
> ->0. Frequently-used settings
>         ->1. Common settings
>                 ->2. File list mode
>                 ->2. filament sensor
> ->0. Not frequently-used settings
> ->0. System settings
> ```
> 
> The advantage of this is that users need not use SD to plug in the computer to modify the settings, and almost all the settings can be modified on the screen directly.
> The disadvantage is that these label strings will take up a lot of memory flash

Based on which user/configuration will be defined what is common and what not? For me and just for me maybe, it is better to have a long list of settings but all of them available and at the same place than settings in different places based on more or less clear rules.

**Comment by radek8** [comment]
> > I think these are better to stay in the feature menu:
> > label_default_mode:Default Mode
> > label_fil_runout_inverting:Inverted Filament Runout Logic
> 
> May be necessary to put some common settings and non-common settings in different lists ?
> for example
> 
> ```
> ->0. Frequently-used settings
>         ->1. Common settings
>                 ->2. File list mode
>                 ->2. filament sensor
> ->0. Not frequently-used settings
> ->0. System settings
> ```
> 
> The advantage of this is that users need not use SD to plug in the computer to modify the settings, and almost all the settings can be modified on the screen directly.
> The disadvantage is that these label strings will take up a lot of memory flash

I think it's a good idea.
If the "non frequently" and "system" menus could be hidden by the user, it would cater to users who configure printers for less experienced users and want to hide these options.
see:
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1609#issuecomment-774784424

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1053

**Comment by oldman4U** [comment]
I can already see all the tickets coming in related to hidden features. 🎉

**Comment by guruathwal** [comment]
> > I think these are better to stay in the feature menu:
> > label_default_mode:Default Mode
> > label_fil_runout_inverting:Inverted Filament Runout Logic
> 
> May be necessary to put some common settings and non-common settings in different lists ?
> for example
> 
> ```
> ->0. Frequently-used settings
>         ->1. Common settings
>                 ->2. File list mode
>                 ->2. filament sensor
> ->0. Not frequently-used settings
> ->0. System settings
> ```
> 
> The advantage of this is that users need not use SD to plug in the computer to modify the settings, and almost all the settings can be modified on the screen directly.
> The disadvantage is that these label strings will take up a lot of memory flash

Currently, there are 93 parameters that are not displayed in settings menus and most of them have at least 2-3 sub-parameters. even if half of these are selected to be added in the settings menus total entries will be close to 200.  Category wise list or as a single list, it will be a long list.
The core reason for the problem is the lack of proper documentation/guide for providing details of available feature and settings.

**Pull request merged**
