### PR TITLE
Memory handling optimization

### PR DESCRIPTION
**Pull request by bagobor**
### Description
Improves memory handling operations by reducing the number of memory allocations. 

### Benefits
- Memory allocation is a high-cost operation so it's better to avoid it if possible
- freed memory access will lead to a crash and/or will require more realtime checks -> bigger chance to  break

### Related Issues

@melufre PTAL, thanks

### CODE REVIEW

**Comment by hfog** [comment]
Good change. This could explain some of the random hanging bugs I've seen during my testing. It could also seriously improve performance of the serial handling code.  I'll try to test it out later tonight and see if it helps.

**Comment by bagobor** [comment]
@hfog thanks!

**Comment by hfog** [comment]
You're welcome. Unfortunately, this did not fix the freezing that I've been seeing when doing very fast and busy prints through the TFT. I think that the TFT is still just not able to push gcode from UART3 through TFT to printer and back fast enough to avoid stuttering and freezing. :(

**Comment by hfog** [comment]
Let me clarify that a little bit. My test case for this has been a benchy printing at 150mm/s sliced with Cura. There are enough curves and short travels here that the amount of gcode pushed over the serial cable is significant. Octoprint hooked directly to the printer works fine. Passing through the TFT it overwhelms the pipe and code gets dropped, resulting in an error state on the printer. (At least that's my current working theory.) If I slow the print down to reasonable speeds (50mm/s) it seems to work just fine.

**Comment by bagobor** [comment]
@hfog have you tried to increase UART buffer in marlin firmware?

**Comment by hfog** [comment]
> @hfog have you tried to increase UART buffer in marlin firmware?

I have not. But I don't encounter any problems when Octoprint is directly connected to the printer so I would be surprised if that would help. Still, it's something to try so I'll probably give it a go.

**Comment by bagobor** [comment]
@hfog just to be sure it's not related. Another thing to try is to increase 
#define DMA_TRANS_LEN  ACK_MAX_SIZE 
ie
#define DMA_TRANS_LEN  (ACK_MAX_SIZE*2)
(2 places in Serial.h files, in TFT firmware)

And similar issue was addressed here: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/commit/9dc60e5df4dd4dedc333557cd4b311a25dc43d44
Maybe you'll find some other places to tweak.

**Comment by bagobor** [comment]
@hfog  I see you were desperate enough to fork it.  I'm thinking about why slow gcode sending may result in error printer state. It should be either some garbage on receiving end due to TFT's buffer or TFT's inability to handle incoming sync commands from marlin.  anything else?

**Comment by hfog** [comment]
Desperate is rather overstating it. Forking was the easiest way to get a stable environment to test in and contribute a fix to the problem.
I agree that either something is corrupting the communication or the TFT isn't correctly handling sync commands. I'm leaning toward the former but honestly, who knows?

**Comment by bagobor** [comment]
@hfog that's why I was suggesting to increase different buffers as it may reveal some correlations. Should one be able to repro it by slicing Benchy at 150mm/s and printing it from TFT's SD in touch mode?

**Comment by hfog** [comment]
@bagobor Perhaps printing from SD in touch mode would repro it but printing from the UART3 port is probably stressing it even farther because it has to maintain communication in two directions at once.

**Comment by hfog** [comment]
I'm pretty sure that what's going on is that the TFT is polling Marlin for certain information at the same time as Octoprint is printing. See this thread: https://github.com/MarlinFirmware/Marlin/issues/16894 and this one: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/193
I've discovered that if I print my 150mm/s benchy through the TFT when it's NOT on a screen that is tracking statistics such as XYZ coords and temps then it succeeds and it doesn't seem to pause.

**Comment by Sewyboowy** [comment]
Hello,
I am having an issue where my prints completely stop seemingly randomly during a print, #244 
Do you think this may be the cause?

**Comment by hfog** [comment]
This is likely a contributing factor but probably not the only cause. I have been looking into it here and there but so far I haven't been able to solve it completely. I think it's related to the TFT polling Marlin for information because if I'm on a TFT screen that doesn't show any live updating status the problem seems to go away.

**Comment by bagobor** [comment]
@Sewyboowy are you using latest TFT firmware?

**Comment by Sewyboowy** [comment]
Yes using the latest TFT firmware and marlin from about a week ago (which other people have working fine).

I should note that I'm using a delta which I thought may be relevant as a delta has to make more, smaller moves typically. I thought all of that should be handled by the main board (SKR Pro v1.1) so I'm  sure why that'd matter

**Comment by bagobor** [comment]
@Sewyboowy "LCD12864 sim mode" is using i2s connection like a real LCD12864 display. In this mode, your printer board is requesting data from SD card directly.
Can you please try to enable marlin's debug options and check printer's log and state just after build fail? 
As an alternative idea: try to enable Board's SD card and print from it to confirm it's not related to TFT  board.

**Comment by AnHardt** [comment]
> "LCD12864 sim mode" is using i2s connection like a real LCD12864 display.

No. The simulated display is a ST7920 based. That is SPI.

**Comment by bagobor** [comment]
@AnHardt thanks for the correction!

**Comment by Sewyboowy** [comment]
Just tried a print in TFT mode with repetier connected. No errors recorded in repetier. I did get some over temp errors before the print whilst in LCD12864 sim mode tho. I re flashed my firmware with a lower current but it isn't going down for some reason. When I lower it with gcode the print starts but the extruder doesn't move.

**Comment by CRCinAU** [comment]
So while trawling through issues / fixes - Make sure you're running the latest Marlin bugfix-2.0.x from github on your controller board. The issue referenced above with respect to handling the M114 command from the TFT has drastic issues in print quality. No change on the TFT Firmware will fix this.

Please do your testing after the updating to the latest bugfix-2.0.x version of Marlin and report if your issue is resolved or not.

**Comment by Sewyboowy** [comment]
Ok so I updated to the latest bugfix and started getting an error where if I inserted my SD card, I'd get a "Media removed" message and when I took it out, I got a "Media inserted" message.
Went back to my previous firmware and disabled soft_pwm. When I ran a print it still failed, but disconnected from my PC. I think that it completely reset but i'm not sure why.
Any ideas?

**Comment by Sewyboowy** [comment]
Tried again printing from PC. It failed and I got this

17:56:47.984 : Error:Line Number is not Last Line Number+1, Last Line: 16919
17:56:47.984 : Resend: 16920
17:56:48.064 : echo:Unknown command: "??1.558 E1199.79"
17:56:48.349 : //action:notification ETE 3h 27m 03s
17:56:53.452 : //action:notification ETE 3h 26m 58s
17:56:59.071 : //action:notification ETE 3h 26m 52s
17:57:03.730 : //action:notification ETE 3h 26m 47s
17:57:08.806 : //action:notification ETE 3h 26m 42s
17:57:13.712 : //action:notification ETE 3h 26m 37s
17:57:18.005 : Error:Line Number is not Last Line Number+1, Last Line: 17744
17:57:18.005 : Resend: 17745
17:57:18.022 : echo:Unknown command: "?"
17:57:18.022 : echo:Unknown command: "?E1228.813"
17:57:18.022 : echo:Unknown command: "X?<n3.766 Y2N17746 G1 X-28.842 Y-14.982 E1228.855 F1800"
17:57:18.022 : Error:Line Number is not Last Line Number+1, Last Line: 17744
17:57:18.022 : Resend: 17745
17:57:18.068 : Error:Line Number is not Last Line Number+1, Last Line: 17751
17:57:18.068 : Resend: 17752
17:57:18.293 : Error:checksum mismatch, Last Line: 17754
17:57:18.293 : Resend: 17755
17:57:18.380 : Error:checksum mismatch, Last Line: 17757
17:57:18.380 : Resend: 17758
17:57:18.769 : Error:checksum mismatch, Last Line: 17764
17:57:18.769 : Resend: 17765
17:57:18.874 : //action:notification ETE 3h 26m 32s
17:57:20.336 : Error:Line Number is not Last Line Number+1, Last Line: 17799
17:57:20.336 : Resend: 17800
17:57:20.352 : echo:Unknown command: "L?Y-13.327"
17:57:20.352 : echo:Unknown command: "?9"
17:57:20.352 : echo:Unknown command: "g:28.207 Y15.844"
17:57:20.571 : Printing layer 6 of 248
17:57:20.711 : Error:Line Number is not Last Line Number+1, Last Line: 17812
17:57:20.711 : Resend: 17813
17:57:20.743 : Error:Line Number is not Last Line Number+1, Last Line: 17812
17:57:20.743 : Resend: 17813
17:57:20.836 : Error:Line Number is not Last Line Number+1, Last Line: 17813
17:57:20.852 : Resend: 17814
17:57:21.118 : echo:Unknown command: "?u6 Z1.3 F600"
17:57:21.118 : Error:checksum mismatch, Last Line: 17813
17:57:21.118 : Resend: 17814
17:57:21.211 : Error:checksum mismatch, Last Line: 17816
17:57:21.211 : Resend: 17817
17:57:21.227 : Error:checksum mismatch, Last Line: 17816
17:58:01.240 : Communication timeout - reset send buffer block
17:58:01.240 : Error:Line Number is not Last Line Number+1, Last Line: 17816
17:58:41.272 : Communication timeout - reset send buffer block
17:58:41.272 : Error:Line Number is not Last Line Number+1, Last Line: 17816
17:59:21.338 : Communication timeout - reset send buffer block
17:59:21.338 : Error:Line Number is not Last Line Number+1, Last Line: 17816
18:00:01.382 : Communication timeout - reset send buffer block
18:00:01.382 : Error:Line Number is not Last Line Number+1, Last Line: 17816
18:00:41.441 : Communication timeout - reset send buffer block
18:00:41.441 : Error:Line Number is not Last Line Number+1, Last Line: 17816
18:01:21.495 : Communication timeout - reset send buffer block
18:01:21.495 : Error:Line Number is not Last Line Number+1, Last Line: 17816
18:02:01.583 : Communication timeout - reset send buffer block
18:02:01.583 : Error:Line Number is not Last Line Number+1, Last Line: 17816
18:02:41.584 : Communication timeout - reset send buffer block
18:02:41.584 : Error:Line Number is not Last Line Number+1, Last Line: 17816
18:03:21.689 : Communication timeout - reset send buffer block
18:03:21.689 : Error:Line Number is not Last Line Number+1, Last Line: 17816
18:04:01.754 : Communication timeout - reset send buffer block
18:04:01.754 : Error:Line Number is not Last Line Number+1, Last Line: 17816
18:04:41.847 : Communication timeout - reset send buffer block
18:04:41.847 : Error:Line Number is not Last Line Number+1, Last Line: 17816
18:05:21.895 : Communication timeout - reset send buffer block
18:05:21.898 : Error:Line Number is not Last Line Number+1, Last Line: 17816
18:05:21.898 : Error:Line Number is not Last Line Number+1, Last Line: 17816
18:05:21.898 : Resend: 17817
18:05:21.914 : echo:Unknown command: "9"
18:05:22.101 : //action:notification ETE 3h 26m 29s
18:05:27.176 : //action:notification ETE 3h 26m 24s
18:05:32.284 : //action:notification ETE 3h 26m 19s

Then it started again (which I believe is the last 3 lines). What is happening?!?!

**Comment by bagobor** [comment]
@Sewyboowy it looks like a lot of corrupted communication messages. Try to use shorter or other USB cable/port.

**Comment by bjoernwedi** [comment]
> @Sewyboowy "LCD12864 sim mode" is using i2s connection like a real LCD12864 display. In this mode, your printer board is requesting data from SD card directly.
> Can you please try to enable marlin's debug options and check printer's log and state just after build fail?
> As an alternative idea: try to enable Board's SD card and print from it to confirm it's not related to TFT board.

Deal all,

I was using skr 1.4 and skr e3 dip with bigger rx buffers in marlin (128bytes) and printed via the printer‘s onboard so card in tft marlin simulation mode. With fuzzy skin (to Stress the Printer serial) and 80-100mm/sec the Printer stutters and results in blob artifacts on the print.

INTERESTING: If i remove the Black tft serial cable, the print is Fine!!!

So i assimiliertes, that in sim Mode the buffer is exhausted on marlin and the printer stucks until the buffer is flushed.

**Comment by thisiskeithb** [comment]
@bigtreetech @Msq001 Can you review this PR and see if it can/should be merged?

**Comment by digant73** [comment]
@bagobor A lot of improvements were made after your PR. Please can you close your PR if you are satisfied with the current implementation?

**Pull request closed without merging**
