### PR TITLE
Release xx.26.1

### PR DESCRIPTION
**Pull request by Lecl0ne**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

Ability to set a custom RGB888 color to the "Knob LED Color" option.

### Benefits

Some proposed colors are not accurate (orange for example) and don't fit with my color-customized printer.

### Related Issues

No related issue.

### CODE REVIEW

**Comment by traffic-light** [comment]
You know you created a pull request to merge a older version of the firmware?

Can you remove this pull request?

**Comment by Lecl0ne** [comment]
So sorry for the beginner mistake. I close it but can't find how to remove
it.
I wanted to submit a suggestion but it looks like this was the wrong way..

**Comment by traffic-light** [comment]
You can create that on the issues tab.

**Comment by burakturkoglu54** [comment]
> #1655

**Comment by burakturkoglu54** [comment]
Duplicate of #

**Comment by burakturkoglu54** [comment]
Duplicate of #

**Comment by burakturkoglu54** [comment]
#1661

**Pull request closed without merging**
