### PR TITLE
Added calibration.bmp to Hybrid Mono theme

### PR DESCRIPTION
**Pull request by bepstein111**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

Adding calibration.bmp (which was previously missing) to my Hybrid Mono theme (which is just a photoshopped version of the fantastic Hybrid Red theme by @AntoszHUN)

### Benefits

new icon

### Related Issues

#2084

### CODE REVIEW

**Comment by ETE-Design** [comment]
@bepstein111 Mabye you could make a "Mono" theme for -Unified Menu Material- also?

**Comment by Guilouz** [comment]
@bepstein111 Please check all your status icons for TFT70 in your theme, they have wrong size, 160x140 and they must be 130x160.

**Comment by bepstein111** [comment]
@Guilouz good catch! thanks for going ahead and doing that! saves me time! will get that included today.

@ETE-Design Sure thing! I'll look into it!

**Comment by bepstein111** [comment]
Just pushed that commit!

**Comment by Guilouz** [comment]
@bepstein111 Need printing_chamber.bmp for other TFT size and it will be good.

**Comment by digant73** [comment]
@bepstein111 the "status_chamber.bmp" icon is present only for TFT70. It is missing on all the other TFTs

**Comment by bepstein111** [comment]
> @bepstein111 the "status_chamber.bmp" icon is present only for TFT70. It is missing on all the other TFTs

Fixed....unsure if I need to make a new pull request??

**Pull request merged**
