### PR TITLE
New Round Miracle icons for PR 2054

### PR DESCRIPTION
**Pull request by radek8**
New Round Miracle icons for PR 2054

### CODE REVIEW

**Comment by oldman4U** [comment]
Radek is now Acenotass

😳

**Comment by radek8** [comment]
Acenotass had no activity on github for a long time

**Comment by oldman4U** [comment]
Thank you for taking over. Can I mention you next time I change the ReadMe?

**Comment by radek8** [comment]
Rather not. I don't want him to think I stole his work when he comes back :-)

**Pull request merged**
